### ISSUE TITLE
include builds with each release

### ISSUE THREAD

**Issue by leo-baltus** [prometheus/jmx_exporter#100]
I was wondering why are there no builds available on each release?

**Comment by brian-brazil** [comment]
All builds are on the central repository.

**Comment by leo-baltus** [comment]
You mean mvnrepository.com? I was looking for the jmx_prometheus_httpserver-0.8-SNAPSHOT-jar-with-dependencies.jar but could not find it.

**Comment by brian-brazil** [comment]
That's a snapshot, you'd have to build that yourself.

**Comment by leo-baltus** [comment]
Where can I find the jar-with-dependencies.jar ?

**Comment by brian-brazil** [comment]
It'll be under the target directory.

**Comment by leo-baltus** [comment]
Sorry for not beeing clear. I am trying to avoid building it myself. So I was looking for url where all builds would be ready to download, including the -with-dependencies- stuff.

**Comment by brian-brazil** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.prometheus.jmx%22
