### ISSUE TITLE
Do not get attribute value when attribute name does not match any rule

### ISSUE THREAD

**Issue by elecnix** [prometheus/jmx_exporter#102]
I'm trying to scrape a third-party MBean which includes getters that have side-effects. My yaml configuration contains a single pattern matching an other attribute, but JmxScraper still invokes the problematic getter before passing it to JmxCollector for evaluation.

**Comment by brian-brazil** [comment]
We can't do this, as we need the value in order to create the string the pattern is applied to. Your only option is to blacklist the mbean.

**Comment by elecnix** [comment]
Why is the value part of the pattern to be matched?

**Comment by brian-brazil** [comment]
It might be a string label you want to extract.
