### ISSUE TITLE
feature request: Support includeObjectNameAttributes

### ISSUE THREAD

**Issue by jacksparrow414** [prometheus/jmx_exporter#1041]
Hi, Community. 

When using jmx-exporter, we have few metrics to monitor. Although we have filtered by `includeObjectNames`, each MBean still has dozens of attributes, and we may only need one or two. I noticed that there is `excludeObjectNameAttributes`, but it requires listing many attributes that we don't need. 

Will the community consider adding support for `includeObjectNameAttributes`? If so, we have already implemented this feature based on the source code and we can contribute it to the community

**Comment by dhoard** [comment]
@jacksparrow414 Create a PR based on the latest code so it can be reviewed.
