### ISSUE TITLE
feature request: use type without name

### ISSUE THREAD

**Issue by automaticgiant** [prometheus/jmx_exporter#107]
i would like to not write transforms for everything, but to just be able to match a pattern for attribute to be able to use default naming/transform but say this pattern is count instead of gauge.
only gets important with scaling. i suspect prometheus and others have a more efficient representation of counts than gauges due to one being monotonic.

**Comment by brian-brazil** [comment]
> i would like to not write transforms for everything, but to just be able to match a pattern for attribute to be able to use default naming/transform but say this pattern is count instead of gauge.

The default naming is hardcoded, and there's no plans to expose it as anything beyond a best-effort default. It's mainly there for historical reasons, though it does do fairly well.

> i suspect prometheus and others have a more efficient representation of counts than gauges due to one being monotonic.

The storage engine has no knowledge of this.
