### ISSUE TITLE
Content-Type header for Prometheus 3.0.0

### ISSUE THREAD

**Issue by jcpunk** [prometheus/jmx_exporter#1084]
### Is your feature request related to a problem? Please describe.

Prometheus 3.0.0 has the option (by default) to be far more strict about what content it scrapes. This can cause unexpected scrape failures for the prometheus exporter.

### Describe the solution you'd like

Set the header "to the correct value". 

### Describe alternatives you've considered

If a scrape target is not providing the correct Content-Type header the fallback protocol can be specified using the fallback_scrape_protocol parameter. 

### Additional context

From : https://prometheus.io/docs/prometheus/3.0/migration/
> Prometheus v3 is more strict concerning the Content-Type header received when scraping. Prometheus v2 would default to the standard Prometheus text protocol if the target being scraped did not specify a Content-Type header or if the header was unparsable or unrecognised. This could lead to incorrect data being parsed in the scrape. Prometheus v3 will now fail the scrape in such cases.

**Comment by dhoard** [comment]
@jcpunk can you elaborate?

The content type/content returned is based on the request `ACCEPT` header. If the `ACCEPT` header doesn't match known values, it fails back to Prometheus text format.

Fixes/changes require changes in the `client_java` library dependency.

Reference: 

https://github.com/prometheus/client_java/blob/99d3dec20372ddd26480bb9405c398b6fb9ab016/prometheus-metrics-exposition-textformats/src/main/java/io/prometheus/metrics/expositionformats/ExpositionFormats.java#L33-L41

**Comment by jcpunk** [comment]
Unfortunately I don't understand much beyond: https://prometheus.io/docs/prometheus/3.0/migration/#scrape-protocols my local `curl` of the JMX exporter doesn't have the header, but that may be the wrong way to test.

**Comment by dhoard** [comment]
@jcpunk I found some issues in the integration tests around testing OpenMetrics and Protobuf formats. As part of the fix, I added code to validate the HTTP `Content-Type`.

The JMX Exporter code is working correctly.

Can you provide the full curl command you are using?

**Comment by jcpunk** [comment]
I'm running `curl -i http://127.0.0.1:9346/metrics`

**Comment by dhoard** [comment]
# Prometheus Code

Per the Prometheus source code...

https://github.com/prometheus/prometheus/blob/af2a1cb10c89de496cd4309ac532624b34112d74/config/config.go#L516-L521

```
	ScrapeProtocolsHeaders = map[ScrapeProtocol]string{
		PrometheusProto:      "application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited",
		PrometheusText0_0_4:  "text/plain;version=0.0.4",
		PrometheusText1_0_0:  "text/plain;version=1.0.0;escaping=allow-utf-8",
		OpenMetricsText0_0_1: "application/openmetrics-text;version=0.0.1",
		OpenMetricsText1_0_0: "application/openmetrics-text;version=1.0.0",
```

The JMX Exporter supports...

- PrometheusProto
- PrometheusText0_0_4
- OpenMetricsText1_0_0

The mapped `Accept` header values for...

- PrometheusText1_0_0
- OpenMetricsText0_0_1

... have never been supported by the JMX Exporter. Maybe they should be. This would required a change in `client_java` since it creates the metric output.

# HTTP Conten-Type Header Testing

No `Accept` header -> output is correct...

Command...

```
curl -i http://localhost:51270/metrics
```

Output...

```
HTTP/1.1 200 OK
Date: Sat, 07 Dec 2024 05:45:32 GMT
Content-type: text/plain; version=0.0.4; charset=utf-8
Content-length: 67018

# HELP io_prometheus_jmx_autoIncrementing_Value Attribute exposed for management 
...
```

---

With `Accept` header of `text/plain` -> output is correct...

Command...

```
curl -i -H "Accept: text/plain" http://localhost:51270/metrics
```

Output...

```
HTTP/1.1 200 OK
Date: Sat, 07 Dec 2024 05:45:32 GMT
Content-type: text/plain; version=0.0.4; charset=utf-8
Content-length: 67018

# HELP io_prometheus_jmx_autoIncrementing_Value Attribute exposed for management 
...
```

---

With `Accept` header of `application/openmetrics-text` -> output is correct...

Command...

```
curl -i -H "Accept: application/openmetrics-text" http://localhost:51270/metrics
```

Output...

```
HTTP/1.1 200 OK
Date: Sat, 07 Dec 2024 05:52:28 GMT
Content-type: application/openmetrics-text; version=1.0.0; charset=utf-8
Content-length: 67036

# TYPE io_prometheus_jmx_autoIncrementing_Value unknown
...
```

---

With `Accept` header of `application/vnd.google.protobuf; proto=io.prometheus.client.MetricFamily` -> output is correct...

Command...

```
curl -i -H "Accept: application/vnd.google.protobuf; proto=io.prometheus.client.MetricFamily" http://localhost:51270/metrics
```

Output...

```
HTTP/1.1 200 OK
Date: Sat, 07 Dec 2024 05:57:41 GMT
Content-type: application/vnd.google.protobuf; proto=io.prometheus.client.MetricFamily; encoding=delimited
Content-length: 41400

<binary data>
```

**Comment by jcpunk** [comment]
Turns out my prometheus config incorrectly called those `jmx-exporter` when there were another product.  Guess I should have checked the metrics too ;)

Sorry for the noise.
