### ISSUE TITLE
More Robust JMX connection settings

### ISSUE THREAD

**Issue by cetra3** [prometheus/jmx_exporter#11]
At the moment with the HTTP Server configuration, when trying to query a remote MBean server, the options provided won't allow you to specify a different service URL or a username and password to connect. You should be able to specify the same options as jconsole.

#### Remote Process URL
This is currently hardset in `JmxScraper`:
```java
String url = "service:jmx:rmi:///jndi/rmi://" + hostPort + "/jmxrmi";
```
This should be fully configurable as some MBean servers are at different URLs.

#### Username and Password

The environment passed is `null`, you should be able to pass in env variables to set the username and password for the connection.  Something like:

```java
Map<String,Object> env=new HashMap<String,Object>();
env.put(JMXConnector.CREDENTIALS,new String[]{username,password});
jmxc = JMXConnectorFactory.connect(new JMXServiceURL(url), env);
```

**Comment by brian-brazil** [comment]
Thanks for the report, is it just the "/jmxrmi" that should be configurable or is there more that someone could could theoretically want to configure?

**Comment by cetra3** [comment]
Created a pull request for this issue: https://github.com/prometheus/jmx_exporter/pull/12

**Comment by brian-brazil** [comment]
This was implemented.
