### ISSUE TITLE
Update dependency to latest client_java (v0.0.21)

### ISSUE THREAD

**Issue by marcuslinke** [prometheus/jmx_exporter#119]
I found that the latest release of jmx_exporter (v0.8) depends on version 0.0.8 of the client_java lib. Meanwhile as there is version 0.0.21 of the lib available is there any reason not to upgrade? I stumbled upon it as there are much more [default exports](https://github.com/prometheus/client_java/blob/master/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/DefaultExports.java) like threads for example now which would be really usable.

**Comment by brian-brazil** [comment]
The latest release uses 0.0.21.

**Comment by marcuslinke** [comment]
Looking at the master branch it seems it does not: https://github.com/prometheus/jmx_exporter/blob/master/jmx_prometheus_javaagent/pom.xml#L26

**Comment by brian-brazil** [comment]
That's fixed and released now.

**Comment by marcuslinke** [comment]
@brian-brazil Thanks!
