### ISSUE TITLE
Jmx config file "kafka-0-8-2.yml", does not fetch metrices for kafka version "kafka_2.10-0.8.1.1.3"

### ISSUE THREAD

**Issue by taherbohari** [prometheus/jmx_exporter#120]
- I want to monitor kafka version "kafka_2.10-0.8.1.1.3" using jmx exporter
- I followed steps mentioned here : https://www.robustperception.io/monitoring-kafka-with-prometheus/
- kafka service gets started but when I see for the kafka metrics at  http://localhost:7071/metrics , I only get to see the jmx metrics and not the kafka metrics.
- when I installed kafka version mentioned in the blog, then I am able to see all the metrices.
- Please let me know which config file to use to get all kafka metrics for version "kafka_2.10-0.8.1.1.3"

**Comment by brian-brazil** [comment]
That's as expected, as that config file is for kafka 0.8.2 or later. Use the other kafka config example.

**Comment by taherbohari** [comment]
Thanks @brian-brazil  for the reply. I have used other config file and it's working. But I am not getting enough metrices like I was getting for kafka-2.11 with 'kafka-0-8-2.yml' file. Can you please let us know how can I add more rules/metrics in it?
