### ISSUE TITLE
unable to get jmx_prometheus_javaagent-0.8-SNAPSHOT-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by sunnyphulphagar** [prometheus/jmx_exporter#125]
Hi,

From where i can get jmx_prometheus_javaagent-0.8-SNAPSHOT-jar-with-dependencies.jar?

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!aboutgroup/prometheus-users
