### ISSUE TITLE
Unterminated key property part

### ISSUE THREAD

**Issue by hrecho** [prometheus/jmx_exporter#129]
hi guys, i am sorry if this is not the right place to ask

i am getting javax.management.MalformedObjectNameException: Unterminated key property part
while trying to ...
`new ObjectName("Tomcat:type=ThreadPool,name=\"http-nio-8080\"/currentThreadsBusy");`

thanks in advance

**Comment by brian-brazil** [comment]
User questions are best asked at https://groups.google.com/forum/#!forum/prometheus-users

Though this appears to be a general JMX question unrelated to Prometheus, so a Java forum may be better.
