### ISSUE TITLE
HTTP server TLS configuration

### ISSUE THREAD

**Issue by anton-pydev** [prometheus/jmx_exporter#132]
It is not clear from documentation whether jmx_exporter http server can expose metrics endpoint via HTTPS  , 
And if it's possible to protect the endpoint with TLS mutual authentication .
Looking at the source code I see that TLS is not supported , but probably I am missing something .

**Comment by brian-brazil** [comment]
It can't, as with all Prometheus components you'll need a reverse proxy such as nginx.

**Comment by anton-pydev** [comment]
Thanks.
