### ISSUE TITLE
Gzip compression code removes fix for machines with alot of cpu cores

### ISSUE THREAD

**Issue by cfrantsen** [prometheus/jmx_exporter#148]
#137 breaks #124 by removing setAcceptor() resulting in the following error on my test machines that has 32 cores.

Caused by: java.lang.IllegalStateException: Insufficient threads: max=10 < needed(acceptors=4 + selectors=8 + request=1)

@erebe

**Comment by brian-brazil** [comment]
Would you like to send a PR fixing this?

**Comment by erebe** [comment]
I can have a look into it tomorow @cfransten if you tell me how to reproduce it

**Comment by cfrantsen** [comment]
To reproduce simply start a java process with the agent configured on a machine with lot's of cores, 16+ should do it I think.

Looking at http://www.eclipse.org/jetty/javadoc/9.4.6.v20170531/org/eclipse/jetty/server/ServerConnector.html it seems simple enough to just use `ServerConnector(Server server, int acceptors, int selectors)` with some sane parameter values to fix this.

When acceptors are set to 0 selector threads are used instead so 0 acceptors and 10 selectors would mimic the previous behavior.

**Comment by cfrantsen** [comment]
Perhaps `setAcceptQueueSize(int acceptQueueSize)` should be used as well to limit the backlog as `setMaxQueued()` was also removed by the gzip commit.

**Comment by erebe** [comment]
Ok Thanks for pointing to the doc. 
I will try to reproduce and fix it tomorow if you haven't done it in the mean time.

**Comment by erebe** [comment]
@cfrantsen I haven't changed the setAcceptQueueSize as it has a different semantic than the setMaxQueued from the previous code.

If you also can test the PR I will be glad

**Comment by brian-brazil** [comment]
If someone can confirm this works, I shall merge.

**Comment by cfrantsen** [comment]
I can test it out later today or tomorrow.

**Comment by brian-brazil** [comment]
#152 might mean we have to change this again if true.

**Comment by brian-brazil** [comment]
Can you try the latest head? We've switched away from jetty.

**Comment by cfrantsen** [comment]
Seems to be working fine. Tested on WebLogic/JDK8 on a 32 core (16 physical + 16 HT) machine where each JVM is binding to one unique IP/hostname.

**Comment by brian-brazil** [comment]
Great! I'll wait a bit for others to confirm this fixes everything without new regressions, and then release.

**Comment by brian-brazil** [comment]
That's released.
