### ISSUE TITLE
Make prometheus endpoitn configurable

### ISSUE THREAD

**Issue by udaraliyanage** [prometheus/jmx_exporter#149]
Hi,

As I understood prometheus endpoint is hardcoded. Shall we make it configurable?

context.addServlet(new ServletHolder(new MetricsServlet()), "/metrics");

**Comment by brian-brazil** [comment]
Why do you need to change? It's the only thing on the port, and /metrics is the standard endpoint.

**Comment by udaraliyanage** [comment]
For instance springboot apps already have /metrics for actuator. There we using /prometheus for prometheus stats. While it is technically still possible to use /prometheus since agent runs in a different port, just thought of having /prometheus so anyone understand that this is prometheus output by looking at configuration.

**Comment by brian-brazil** [comment]
I don't see the confusion here. /metrics is the standard for Prometheus so your argument is basically that Promethus should change its standard everywhere to /prometheus - which isn't going to happen.

I'm not in favour of allowing users to make their setup more complicated and non-standard just in case  it might be easier for the odd users to understand what an endpoint means.

**Comment by mindfulmonk** [comment]
It would be good if it was configurable.

The official exporters like node, consul and mysql already have a`web.telemetry-path`
