### ISSUE TITLE
Jetty update breaks compatibility with jdk < 8

### ISSUE THREAD

**Issue by cfrantsen** [prometheus/jmx_exporter#152]
#137 upgraded jetty to 9.4 which requires JDK8, which in turn means jmx_exporter is not usable on systems running older JDK versions. I'm not quite sure what the goal is in terms of JDK support is but only supporting JDK8 seems lika problem.

http://www.eclipse.org/jetty/documentation/9.4.x/what-jetty-version.html

**Comment by brian-brazil** [comment]
Our target is 1.6, and our poms say 1.5. How did this compile if that's the case?

**Comment by cfrantsen** [comment]
I'm not really familiar with how pom's etc work but after building, all flavours of class files are included in the final jar :-)
```
$ mvn dependency:purge-local-repository && mvn -U clean package
<unpack jar-file>
$ find . -name *.class -exec file -b {} \; | sort | uniq
compiled Java class data, version 48.0 (Java 1.4)
compiled Java class data, version 49.0 (Java 1.5)
compiled Java class data, version 50.0 (Java 1.6)
compiled Java class data, version 51.0 (Java 1.7)
compiled Java class data, version 52.0 (Java 1.8)
```

**Comment by cfrantsen** [comment]
When building with JDK7/8 this is the version distribution of class files.
io.prometheus.jmx: 1.5
io.prometheus.client: 1.6
org.yaml.snakeyaml: 1.5
org.eclipse.jetty: 1.8
org.mortbay: 1.4
javax.servlet: 1.7

**Comment by erebe** [comment]
Indeed, building the HEAD of the repo on docker 6-jdk return this build failure.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project jmx_prometheus_httpserver: Compilation failure
[ERROR] /mnt/jmx_exporter/jmx_prometheus_httpserver/src/main/java/io/prometheus/jmx/WebServer.java:[4,-1] cannot access org.eclipse.jetty.server.Server
[ERROR] bad class file: ZipFileIndexFileObject[/root/.m2/repository/org/eclipse/jetty/jetty-server/9.4.3.v20170317/jetty-server-9.4.3.v20170317.jar(org/eclipse/jetty/server/Server.class)]
[ERROR] class file has wrong version 52.0, should be 50.0
[ERROR] -> [Help 1]
```

and trying to run the jar builded with a jdk8 return this error at runtime
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/prometheus/jmx/WebServer : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: io.prometheus.jmx.WebServer. Program will exit.
```
It still kind of feel strange that It does not produce a compile time error with a jdk-8.

Don't have a magic solution here, either bump the requirement to a jdk-7 and downgrade to jetty 9.2.21.v20170120 or revert the gzip compression.

Your call @brian-brazil

**Comment by brian-brazil** [comment]
Downgrade is the route to go, and we'll need to do similar over in the client. If we lose gzip we lose gzip.

**Comment by erebe** [comment]
#153

**Comment by cfrantsen** [comment]
If I'm not missing something jetty upgraded to solve #94 so gzip compression should still be possible to implement with this older version of jetty

See https://github.com/prometheus/jmx_exporter/pull/95#issuecomment-260755688 for info.

**Comment by brian-brazil** [comment]
We could always switch to a plain httpserver once that's implemented over in the client, that'd avoid pretty much all the problems we've seen here.

**Comment by erebe** [comment]
I already have forked the project (due to unrelated reasons) and I am not willing to go around the trouble to try to re-add the feature @cfrantsen.
Maybe when I have more to share, I will try to reintegrate it, but not for now.
Feels free to take the releave :)
