### ISSUE TITLE
jmx-exporter never responds to metrics request

### ISSUE THREAD

**Issue by oleksiys** [prometheus/jmx_exporter#157]
After running a bm test on 5 cassandra nodes, jmx-exporter stops responding to metrics requests (on all the nodes). Scraper connection is accepted, but response never delivered.
Cassandra stacktraces contains interesting info (attached), looks like several (jetty) threads are blocked on write, while one of them constantly generating something that looks like an error log.
I don't see nothing in the cassandra log, which might be related to the problem.

jmx-exporter version: 0.9
cassandra version: 3.10
os: linux
java: jdk1.8.0_131

[stacktraces.txt](https://github.com/prometheus/jmx_exporter/files/1086065/stacktraces.txt)

**Comment by brian-brazil** [comment]
I'm going to presume this is another form of #156
