### ISSUE TITLE
Possible heap issue with JBoss EAP

### ISSUE THREAD

**Issue by choppedpork** [prometheus/jmx_exporter#167]
Hello,

I've been tasked with monitoring a legacy JBoss EAP application and seeing as we're already using Prometheus in-house, jmx_exporter seems to be the way to go. Unfortunately I can't run it as an agent - the legacy application provides an engine to run Groovy scripts and adding agents (the same thing happens with agent bond and Jolokia) causes classloader issues that prevent the scripts from executing.

But that's ok because jmx_exporter has a standalone HTTP mode. Unfortunately JBoss EAP being... well, JBoss, it does not use the standard JMX protocol and opts for a custom remoting-jmx / remoting3 implementation. After struggling for a while with adding jboss-client.jar to the classpath and not succeeding I have finally managed to get it to work by making the following change to the pom file and rebuilding it:
```
--- a/collector/pom.xml
+++ b/collector/pom.xml
@@ -31,6 +31,23 @@
       <artifactId>snakeyaml</artifactId>
       <version>1.16</version>
     </dependency>
+    <dependency>
+    <groupId>org.jboss.as</groupId>
+    <artifactId>jboss-as-ejb-client-bom</artifactId>
+    <type>pom</type>
+    <version>7.2.0.Final</version>
+</dependency>
+<dependency>
+    <groupId>org.jboss.as</groupId>
+    <artifactId>jboss-as-jms-client-bom</artifactId>
+    <type>pom</type>
+    <version>7.2.0.Final</version>
+</dependency>
+<dependency>
+    <groupId>org.jboss.remoting3</groupId>
+    <artifactId>remoting-jmx</artifactId>
+    <version>1.0.1.Final</version>
+</dependency>
   </dependencies>
```

This now works great and I can get all 2.5k+ (mostly useless) metrics out. Here's my config file - I'm limiting what is being extracted quite severely as I'm only interested in the heap/memory/gc and datasource metrics. Here's my config:
```
jmxUrl: service:jmx:remoting-jmx://localhost:9999
ssl: false
username: xx
password: xx
whitelistObjectNames: ["java.lang:*","jboss.as:subsystem=datasources,*"]
```
This results in ~293 metrics being available to Prometheus.
Unfortunately, I've noticed that the memory was growing quite rapidly overnight (this was with an unbounded / default heap) - the metric used is `container_memory_rss` from cAdvisor:
![screen shot 2017-07-20 at 12 10 28](https://user-images.githubusercontent.com/11997044/28414648-959aea40-6d44-11e7-9484-189e75705460.png)
I've since tried limiting memory using -Xms -Xmx, starting at (overly optimistic I guess) 32m, then 64m and now at 96m. Every attempt has unfortunately resulted in heap errors:
```
2017-07-19 23:15:40.572:WARN:oejs.ServletHandler:Error for /metrics
java.lang.OutOfMemoryError: Java heap space
2017-07-19 23:16:40.371:WARN:oejs.ServletHandler:Error for /metrics
java.lang.OutOfMemoryError: Java heap space
2017-07-19 23:17:40.500:WARN:oejs.AbstractHttpConnection:/metrics
java.lang.OutOfMemoryError: GC overhead limit exceeded
2017-07-19 23:18:40.364:WARN:oejs.ServletHandler:Error for /metrics
java.lang.OutOfMemoryError: Java heap space
2017-07-19 23:19:40.423:WARN:oejs.ServletHandler:Error for /metrics
java.lang.OutOfMemoryError: Java heap space
Exception in thread "qtp1099855928-20" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "qtp1099855928-21"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "qtp1099855928-21"
```
I've captured a heap dump and attempted at analyzing it with VisualVM - sadly this is a little bit outside of my skillset so not sure if what I found is of relevance but here it is:
![screen shot 2017-07-20 at 12 17 54](https://user-images.githubusercontent.com/11997044/28414920-7f3f5758-6d45-11e7-9eb8-a9b03c674675.png)
Obviously, a lot of those are probably legitimate but here's something I wasn't expecting:
![screen shot 2017-07-20 at 12 19 14](https://user-images.githubusercontent.com/11997044/28414973-b0ba0698-6d45-11e7-84f4-86701a5139d6.png)

A _very_ substantial amount of the char[] instances (~1500 from what I can see) is 65k of zeroes. I'd be quite happy to provide the heapdump if this would help diagnosing this.

Thanks in advance!
Simon

**Comment by brian-brazil** [comment]
If you've modified the jmx exporter and are having problems, the presumption is that the modification is the issue. 

From a quick search there are multiple reports of issues with these integrations. Per https://issues.jboss.org/browse/REMJMX-45 try 1.0.4.Final.

This is not something we can practically support though.

**Comment by choppedpork** [comment]
Thanks for pointing me in this direction @brian-brazil, I'm going to try aligning the version of the dependencies to the one actually used by the particular version of JBoss in use here and report back here in case someone else ever needs to do this.
