### ISSUE TITLE
 Without rebuilding Jboss application (image) 

### ISSUE THREAD

**Issue by prasenforu** [prometheus/jmx_exporter#169]
I want use this for kubernetes platform.

My Jboss application running in kubernetes environment.

Can you guide me how I can use this without rebuilding Jboss application (docker image)

Basically want to run this as a separate container and collect metrics from JBoss application server (docker container/pod).

**Comment by brian-brazil** [comment]
It's recommended to use this exporter as a java agent, as that's the easiest to work with and produces the best metrics.
