### ISSUE TITLE
Java agent preventing startup

### ISSUE THREAD

**Issue by tpbowden** [prometheus/jmx_exporter#170]
After upgrading from jmx_exporter 0.8 to 0.10, the java agent is now blocking Cassandra (3.0) from starting up. The metrics endpoint is serving metrics properly, but there is nothing related to cassandra in there as it has not yet started and is not accepting connections.

**Comment by lesterwang** [comment]
I have the same problem, when I upgrade the jmx_exporter from 0.9 to 0.10, the cassandra can't startup, but the jmx_exporter can start to work, I can retrive the jmx_* metrics. 
The result of `sudo service cassandra status` is `could not access pidfile for Cassandra
`
And then kill the cassandra thread by `pgrep -f cassandra | sudo kill -9`, the cassandra start to running.
The cassandra version is 2.1.13

**Comment by brian-brazil** [comment]
It sounds like there's something more going on there. Are you sure the old cassandra is dead?

**Comment by lesterwang** [comment]
yes, I stop the cassandra first and check there is no cassandra thread any more, then update the cassandra-env.sh, update the JVM_OPTS, upgrade the version from 0.9 to 0.10, then I can't start the cassandra, but there is a cassandra thread, after I kill it, the cassandra works well

**Comment by brian-brazil** [comment]
What exactly do you mean by threads? Unix uses processes.

**Comment by lesterwang** [comment]
When I start the cassandra after upgrade the version, the process is:
`cassand+ 13695  3.5  0.8 9774828 131368 ?      Sl   15:07   0:00 java -cp /etc/cassandra:/usr/share/cassandra/lib/ST4-4.0.8.jar:/usr/share/cassandra/lib/airline-0.6.jar:/usr/share/cassandra/lib/antlr-runtime-3.5.2.jar:/usr/share/cassandra/lib/commons-cli-1.1.jar:/usr/share/cassandra/lib/commons-codec-1.2.jar:/usr/share/cassandra/lib/commons-lang3-3.1.jar:/usr/share/cassandra/lib/commons-math3-3.2.jar:/usr/share/cassandra/lib/compress-lzf-0.8.4.jar:/usr/share/cassandra/lib/concurrentlinkedhashmap-lru-1.4.jar:/usr/share/cassandra/lib/disruptor-3.0.1.jar:/usr/share/cassandra/lib/guava-16.0.jar:/usr/share/cassandra/lib/high-scale-lib-1.0.6.jar:/usr/share/cassandra/lib/jackson-core-asl-1.9.2.jar:/usr/share/cassandra/lib/jackson-mapper-asl-1.9.2.jar:/usr/share/cassandra/lib/jamm-0.3.0.jar:/usr/share/cassandra/lib/javax.inject.jar:/usr/share/cassandra/lib/jbcrypt-0.3m.jar:/usr/share/cassandra/lib/jline-1.0.jar:/usr/share/cassandra/lib/jna-4.0.0.jar:/usr/share/cassandra/lib/json-simple-1.1.jar:/usr/share/cassandra/lib/libthrift-0.9.2.jar:/usr/share/cassandra/lib/logback-classic-1.1.2.jar:/usr/share/cassandra/lib/logback-core-1.1.2.jar:/usr/share/cassandra/lib/lz4-1.2.0.jar:/usr/share/cassandra/lib/metrics-core-2.2.0.jar:/usr/share/cassandra/lib/netty-all-4.0.23.Final.jar:/usr/share/cassandra/lib/reporter-config-2.1.0.jar:/usr/share/cassandra/lib/slf4j-api-1.7.2.jar:/usr/share/cassandra/lib/snakeyaml-1.11.jar:/usr/share/cassandra/lib/snappy-java-1.0.5.2.jar:/usr/share/cassandra/lib/stream-2.5.2.jar:/usr/share/cassandra/lib/super-csv-2.1.0.jar:/usr/share/cassandra/lib/thrift-server-0.3.7.jar:/usr/share/cassandra/apache-cassandra-2.1.13.jar:/usr/share/cassandra/apache-cassandra-thrift-2.1.13.jar:/usr/share/cassandra/apache-cassandra.jar:/usr/share/cassandra/cassandra-driver-core-2.0.9.2.jar:/usr/share/cassandra/netty-3.9.0.Final.jar:/usr/share/cassandra/stress.jar: -ea -javaagent:/usr/share/cassandra/lib/jamm-0.3.0.jar -XX:+CMSClassUnloadingEnabled -XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=42 -Xms7645M -Xmx7645M -XX:+HeapDumpOnOutOfMemoryError -Xss256k -XX:StringTableSize=1000003 -XX:+UseG1GC -XX:G1RSetUpdatingPauseTimePercent=5 -XX:MaxGCPauseMillis=500 -Dfile.encoding=UTF8 -XX:+UseTLAB -XX:CompileCommandFile=/etc/cassandra/hotspot_compiler -XX:+CMSParallelInitialMarkEnabled -XX:+CMSEdenChunksRecordAlways -XX:CMSWaitDuration=10000 -XX:+UseCondCardMark -Djava.net.preferIPv4Stack=true -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.password.file=/etc/cassandra/jmxremote.password -javaagent:/home/ubuntu/jmx_exporter/jmx_prometheus_javaagent-0.10.jar=7070:/home/ubuntu/jmx_exporter/cassandra.yml
`

but after I kill the cassandra thread, the process becomes:

`cassand+ 13776  153 53.3 10115784 8353872 ?    SLl  15:08   0:27 java -ea -javaagent:/usr/share/cassandra/lib/jamm-0.3.0.jar -XX:+CMSClassUnloadingEnabled -XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=42 -Xms7645M -Xmx7645M -XX:+HeapDumpOnOutOfMemoryError -Xss256k -XX:StringTableSize=1000003 -XX:+UseG1GC -XX:G1RSetUpdatingPauseTimePercent=5 -XX:MaxGCPauseMillis=500 -Dfile.encoding=UTF8 -XX:+UseTLAB -XX:CompileCommandFile=/etc/cassandra/hotspot_compiler -XX:+CMSParallelInitialMarkEnabled -XX:+CMSEdenChunksRecordAlways -XX:CMSWaitDuration=10000 -XX:+UseCondCardMark -Djava.net.preferIPv4Stack=true -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.password.file=/etc/cassandra/jmxremote.password -javaagent:/home/ubuntu/jmx_exporter/jmx_prometheus_javaagent-0.10.jar=7070:/home/ubuntu/jmx_exporter/cassandra.yml -Dlogback.configurationFile=logback.xml -Dcassandra.logdir=/var/log/cassandra -Dcassandra.storagedir= -Dcassandra-pidfile=/var/run/cassandra/cassandra.pid -cp /etc/cassandra:/usr/share/cassandra/lib/ST4-4.0.8.jar:/usr/share/cassandra/lib/airline-0.6.jar:/usr/share/cassandra/lib/antlr-runtime-3.5.2.jar:/usr/share/cassandra/lib/commons-cli-1.1.jar:/usr/share/cassandra/lib/commons-codec-1.2.jar:/usr/share/cassandra/lib/commons-lang3-3.1.jar:/usr/share/cassandra/lib/commons-math3-3.2.jar:/usr/share/cassandra/lib/compress-lzf-0.8.4.jar:/usr/share/cassandra/lib/concurrentlinkedhashmap-lru-1.4.jar:/usr/share/cassandra/lib/disruptor-3.0.1.jar:/usr/share/cassandra/lib/guava-16.0.jar:/usr/share/cassandra/lib/high-scale-lib-1.0.6.jar:/usr/share/cassandra/lib/jackson-core-asl-1.9.2.jar:/usr/share/cassandra/lib/jackson-mapper-asl-1.9.2.jar:/usr/share/cassandra/lib/jamm-0.3.0.jar:/usr/share/cassandra/lib/javax.inject.jar:/usr/share/cassandra/lib/jbcrypt-0.3m.jar:/usr/share/cassandra/lib/jline-1.0.jar:/usr/share/cassandra/lib/jna-4.0.0.jar:/usr/share/cassandra/lib/json-simple-1.1.jar:/usr/share/cassandra/lib/libthrift-0.9.2.jar:/usr/share/cassandra/lib/logback-classic-1.1.2.jar:/usr/share/cassandra/lib/logback-core-1.1.2.jar:/usr/share/cassandra/lib/lz4-1.2.0.jar:/usr/share/cassandra/lib/metrics-core-2.2.0.jar:/usr/share/cassandra/lib/netty-all-4.0.23.Final.jar:/usr/share/cassandra/lib/reporter-config-2.1.0.jar:/usr/share/cassandra/lib/slf4j-api-1.7.2.jar:/usr/share/cassandra/lib/snakeyaml-1.11.jar:/usr/share/cassandra/lib/snappy-java-1.0.5.2.jar:/usr/share/cassandra/lib/stream-2.5.2.jar:/usr/share/cassandra/lib/super-csv-2.1.0.jar:/usr/share/cassandra/lib/thrift-server-0.3.7.jar:/usr/share/cassandra/apache-cassandra-2.1.13.jar:/usr/share/cassandra/apache-cassandra-thrift-2.1.13.jar:/usr/share/cassandra/apache-cassandra.jar:/usr/share/cassandra/cassandra-driver-core-2.0.9.2.jar:/usr/share/cassandra/netty-3.9.0.Final.jar:/usr/share/cassandra/stress.jar: -XX:HeapDumpPath=/home/cassandra/java_1502118433.hprof -XX:ErrorFile=/home/cassandra/hs_err_1502118433.log org.apache.cassandra.service.CassandraDaemon
`
you can see the jmx_prometheus_javaagent position changed, I am not sure is it related with the problem

**Comment by lesterwang** [comment]
sorry I mis use the thread and process

**Comment by brian-brazil** [comment]
The first of those is lacking a class to run.

**Comment by lesterwang** [comment]
Between the first one and second one, I run `sudo kill -9 13695` , but the kill operation make the cassandra load the `-Dlogback.configurationFile=logback.xml -Dcassandra.logdir=/var/log/cassandra -Dcassandra.storagedir= -Dcassandra-pidfile=/var/run/cassandra/cassandra.pid` and `-XX:HeapDumpPath=/home/cassandra/java_1502118433.hprof -XX:ErrorFile=/home/cassandra/hs_err_1502118433.log org.apache.cassandra.service.CassandraDaemon` correctly. I tried several time, the result is same. Seems jmx_exporter 0.10.0 cause some problem to the class loading

**Comment by brian-brazil** [comment]
There's something more going on here. Why is it trying to run C* twice?

**Comment by lesterwang** [comment]
The service `stop` and `restart` not work after I start it, so I try to kill the process to recover with jmx exporter 0.9, but kill the process make the cassandra work well.

**Comment by starplanet** [comment]
I have the trouble two. jmx export 0.10.0 can work with cassandra 3.10, but when I use the same configuration with cassandra 3.0.8, it will prevent casandra start up.

**Comment by tiago-loureiro** [comment]
I have managed to isolate the issue, which gets surfaced by any cassandra version earlier than 3.10. The reason why 3.10 and above work is that the check for open JMX port has been removed https://github.com/apache/cassandra/commit/c7ad00e3ea13e326f7472996cf682b7b81087dea

Thus, once cassandra is started, it hangs when running something like:
```
java -javaagent:jmx_prometheus_javaagent/target/jmx_prometheus_javaagent-0.10-SNAPSHOT.jar=8081:/prometheus-jmx.yml
```
and never manages to make progress.

This was introduced when the exporter started to make use of [simple HTTP server](https://github.com/prometheus/jmx_exporter/commit/5b180affbefa445088d4608b9640ca404ce91ae2) instead of jetty. If you run the command above, you will see that the command will never exit and you can even issue requests to port 8081 meaning that the server is still running.

**Comment by brian-brazil** [comment]
The httpserver being a non-daemon thread is likely the issue.

**Comment by VinceMD** [comment]
I'm observing the same issue with Cassandra 2.1.18 and Kubernetes. It just hangs and Cassandra never starts

**Comment by vrischmann** [comment]
Just updated the jmx exporter and have the same problem. Here's an ugly patch to make it work.

    diff --git a/jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java b/jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java
    index d97024a..4b07457 100644
    --- a/jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java
    +++ b/jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java
    @@ -1,6 +1,7 @@
     package io.prometheus.jmx;

     import java.io.File;
    +import java.io.IOException;
     import java.lang.instrument.Instrumentation;
     import java.net.InetSocketAddress;

    @@ -21,7 +22,7 @@ public class JavaAgent {

          int port;
          String file;
    -     InetSocketAddress socket;
    +     final InetSocketAddress socket;

          if (args.length == 3) {
            port = Integer.parseInt(args[1]);
    @@ -35,6 +36,19 @@ public class JavaAgent {

          new JmxCollector(new File(file)).register();
          DefaultExports.initialize();
    -     server = new HTTPServer(socket, CollectorRegistry.defaultRegistry);
    +
    +     Thread thread = new Thread(new Runnable() {
    +       @Override
    +       public void run() {
    +         try {
    +           server = new HTTPServer(socket, CollectorRegistry.defaultRegistry);
    +         } catch ( IOException e ) {
    +           e.printStackTrace();
    +         }
    +       }
    +     });
    +     thread.setDaemon(true);
    +     thread.start();
    +     thread.join();
        }
     }

seems to work here

**Comment by elecnix** [comment]
For reference, daemon threads in Jetty was introduced in #15.

**Comment by brian-brazil** [comment]
What we probably need here is an option to control whether the httpserver is a daemon thread over in client_java, and then use that here.

**Comment by ilucker** [comment]
@brian-brazil  i've submitted a [pull request](https://github.com/prometheus/client_java/pull/300) to client_java. 
Do you want me to create one for jmx_exporter?

**Comment by gpaggi** [comment]
@ilucker I took the freedom to do so, since it was blocking my setup of Cassandra monitoring.
@brian-brazil can you please merge the PR if you are happy with it?

**Comment by ajayjnv02** [comment]
I am getting below error while running cassandra daemon in jboss server. Can any body help

10:14:17,091 INFO  [org.wildfly.naming] (MSC service thread 1-1) WildFly Naming version 1.0.9.Final
10:14:17,112 INFO  [stdout] (MSC service thread 1-1) Exception (java.lang.RuntimeException) encountered during startup: Cannot bind to URL [rmi://localhost:50497/jmxrmi]: javax.naming.NoPermissionException: WFNAM00006: Cannot modify read-only naming context
10:14:17,113 ERROR [stderr] (MSC service thread 1-1) java.lang.RuntimeException: Cannot bind to URL [rmi://localhost:50497/jmxrmi]: javax.naming.NoPermissionException: WFNAM00006: Cannot modify read-only naming context
10:14:17,113 ERROR [stderr] (MSC service thread 1-1)    at org.apache.cassandra.service.CassandraDaemon.exitOrFail(CassandraDaemon.java:651)
10:14:17,114 ERROR [stderr] (MSC service thread 1-1)    at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:126)
10:14:17,114 ERROR [stderr] (MSC service thread 1-1)    at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:188)
10:14:17,114 ERROR [stderr] (MSC service thread 1-1)    at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:533)
10:14:17,114 ERROR [stderr] (MSC service thread 1-1)    at com.ericsson.bss.cil.unittest.utils.embedded.cassandra.CassandraDaemonForTest.getInstance(CassandraDaemonForTest.java:162)

**Comment by rgadekarla** [comment]
I am running to same issue where the JMX Exporter is blocking the Tomcat server from coming up. Here the JMXExporter is not running in the javaagent mode but in remote mode. If JMX exporter is killed, the Tomcat boots up well and starts serving requests. So temporary resolution seems to be
- Stop JMX exporter
- Start Tomcat
- Wait for Tomcat to boot up properly and make sure all end points are serving requests
- Start JMX exporter

This resolved the issue
