### ISSUE TITLE
Metrics endpoint is slow

### ISSUE THREAD

**Issue by jayme-github** [prometheus/jmx_exporter#175]
I've added jmx_exporter to a WildFly 10 setup and notices that the `/metrics` endpoint is pretty slow (in relation to various other endpoints from applications and exporters). For me `/metrics` returns data in around 7-10 seconds (without any user load on the server) and would occasionally exceed the prometheus default scrape timeout of 10 seconds.

If this is normal (I'm new to all this Java/JMX/WildFly stuff) a short note in the readme would be cool (at least for people like me :smiley: ).

**Comment by brian-brazil** [comment]
This is normal, JMX is not particularly efficient.

**Comment by finkr** [comment]
As mentioned by Brian Brazil: _JMX is not particularly efficient_.

Using `whitelistObjectNames`, It is often possible to dramatically **speed-up things** (dropped from 15 seconds to 0.9s. in my use case).
See ->  https://github.com/prometheus/jmx_exporter/pull/284
