### ISSUE TITLE
Adding several jmx_exporters leads to multiple `jmx_scrape_duration_seconds` in output

### ISSUE THREAD

**Issue by olvesh** [prometheus/jmx_exporter#176]
We have several yaml files to configure the Collectors, and add several (two) in one JVM.
Each adds the `jmx_scrape_duration_seconds` and when JVM start it fails on startup complaining of duplicate metrics.

One solution is to bundle the files into one file, but it would be nice to keep the modularity of the configs.

**Comment by brian-brazil** [comment]
It's expected that you only have one agent per jvm, and thus you should only have one config. It's more efficient too.

**Comment by olvesh** [comment]
I was a bit unclear. We have one agent, and two collectors.

**Comment by brian-brazil** [comment]
That's not a stock jmx exporter. Only one collector is supported per JVM.

**Comment by olvesh** [comment]
Ok. Didn't see that anywhere but guess it makes sense. An alternative could have been to add a label on collector creation. 
We merged files and it is working.
