### ISSUE TITLE
Multiple target instances not supported for now

### ISSUE THREAD

**Issue by WillCup** [prometheus/jmx_exporter#181]
Just to support.

[here is the patch pull request](https://github.com/prometheus/jmx_exporter/pull/180)

and patch file
[support_multiple_jmx_instance.patch](https://github.com/prometheus/jmx_exporter/files/1251527/support_multiple_jmx_instance.txt)

**Comment by i4yyds** [comment]
请问您提供的这个代码，是可以让jmx_exporter支持同时采集多个jmx端口（实例）吗？

**Comment by dhoard** [comment]
@i4yyds 不。每个 Java 进程需要使用一个导出器。最好使用 Java 代理版本。(No. You need to use one exporter per Java process. Preferably using the Java agent version.)

**Comment by i4yyds** [comment]
@dhoard 但是我看到您的代码support_multiple_jmx_instance.patch，不是可以支持多个jmx实例吗？我想使用jmx-exporter获取java的jvm数据，目前来看jmx_exporter是Java应用端改动最小的方案(只需要在java启动命令中添加参数即可，其他的如spring actuator改动都比较大)。请问您知道有没有其他的让jmx-exporter同时连接多个jmx实例的方法呢？

**Comment by dhoard** [comment]
@i4yyds 虽然此问题附加了补丁，但未集成。 将一个 JMX Exporter 用于多个应用程序的用例不是我们想要支持的模式。
