### ISSUE TITLE
Missing Default Port Assignment

### ISSUE THREAD

**Issue by jcantu-usgs** [prometheus/jmx_exporter#197]
Hi,

Can you folks suggest a default port assignment for jmx_prometheus_javaagent?

I couldn't find one in this list:
https://github.com/prometheus/prometheus/wiki/Default-port-allocations

Thanks,
Jonathan

**Comment by brian-brazil** [comment]
There isn't one, as you'd technically need one per thing that it's an agent for. Follow whatever your local port numbering convention is.
