### ISSUE TITLE
hadoop mapreduce jmx is a riddle wrapped in an enigma

### ISSUE THREAD

**Issue by typingduck** [prometheus/jmx_exporter#2]
For hadoop jobtracker/tasktracker a lot of the useful metrics are exposed as JSON contained in the jmx output. See e.g. 'SummaryJson'.

This is perhaps outside the scope of a jmx_for_prometheus but we need a way of getting this hadoop info into prometheus. Perhaps another scaper that just converts the http://.../jmx  JSON endpoints into prometheus suitable format will be needed.

**Comment by brian-brazil** [comment]
That sounds like a case for a separate scraper unfortunately.

**Comment by brian-brazil** [comment]
Looking at this more recently, that's just one way that Hadoop exposes JMX stats. The usual ways also work, so I don't think there's anything to be done here.
