### ISSUE TITLE
secure the endpoint?

### ISSUE THREAD

**Issue by jmazzitelli** [prometheus/jmx_exporter#201]
What are the odds of a PR being accepted that secures the metrics endpoint of jmx_exporter (so it, say, supports https and basic auth as an example)?

**Comment by brian-brazil** [comment]
In line with the rest of the Prometheus ecosystem, this is left to tools like nginx/apache to handle.

**Comment by xakassi** [comment]
Hi, guys!
Do we have any chance that things have changed and you can accept a PR for securing /metrics endpoint with basic auth? Nginix is not convenient for us in Kuberenetes environment.
