### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by binglind** [prometheus/jmx_exporter#210]
ERROR io.fabric8.agent.shaded.jmx_exporter.io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector [JmxCollector.java:406] JMX scrape failed: java.lang.NullPointerException
	at io.fabric8.agent.shaded.jmx_exporter.io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.processBeanValue(JmxScraper.java:254)

  it seems like  "l2s.put(idx, composite.get(idx).toString());" has problem

**Comment by niuhf0452** [comment]
I have the same problem. I make PR #208 .

**Comment by brian-brazil** [comment]
This was just fixed.
