### ISSUE TITLE
split on : messes up windows paths

### ISSUE THREAD

**Issue by blackandcold** [prometheus/jmx_exporter#212]
https://github.com/prometheus/jmx_exporter/blob/7d6eae860e70ee645257e232dc70e5de8c729171/jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java#L16

maybe change it to ';'?

Simple example of problem: ".jar=1234:C:\config.yaml" => 1234 will be interpreted as host, C as Int port *exception*.
Since this is an argument, quotes don't help.

A simple work around is to drop the lib and logger .jar into working directory and reference them with ./

Edit:  logger .jar is needed for JBoss and has nothing to do with the problem itself :)

**Comment by brian-brazil** [comment]
Hmm, we've been doing it this way for some time. Let's see if the workaround is sufficient before breaking everyone.

**Comment by blackandcold** [comment]
For development the workaround is fine. For production only if the host is non Windows based.
Seems like no one was using the exporter on a Windows machine or always used relative paths :)

Java classpath has also OS dependent seperator: https://en.wikipedia.org/wiki/Classpath_%28Java%29#OS_specific_notes 

I'll close this issue for now. If needed I'll do a pull request.
