### ISSUE TITLE
kafka_server_fetcherlagmetrics_consumerlag always 0.0

### ISSUE THREAD

**Issue by jianchen2580** [prometheus/jmx_exporter#216]
Kafka version: 0.10.0.1
I'm Using [example config](https://raw.githubusercontent.com/prometheus/jmx_exporter/master/example_configs/kafka-0-8-2.yml)
Other metrics is working as excepted, but "kafka_server_fetcherlagmetrics_consumerlag" always 0.0:
`kafka_server_fetcherlagmetrics_consumerlag{clientId="ReplicaFetcherThread-0-1010179",partition="12",topic="xxxx",} 0.0`

**Comment by brian-brazil** [comment]
The JMX exporter just exposes what JMX does, you'll have to take this up with Kafka.
