### ISSUE TITLE
Version number confusion

### ISSUE THREAD

**Issue by DemonTPx** [prometheus/jmx_exporter#220]
Hi,

I am a bit confused about the versioning of the exporter. I thought that `0.10` was the latest version, but later found out that it is `0.1.0`.

To me it appears that `0.10` is newer than `0.1.0` and the next (major) version should be either `1.0`, `1.0.0` or `0.11`. My suggestion would be to use one of these version numbers for the next release. (See also: https://semver.org/)

I found this out after having some connections problems with cassandra which were supposedly fixed in `0.1.0` (see #170), but I thought for a long time I was already running the latest version with the fix.

**Comment by brian-brazil** [comment]
0.1.0 is the latest version, that was this package switching to semver.

**Comment by DemonTPx** [comment]
Yeah, but that took me a while to find out. My point is that I could have found out a lot sooner if either the version was different (`1.0`, `0.11` or whatever) or maybe if a note on the front of the github page would have told me that `0.1.0` was the latest version.

Also, if (in the future) you were to version a package with `0.3.0`, it would be very confusing, since `0.3` is also available here: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/

So my suggestion is to use a version number above `0.10` to prevent all this confusion from happening now and in the future.

**Comment by brian-brazil** [comment]
It's linked from the readme, used in an example in the readme, it's the most recent release on github and the release announcement included the change in versioning scheme.

**Comment by pantaoran** [comment]
I know this is an old issue, and at that date two years ago this probably made more sense.
But now, I don't understand what's going on with the versioning at all.
You say you switched from one versioning scheme to another in 2017. Then why do we now have the latest version from 2019 again as 0.11.0? Why not 0.4 or 0.3.2?
Looking at the list of github releases now just makes no sense.
