### ISSUE TITLE
Using jmx_exporter with a security manager

### ISSUE THREAD

**Issue by gehel** [prometheus/jmx_exporter#223]
I'm using jmx_exporter to collect metrics on elasticsearch. Since elasticsearch installs a fairly strict security manager, additional configuration is required to make things work. I had to create a custom java.policy file (in my case in `/home/elasticsearch/.java.policy`) with the following rules:

    grant codeBase "file:/usr/share/java/prometheus/-" {
      permission javax.management.MBeanServerPermission "createMBeanServer";
      permission javax.management.MBeanPermission "*", "*";
      permission java.lang.RuntimePermission "accessClassInPackage.sun.management";
      permission java.io.FilePermission "/etc/elasticsearch/prometheus_jmx_exporter.yaml", "read";
      permission java.io.FilePermission "/proc/self/status", "read";
    };

I'm opening this issue just so that someone else having the same issue will loose less time than me to make things work :) . Unless you want to add documentation in some more specific place, this issue can probably be closed as-is.

**Comment by brian-brazil** [comment]
Usually I'd say to put it in as a comment our example ES configuration but a) noone has contributed one of 
those and b) I thought ES removed all of their mBeans, and thus you need a specific ES exporter.

**Comment by gehel** [comment]
Yes, elasticsearch has removed all their MBeans. We still want to use jmx_exporter to get JVM level metrics, so that those metrics are consistent across our different applications.

**Comment by brian-brazil** [comment]
I had thought that the elastic search exporters were following the naming/labels that the client library exposes for the jvm stats. Is that not the case?

**Comment by gehel** [comment]
I have to admit that I did not even check... my bad. I'll dig into this tomorrow and report my findings...

**Comment by brian-brazil** [comment]
Closing due to staleness.
