### ISSUE TITLE
Using jmx_exporter with JMXMP 

### ISSUE THREAD

**Issue by sergeyarl** [prometheus/jmx_exporter#226]
Hi! 

We're trying to switch from RMI to JMXMP , but in case of using JMXMP jmx_exporter doen't seem to be fully working.

So I'm wondering if jmx_exporter supports JMXMP ?

Thank you! 

Regards,
Sergey

**Comment by brian-brazil** [comment]
We support JMX, so if the underlying libraries support that so do we. Using the jmx exporter as a java agent is recommended.

**Comment by sergeyarl** [comment]
I managed to connect using JMXMP and jmx exporter after specifying needed library via `-sp`

Thank you! 

Regards,
Sergey
