### ISSUE TITLE
jmx_prometheus_httpserver debian package shouldn't depend on java-runtime

### ISSUE THREAD

**Issue by arush-sal** [prometheus/jmx_exporter#228]
The mentioned `jmx_prometheus_httpserver` debian package should check for either `$JAVA_HOME` or `java` binary in the `$PATH` variable instead of being dependent on the virtual `java-runtime` package.

**Comment by brian-brazil** [comment]
I think you're getting confused with RPMs. With Debian packaging you specify dependencies on packages.

**Comment by arush-sal** [comment]
I was referring to line no.6 in the deb package's control file:
[Depends: java-runtime](https://github.com/prometheus/jmx_exporter/blob/95b28bb12ad8e3f754903ec6a033988c8e573725/jmx_prometheus_httpserver/src/deb/control/control#L6)
Instead of having the dependency on the virtual `java-runtime` package it rather should check for a JRE/JDK on the machine. As in case if the machine has `Oracle Java` extracted directly from a tar archive it won't have the required package but still, the machine could have easily run the jar. Because of the dependency, the user will now have to install the specified package which could possibly lead to a runtime conflict or an issue with their application.

**Comment by brian-brazil** [comment]
If you bypass Debian packaging by installing things by hand, isn't not unexpected that things will break. In this case you want the `equivs` package.

**Comment by Learnfr** [comment]
you have to remove the line "Depends: java-runtime" from ./jmx_prometheus_httpserver/src/deb/control/control and then run mvn package to rebuild a new package
I have the same issue because I use openjdk and not oracle jvm
