### ISSUE TITLE
Update the maven repository and README.md with v0.2.1

### ISSUE THREAD

**Issue by arush-sal** [prometheus/jmx_exporter#229]
The maven repository and the README.md file should be updated to v0.2.1 as that is the latest build version.

**Comment by brian-brazil** [comment]
Would you like to send a PR?

**Comment by arush-sal** [comment]
Sorry, but the javaagent release in the official repo at [repo1.maven.org](https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.2.0/jmx_prometheus_javaagent-0.2.0.jar) will need to be updated first. But I guess since it's a minor version release it can be skipped.

**Comment by brian-brazil** [comment]
There is no 0.2.1 yet.

**Comment by arush-sal** [comment]
Well, sorry about that it seems that I got confused by:
[`<version>0.2.1-SNAPSHOT</version>`](https://github.com/prometheus/jmx_exporter/blob/95b28bb12ad8e3f754903ec6a033988c8e573725/pom.xml#L7)

Apologizes for that again.
