### ISSUE TITLE
Release on Maven central

### ISSUE THREAD

**Issue by rhuss** [prometheus/jmx_exporter#24]
'would be cool if releases were available on Maven central so that the agent could be downloaded from there. Even a snapshot release would help.

**Comment by brian-brazil** [comment]
I plan on doing this, though I'm not sure when I'll get to it.

**Comment by rhuss** [comment]
Thanks ;-) 

If I can help, let me know (however, it's more an administrative thing, to get accounts @ sonatype, GPG signing the artefact with your key etc.). See the [sonatype guide](http://central.sonatype.org/pages/ossrh-guide.html) for more info.

**Comment by brian-brazil** [comment]
I've already got client_java setup, it's mostly a matter of banging my head against it for several hours I expect.

**Comment by jitpack-io** [comment]
Hi!
In the mean time this might help https://jitpack.io/#prometheus/jmx_exporter/e55aa0e1ff

**Comment by brian-brazil** [comment]
Well, I was right when I said several hours.

The agent is now avilable at http://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.3/jmx_prometheus_javaagent-0.3.jar
