### ISSUE TITLE
Allow dots in names and label (sanitize)

### ISSUE THREAD

**Issue by mthoretton** [prometheus/jmx_exporter#256]
Hello!

Would it be possible to add "." (dot) as to the list of "allowed" characters in names and labels? (or have the possibility to add chars in the config)
We want to use jmx_exporter and consume the endpoint both from k8s and datadog. As Datadog use dots as separator, it would be super nice to have dots instead of underscores in order to filter metrics by prefix: `kafka.network.*` for instance.

Thanks!

**Comment by brian-brazil** [comment]
No, this is not permitted by the Prometheus data model.

**Comment by mthoretton** [comment]
👍 It makes a lot of sense to not allow it then. We'll process that in the custom datadog check we use then, thanks for the quick answer!
