### ISSUE TITLE
Grafana not able to Pull Prometheus JVM exporter data

### ISSUE THREAD

**Issue by haripatn** [prometheus/jmx_exporter#261]
Hi All,
Please help me here:
Scenario: Websphere Application server, I have used below JVM options and restarted
 -javaagent:/apps/prometheus/jmx_prometheus_javaagent-0.2.0.jar=8082:/apps/prometheus/configME.yaml

**cat /apps/prometheus/configME.yaml**
_startDelaySeconds: 0
#hostPort: 127.0.0.1:1099
jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:1099/jmxrmi
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames: ["org.apache.cassandra.metrics:*"]
blacklistObjectNames: ["org.apache.cassandra.metrics:type=ColumnFamily,*"]
rules:
  - pattern: 'org.apache.cassandra.metrics<type=(\w+), name=(\w+)><>Value: (\d+)'
    name: cassandra_$1_$2
    value: $3
    valueFactor: 0.001
    labels: {}
    help: "Cassandra metric $1 $2"
    type: GAUGE
    attrNameSnakeCase: false_

I am able to see the metrics in prometheus in below format, but In Grafana i can not create a single graph/dashboard and getting error "a.data.data is undefined", Does grafana expect a different format than what prometheus is generating? Ex query on graphana: rate(jvm_gc_collection_seconds_sum{gc="MarkSweepCompact",instance="aial2393.belldev.dev.bce.ca:8082",job="jvmmonitor"}[5m]))

Below is the truncated data which i get from Prometheus Metrics:

 HELP jvm_memory_bytes_used Used bytes of a given JVM memory area.
 TYPE jvm_memory_bytes_used gauge
jvm_memory_bytes_used{area="heap",} 7.917568384E9
jvm_memory_bytes_used{area="nonheap",} 4.97619728E8
 HELP jvm_memory_bytes_committed Committed (bytes) of a given JVM memory area.
 TYPE jvm_memory_bytes_committed gauge
jvm_memory_bytes_committed{area="heap",} 1.073741824E10
jvm_memory_bytes_committed{area="nonheap",} 6.92037304E8
 HELP jvm_memory_bytes_max Max (bytes) of a given JVM memory area.
 TYPE jvm_memory_bytes_max gauge
jvm_memory_bytes_max{area="heap",} 1.073741824E10
jvm_memory_bytes_max{area="nonheap",} -1.0
 HELP jvm_memory_pool_bytes_used Used bytes of a given JVM memory pool.
 TYPE jvm_memory_pool_bytes_used gauge
jvm_memory_pool_bytes_used{pool="class storage",} 2.93938188E8
jvm_memory_pool_bytes_used{pool="JIT code cache",} 1.34217728E8
jvm_memory_pool_bytes_used{pool="JIT data cache",} 6.6759968E7
jvm_memory_pool_bytes_used{pool="miscellaneous non-heap storage",} 7994380.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by haripatn** [comment]
I resolved it myself anyways thanks

**Comment by Xat59** [comment]
@haripatn how did you solve it by yourself ? can you please share your feedback ? thank a lot !
