### ISSUE TITLE
Scrape error on a dynamic JMX source

### ISSUE THREAD

**Issue by gfliker** [prometheus/jmx_exporter#27]
While monitoring a busy ActiveMQ instance were getting scrape errors.

In the logs we see this:

SEVERE: JMX scrape failed: javax.management.InstanceNotFoundException: org.apache.activemq:BrokerName=amq,Type=Connection,ConnectorName=openwire,Connection=ID_

The mbean represents connections to the activemq broker and each connection is getting an ID_*.

We tried adding a pattern to filter only for the desired mbeans but still the error persists.

Connection to the ActiveMQ broker are ever changing and i'm guessing that's the root of the problem. 

Also since were getting the same error with a pattern or without im guessing the workflow is to load all mbeans and their values (takes a few seconds)  and only then apply the pattern.
If that's the case it is very optimistic for our use case.

Many thanks.

Gil Fliker

**Comment by brian-brazil** [comment]
Can you get me a stack trace from https://github.com/prometheus/jmx_exporter/tree/exceptions ? Nikita should already have a build of it and knows how to get the logs.

**Comment by gfliker** [comment]
Sent you an email with the stack trace

**Comment by brian-brazil** [comment]
Thanks for that, issue is a javax.management.InstanceNotFoundException from the getMBeanInfo.

**Comment by brian-brazil** [comment]
I've merged in a change to master that should fix this, can you confirm it's working now?

**Comment by gfliker** [comment]
Great this is working now many thx !.

It take 23 seconds for the scrape which is something we need to resolve somehow.

Regarding my other question when the filter is applied, before loading all metrics or after can you share the logic ?

The way were monitoring ActiveMQ today is with collected to which we provide the list of mbeans we want  and it takes much less time.

Again thx

**Comment by brian-brazil** [comment]
Great.

The filter is applied after the scrape. #23 covers how to approach that if you want to chime in there.

**Comment by muzili1** [comment]
Can you send me a yaml file about activemq ？
@gfliker      Thanks.
