### ISSUE TITLE
Kafka Connect metrics not listed, only standard system metrics

### ISSUE THREAD

**Issue by famuyiwad** [prometheus/jmx_exporter#274]
Hi,

We have configured our kafka connect instance to export JMX via this javaagent as follows
`export JMX_PORT=1234
export KAFKA_JMX_OPTS="-Djava.util.logging.config.file=/prometheus-config/prometheus-logging.properties -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1234 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=5678 -javaagent:/tmp/jmx_prometheus_javaagent-0.9.jar=8901:/prometheus-config/prometheus-config.yml`

With the debugging enabled as seen above, we can see that the kafka connect metrics are being parsed and processed as defined in the config YAML file

`May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-rebalance-metrics'_'rebalance-max-time-ms': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-rebalance-metrics}rebalance-max-time-ms': -Infinity
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-rebalance-metrics'_'time-since-last-rebalance-ms': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-rebalance-metrics}time-since-last-rebalance-ms': 596854.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-rebalance-metrics'_'epoch': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-rebalance-metrics}epoch': 6.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-rebalance-metrics'_'leader-name': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-rebalance-metrics}leader-name': http://ip-10-32-123-125.ec2.internal:31877/
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-rebalance-metrics'_'completed-rebalances-total': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-rebalance-metrics}completed-rebalances-total': 2.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-rebalance-metrics'_'rebalance-avg-time-ms': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-rebalance-metrics}rebalance-avg-time-ms': 0.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-rebalance-metrics'_'rebalancing': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-rebalance-metrics}rebalancing': 0.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=app-info'_'commit-id': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=app-info}commit-id': ec61c5e93da662df
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=app-info'_'version': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=app-info}version': 1.0.0-cp1
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=kafka-metrics-count'_'count': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=kafka-metrics-count}count': 78.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-metrics'_'connector-startup-failure-percentage': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-metrics}connector-startup-failure-percentage': 0.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-metrics'_'task-startup-attempts-total': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-metrics}task-startup-attempts-total': 6.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-metrics'_'connector-startup-success-total': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-metrics}connector-startup-success-total': 7.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-metrics'_'connector-startup-failure-total': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-metrics}connector-startup-failure-total': 0.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-metrics'_'task-startup-success-percentage': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-metrics}task-startup-success-percentage': 0.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-metrics'_'connector-startup-attempts-total': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-metrics}connector-startup-attempts-total': 7.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-metrics'_'connector-count': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-metrics}connector-count': 2.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-metrics'_'connector-startup-success-percentage': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-metrics}connector-startup-success-percentage': 0.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-metrics'_'task-startup-success-total': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-metrics}task-startup-success-total': 6.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-metrics'_'task-startup-failure-percentage': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-metrics}task-startup-failure-percentage': 0.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-metrics'_'task-count': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-metrics}task-count': 2.0
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect:type=connect-worker-metrics'_'task-startup-failure-total': process
May 23, 2018 9:34:39 AM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'kafka.connect{type=connect-worker-metrics}task-startup-failure-total': 0.0`

However, we don't know why same metrics are not accessible via the `metrics` endpoint.

Here is the `prometheus-config.yml` file we are using

lowercaseOutputName: true
attrNameSnakeCase: true
whitelistObjectNames:
  - "kafka.connect:type=*"
rules:
  - pattern: 'kafka.(\w+)<type=(.+)><>(Count|Value)'
    name: kafka_$1_$2
  - pattern: kafka.(\w+)<type=(.+), connector=(.+)><>(Count|Value)
    name: kafka_$1_$2
    labels:
      connector: "$3"
  - pattern: kafka.(\w+)<type=(.+), connector=(.+), task=(.*)><>(Count|Value)
    name: kafka_$1_$2
    labels:
      connector: "$3"
      task: "$4"
  - pattern: kafka.(\w+)<type=(.+), client-id=(.+)><>(Count|Value)
    name: kafka_$1_$2
    labels:
      clientId: "$3"
  - pattern: kafka.(\w+)<type=(.+), id=(.+)><>(Count|Value)
    name: kafka_$1_$2
    labels:
      id: "$3"
  - pattern: kafka.(\w+)<type=(.+), client-id=(.+), node-id=(.+)><>(Count|Value)
    name: kafka_$1_$2
    labels:
      clientId: "$3"
      nodeId: "$4"
  - pattern: kafka.(\w+)<type=(.+), client-id=(.+), topic=(.+)><>(Count|Value)
    name: kafka_$1_$2
    labels:
      clientId: "$3"
      topic: "$4"
  - pattern : kafka.(\w+)<type=(.+), name=(.+)><>(Count|Value)
    name: kafka_$1_$2_$3_$4
    type: COUNTER
  - pattern : kafka.(\w+)<type=(.+), name=(.+), (\w+)=(.+)><>(Count|Value)
    name: kafka_$1_$2_$3_$6
    labels:
      "$4": "$5"
 
Here is an excerpt of the exported returned via the metrics endpoint from the http server.

`# HELP jvm_classes_loaded The number of classes that are currently loaded in the JVM
# TYPE jvm_classes_loaded gauge
jvm_classes_loaded 10958.0
# HELP jvm_classes_loaded_total The total number of classes that have been loaded since the JVM has started execution
# TYPE jvm_classes_loaded_total counter
jvm_classes_loaded_total 10958.0
# HELP jvm_classes_unloaded_total The total number of classes that have been unloaded since the JVM has started execution
# TYPE jvm_classes_unloaded_total counter
jvm_classes_unloaded_total 0.0
# HELP jmx_config_reload_success_total Number of times configuration have successfully been reloaded.
# TYPE jmx_config_reload_success_total counter
jmx_config_reload_success_total 0.0
# HELP jvm_threads_current Current thread count of a JVM
# TYPE jvm_threads_current gauge
jvm_threads_current 47.0
# HELP jvm_threads_daemon Daemon thread count of a JVM
# TYPE jvm_threads_daemon gauge
jvm_threads_daemon 23.0
# HELP jvm_threads_peak Peak thread count of a JVM
# TYPE jvm_threads_peak gauge
jvm_threads_peak 51.0
# HELP jvm_threads_started_total Started thread count of a JVM
# TYPE jvm_threads_started_total counter
jvm_threads_started_total 59.0
# HELP jvm_threads_deadlocked Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers
# TYPE jvm_threads_deadlocked gauge
jvm_threads_deadlocked 0.0
# HELP jvm_threads_deadlocked_monitor Cycles of JVM-threads that are in deadlock waiting to acquire object monitors
# TYPE jvm_threads_deadlocked_monitor gauge
jvm_threads_deadlocked_monitor 0.0
# HELP jvm_memory_bytes_used Used bytes of a given JVM memory area.
# TYPE jvm_memory_bytes_used gauge
jvm_memory_bytes_used{area="heap",} 7.375832E7
jvm_memory_bytes_used{area="nonheap",} 8.0906792E7
# HELP jvm_memory_bytes_committed Committed (bytes) of a given JVM memory area.
# TYPE jvm_memory_bytes_committed gauge
jvm_memory_bytes_committed{area="heap",} 2.68435456E8
jvm_memory_bytes_committed{area="nonheap",} 8.2378752E7
# HELP jvm_memory_bytes_max Max (bytes) of a given JVM memory area.
# TYPE jvm_memory_bytes_max gauge
jvm_memory_bytes_max{area="heap",} 2.68435456E8
jvm_memory_bytes_max{area="nonheap",} -1.0
# HELP jvm_memory_pool_bytes_used Used bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_bytes_used gauge
jvm_memory_pool_bytes_used{pool="Code Cache",} 1.7613184E7
jvm_memory_pool_bytes_used{pool="Metaspace",} 5.6107232E7
jvm_memory_pool_bytes_used{pool="Compressed Class Space",} 7186376.0
jvm_memory_pool_bytes_used{pool="G1 Eden Space",} 1.572864E7
jvm_memory_pool_bytes_used{pool="G1 Survivor Space",} 7340032.0
jvm_memory_pool_bytes_used{pool="G1 Old Gen",} 5.0689648E7
# HELP jvm_memory_pool_bytes_committed Committed bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_bytes_committed gauge
jvm_memory_pool_bytes_committed{pool="Code Cache",} 1.7891328E7
jvm_memory_pool_bytes_committed{pool="Metaspace",} 5.701632E7
jvm_memory_pool_bytes_committed{pool="Compressed Class Space",} 7471104.0
jvm_memory_pool_bytes_committed{pool="G1 Eden Space",} 1.61480704E8
jvm_memory_pool_bytes_committed{pool="G1 Survivor Space",} 7340032.0
jvm_memory_pool_bytes_committed{pool="G1 Old Gen",} 9.961472E7
# HELP jvm_memory_pool_bytes_max Max bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_bytes_max gauge
jvm_memory_pool_bytes_max{pool="Code Cache",} 2.5165824E8
jvm_memory_pool_bytes_max{pool="Metaspace",} -1.0
jvm_memory_pool_bytes_max{pool="Compressed Class Space",} 1.073741824E9
jvm_memory_pool_bytes_max{pool="G1 Eden Space",} -1.0
jvm_memory_pool_bytes_max{pool="G1 Survivor Space",} -1.0
jvm_memory_pool_bytes_max{pool="G1 Old Gen",} 2.68435456E8
# HELP jmx_config_reload_failure_total Number of times configuration have failed to be reloaded.
# TYPE jmx_config_reload_failure_total counter
jmx_config_reload_failure_total 0.0
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 63.33
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.527067339935E9
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 471.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 65536.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 8.488361984E9
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 5.44526336E8
# HELP jmx_scrape_duration_seconds Time this JMX scrape took, in seconds.
# TYPE jmx_scrape_duration_seconds gauge
jmx_scrape_duration_seconds 0.012681603
# HELP jmx_scrape_error Non-zero if this scrape failed.
# TYPE jmx_scrape_error gauge
jmx_scrape_error 0.0
# HELP jvm_info JVM version info
# TYPE jvm_info gauge
jvm_info{version="1.8.0_102-b14",vendor="Azul Systems, Inc.",} 1.0
# HELP jvm_gc_collection_seconds Time spent in a given JVM garbage collector in seconds.
# TYPE jvm_gc_collection_seconds summary
jvm_gc_collection_seconds_count{gc="G1 Young Generation",} 142.0
jvm_gc_collection_seconds_sum{gc="G1 Young Generation",} 1.371
jvm_gc_collection_seconds_count{gc="G1 Old Generation",} 0.0
jvm_gc_collection_seconds_sum{gc="G1 Old Generation",} 0.0`
  
Thanks in advance

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by ozbillwang** [comment]
@famuyiwad 

Did you get the problem fix? I got similar issue, and found someone got little deep on this issue.

https://groups.google.com/forum/#!searchin/prometheus-users/jvm_|sort:date/prometheus-users/OtYM7qGMbvA/dZ4vIfWLAgAJ

>I tried different versions and found when version <=0.9 it's OK.

I will try with different versions soon, and report here. 

If this is proved, then it will be a bug, this ticket should be opened.

**Comment by ozbillwang** [comment]
got a statement about jvm metric

https://github.com/prometheus/jmx_exporter/issues/111#issuecomment-341983150

>@brian-brazil can you add some sort of tip to the readme that `jvm_* metrics are only exposed when using the Java agent`? It took me an hour or two of troubleshooting and searching old issues to figure this out, after playing only with the HTTP server version. Thanks!
