### ISSUE TITLE
Maven Compiler target version

### ISSUE THREAD

**Issue by picadoh** [prometheus/jmx_exporter#281]
The current default target version is 1.6 (parent pom.xml) but the jmx_exporter does not compile with 1.6. It requires at least 1.7 because of its dependencies.

Example here:

https://jitpack.io/com/github/prometheus/jmx_exporter/-parent-0.3.1-g2db4f0c-3/build.log
```
Caused by: java.lang.UnsupportedClassVersionError: org/codehaus/mojo/buildhelper/ReserveListenerPortMojo : Unsupported major.minor version 51.0
```

For tools that select the compiler to use based on the target version (e.g. Jitpack) this upgrade is necessary.

**Comment by brian-brazil** [comment]
What's pulling that in?
