### ISSUE TITLE
Can't assign custom labels to process or jvm related metrics

### ISSUE THREAD

**Issue by DivsDibs** [prometheus/jmx_exporter#294]
The rules probably don't give us an option to add a _custom_ label to the metrics having the namespaces like
process.cpu.seconds.total, (process.*),
jvm_memory_bytes_used (jvm.*).

Is there a way to associate a custom label like "services=my-app" to these metrics, from the app side? Associating a metric, on prometheus side based on instance ip values of where the app is deployed, sound a little less dynamic to me. We use multi-tenancy in Cloud. There can be multiple JVMs running on the same node. How can we distinguish in such case? 

We are running the jmx_exporter as a javaagent, as recommended to export kafka metrics.
`KAFKA_OPTS="$KAFKA_OPTS -javaagent:$PWD/jmx_prometheus_javaagent-0.10.jar=9192:$PWD/kafka-0-10-1-1.yml" /opt/kafka_2.11-0.10.1.1/bin/kafka-server-start.sh /opt/kafka_2.11-0.10.1.1/config/server.properties &` .

**Comment by brian-brazil** [comment]
This is by design, you can do this via target labels on the Prometheus side using relabel_configs.

**Comment by baiwfg2** [comment]
@brian-brazil I don't understand. For example, java original jmx metrics can have labels,
```
java_lang_MemoryPool_UsageThresholdSupported{name="PS Eden Space",} 0.0
java_lang_MemoryPool_UsageThresholdSupported{name="Code Cache",} 1.0
java_lang_MemoryPool_UsageThresholdSupported{name="Compressed Class Space",} 1.0
java_lang_MemoryPool_UsageThresholdSupported{name="PS Survivor Space",} 0.0
# HELP java_lang_Threading_ThreadContentionMonitoringEnabled ThreadContentionMonitoringEnabled (java.lang<type=Threading><>ThreadContentionMonitoringEnabled)
# TYPE java_lang_Threading_ThreadContentionMonitoringEnabled untyped
java_lang_Threading_ThreadContentionMonitoringEnabled 0.0
# HELP java_lang_OperatingSystem_CommittedVirtualMemorySize CommittedVirtualMemorySize (java.lang<type=OperatingSystem><>CommittedVirtualMemorySize)
# TYPE java_lang_OperatingSystem_CommittedVirtualMemorySize untyped
java_lang_OperatingSystem_CommittedVirtualMemorySize 4.388687872E9
# HELP java_lang_GarbageCollector_LastGcInfo_memoryUsageAfterGc_used java.lang.management.MemoryUsage (java.lang<type=GarbageCollector, name=PS Scavenge, key=Compressed Class Space><LastGcInfo, memoryUsageAfterGc>used)
# TYPE java_lang_GarbageCollector_LastGcInfo_memoryUsageAfterGc_used untyped
java_lang_GarbageCollector_LastGcInfo_memoryUsageAfterGc_used{name="PS Scavenge",key="Compressed Class Space",} 1172328.0
java_lang_GarbageCollector_LastGcInfo_memoryUsageAfterGc_used{name="PS Scavenge",key="PS Survivor Space",} 2605104.0
java_lang_GarbageCollector_LastGcInfo_memoryUsageAfterGc_used{name="PS Scavenge",key="PS Old Gen",} 912376.0
java_lang_GarbageCollector_LastGcInfo_memoryUsageAfterGc_used{name="PS Scavenge",key="Metaspace",} 9618648.0
```

How should I create a MBean, whose metrics can be exported by jmx_exporter into the one that has a custom labels ?
