### ISSUE TITLE
qualys scan is causing high cpu on the jmx_exporter configured hosts

### ISSUE THREAD

**Issue by rajpaly** [prometheus/jmx_exporter#297]
Hello,

we have configured jmx_exporter for expose cassandra metrics to prometheus . whenever we run a qualys scan for vulnerability validation we are seeing high cpu spike and during that time we are seeing java process and gc porcess has high cpu consuming process.  and also when i do netstat i see 100s of lines from qualys scan server.  why does jmx_exporter let the qualys scan open so many threads?

**Comment by brian-brazil** [comment]
There is a thread limit of 5 in there, however if you DOS any application you shouldn't be surprised if it falls over.

**Comment by rajpaly** [comment]
Thanks @brian-brazil  cay point me where the thread limit is configurable?

**Comment by brian-brazil** [comment]
It's hardcoded in https://github.com/prometheus/client_java/blob/master/simpleclient_httpserver/src/main/java/io/prometheus/client/exporter/HTTPServer.java#L149

If you need something a bit more custom, you'd need to provide your own http server.

**Comment by rajpaly** [comment]
is this something configurable on the host where jmx_exporter is running?

**Comment by brian-brazil** [comment]
There is no way to configure it, nor is it planned. It's meant to work sanely for most use cases, while still mitigating DOSes.

**Comment by brian-brazil** [comment]
I don't think there's anything for us to do here.
