### ISSUE TITLE
Prometheus jmx_exporter is not working with istio

### ISSUE THREAD

**Issue by LucasBoisserie** [prometheus/jmx_exporter#304]
Hello,

The _jmx_exporter_ is not working with ISTIO. When prometheus try to scrape metrics, it gets a HTTP 503 errors
After some investigation, the HTTP error is throw by _envoy_ (sidecar istio proxy embedded in the pod with the application).
In the _envoy_ log, there is the error message below:
```
[C11] protocol error: http/1.1 protocol error: HPE_UNEXPECTED_CONTENT_LENGTH
"GET /metrics HTTP/1.1" 503 UC 0 57 48 - "-" "Prometheus/2.3.1"
```

Before forward a request to the app container, envoy check the HTTP syntax.
We tried to reproduce this issue with _curl_.
After looking in prometheus source code to find the request sent, the error appears when the `Accept-Encoding` header is set with the `gzip` value.

We launch jmx_prometheus_httpserver in local to debug
```
$ curl -v  http://localhost:8080/metrics -H "Accept-Encoding: gzip"
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /metrics HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Accept-Encoding: gzip
>
< HTTP/1.1 200 OK
< Date: Thu, 09 Aug 2018 09:15:56 GMT
< Content-encoding: gzip
< Content-length: 627
< Content-type: text/plain; version=0.0.4; charset=utf-8
< Transfer-encoding: chunked

```
According to the envoy error message, the issue come from the `Content-length` header.
According to the http 1.1 spec, in the Chunked Transfer part, it specified that when a transfer-encoding is set to chunked, the content-length must be not set (https://tools.ietf.org/html/rfc7230#section-4.1.2).

**Comment by brian-brazil** [comment]
> it specified that when a transfer-encoding is set to chunked, the content-length must be not set (https://tools.ietf.org/html/rfc7230#section-4.1.2).

That specifies it can't be sent as a trailer, it doesn't say anything about a header. 3.3.2 is the section you want. The relevant code is over in client_java, would you like to send a PR?

**Comment by brian-brazil** [comment]
Closing in favour of client_java issue.

**Comment by kringol** [comment]
Any chance of a new jmx_exporter version soon including the upgrading to the new client_java (0.6.0) so that this issue can be fixed?

**Comment by avillev** [comment]
Same here, @brian-brazil , when can we expect seeing that fix in a released version of the jmx_exporter ?

**Comment by varun-da** [comment]
good debugging @LucasBoisserie!

**Comment by varun-da** [comment]
upgrading to 0.12.0 fixed the issue.
