### ISSUE TITLE
Causing JVM freeze when scrape a large kubernetes pod

### ISSUE THREAD

**Issue by huaxiawang** [prometheus/jmx_exporter#306]
Pod resources:
```
32 CPUs
64 GB memory
```

Prometheus settings:
```
global:
  scrape_interval:     1m
  evaluation_interval: 1m
  scrape_timeout:      10s
```

The scrape will cause JVM completely freeze until scrape timed out, see graph generated by jHiccup:
With jmx_exporter enabled
![se_with_prometheus](https://user-images.githubusercontent.com/8367961/44479436-713a0b00-a5f5-11e8-9869-30bf6d43bf21.png)

With jmx_exporter disabled
![se_without_prometheus](https://user-images.githubusercontent.com/8367961/44479640-01785000-a5f6-11e8-8825-4d8643806379.png)

And even jmx_exporter would fail to get actual results:
![prometheus](https://user-images.githubusercontent.com/8367961/44479758-616ef680-a5f6-11e8-8a4f-7b921303bc1e.png)

The long time freeze only happens on large pods, for smaller pods with 8 CPUs and 16 GB memory, it will introduce some overhead(1~2 seconds), but won't freeze the JVM completely.
Thus it appears to me that the collector might have some issue with collecting on large instances.

After playing with jmx_exporter and configuration yaml file, I found there is a default exporter that will scrape a list of jvm information no matter how, and some of them might be expensive.
[DefaultExports.initialize();](https://github.com/prometheus/jmx_exporter/blob/master/jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java#L53)
But the question is why the scraping on large instance would be much worse?

**Comment by brian-brazil** [comment]
JMX and the JMX exporter know nothing of machine sizes. This is most likely an issue with the JMX mBeans being provided by your application.

**Comment by huaxiawang** [comment]
But when I downgraded my machine size, this issue is not so bad.
I tested same application in different machine sizes, e.g. 8 cores, 16 GB and 32 cores, 64 GB.
The number of mBeans might be a lot more, but the time of scrape is not linearly increasing according to what I have.

**Comment by brian-brazil** [comment]
You're not giving me much information to go on here. I've no idea what application you're working with for example, or what the config is. All I can tell you is that the machine size should have no notable effect on jmx exporter performance.

**Comment by huaxiawang** [comment]
I will see if it's some collectors in client_java cause this issue, thank you.

**Comment by brian-brazil** [comment]
This has gone stale, I'm presuming it was an application issue.
