### ISSUE TITLE
Argument parsing fails on Windows with absolute configuration file path

### ISSUE THREAD

**Issue by enyone** [prometheus/jmx_exporter#312]
Reason is `string.split(":")` is used blindly when parsing arguments.

```
java.exe "-javaagent:./jmx_prometheus_javaagent-0.3.1.jar=8080:C:\config.yaml" -jar "C:\yourJar.jar"
```

**Comment by brian-brazil** [comment]
Currently you can workaround this using relative paths

**Comment by mvdobrinin** [comment]
You can also work around this by using absolute paths from the current drive. 

```\Program Files\Custom Utilities\StringFinder.exe```

See the MS docs - https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats.

**Comment by mvdobrinin** [comment]
@brian-brazil Let me know your thoughts. 😄

**Comment by mvdobrinin** [comment]
#371
