### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by rodlogic** [prometheus/jmx_exporter#313]

**Comment by brian-brazil** [comment]
The jmx exporter is on maven central, that's the official place to download it from.

**Comment by brian-brazil** [comment]
There is no 0.3.2 yet (and likely won't be), but 0.3.1 is there: http://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/

**Comment by rodlogic** [comment]
I see the confusion now: Maven Repository (mvnrepository.com) is showing 0.10 as the latest from 2017 (top of the list), but the latest deployment date is 0.3.1 in May 2018.
