### ISSUE TITLE
Explain that latest is release is 0.3.1 (not 0.9, 0.10 or  0.11)

### ISSUE THREAD

**Issue by finkr** [prometheus/jmx_exporter#314]
Hello,

I took some time me to figure out that  the current latest release is 0.3.1

The version history is :
- 0.3 > 0.4 > ...  > 0.9 > 0.10 > 0.11 > 0.1.0 > 0.2.0 > 0.3.0 > **0.3.1**

Looking at version number, one may assume that 0.9 is more recent than 0.3.1, which is not.
Also, 0.3.1 is not a maintenance release for 0.3

The time wrap occurred in **0.11 => 0.1.0** [commit](https://github.com/prometheus/jmx_exporter/commit/8c6781217fe9a137b1f8086de2a4b85bab238538)

It would be nice to have a note somewhere (here or README file)

**Comment by rodlogic** [comment]
FYI: I ran into the same confusion in #313. I initially thought that the latest releases where no longer being deployed to Maven central.

**Comment by muffl0n** [comment]
mvnrepository.com is confused aswell and so was I:
![mvnrepository.com showing that 0.10 is newer than 0.3.1](https://lh4.googleusercontent.com/LZxP39QdPsSMVqT0K28adeZ6fpYHSm_7xqfMJiWijuYDqq466DkmKaUELegWI0JqroYJjZHkEps9dQ=w1644-h1135)
https://mvnrepository.com/artifact/io.prometheus.jmx/collector/0.3.1

**Comment by brian-brazil** [comment]
0.11.0 is out.

**Comment by muffl0n** [comment]
Awesome! Thank you very much! Do you have an idea when it'll be available via https://mvnrepository.com/artifact/io.prometheus.jmx?

**Comment by brian-brazil** [comment]
I've no idea to be honest.

**Comment by finkr** [comment]
@muffl0n,  The jar for version 0.11.0 is now available for download at https://mvnrepository.com/artifact/io.prometheus.jmx
