### ISSUE TITLE
Why HTTPServer run in daemon  mode ?

### ISSUE THREAD

**Issue by irwinsun** [prometheus/jmx_exporter#316]
See  JavaAgent.java  line:54

> server = new HTTPServer(socket, CollectorRegistry.defaultRegistry, **true**);

 It will exit when I  scrape remote JMX targets, use like this
> java -javaagent:./jmx_prometheus_javaagent-0.3.1.jar=9999:mymonitor.yaml

**Comment by brian-brazil** [comment]
The java agent is intended to be injected into what you're trying to monitor - and stopping shutdown of that system would not be good. I'd recommend using the java agent inside whatever you're trying to monitor.

**Comment by irwinsun** [comment]
@brian-brazil Thank you!
But the user's Java server does not allow us to access or add the jmx exporter, only jmxremote is provided for access.  So I can only continue to use the old version of 0.10.
It would be great if you could provide an optional parameter.

**Comment by brian-brazil** [comment]
It makes no sense for the java agent to be a non-daemon thread. You want the httpserver.
