### ISSUE TITLE
Failed to create /opt/jmx-exporter-loader in my workload's container

### ISSUE THREAD

**Issue by gmflau** [prometheus/jmx_exporter#322]
Here is the log from my prometheus-jmx-exporter-operator-xxxx pod:

ime="2018-09-26T23:37:00Z" level=info msg="Inspecting pod 'dse-2'"
time="2018-09-26T23:37:00Z" level=info msg="Inspecting container 'dse' for java processes"
time="2018-09-26T23:37:01Z" level=info msg="Java processes: [161]"
time="2018-09-26T23:37:01Z" level=info msg="Copying the content of '/opt/jmx-exporter-loader' directory to 'default/dse-2/dse:/opt/jmx-exporter-loader'"
time="2018-09-26T23:37:01Z" level=info msg="Creating 'default/dse-2/dse:/opt/jmx-exporter-loader' if not exists."
time="2018-09-26T23:37:01Z" level=info msg="Executing command failed with: command terminated with exit code 1"
time="2018-09-26T23:37:01Z" level=error msg="Creating destination directory failed: command terminated with exit code 1"
time="2018-09-26T23:37:01Z" level=error msg="Copying jmx-exporter-loader jars to container 'default/dse-2/dse'failed: command terminated with exit code 1"
time="2018-09-26T23:37:01Z" level=warning msg="Processing pod failed: command terminated with exit code 1"

**Comment by gargamel83** [comment]
Hi, How did you fixed it? I have the same issue...
