### ISSUE TITLE
CPU consumption

### ISSUE THREAD

**Issue by garmes-gdev** [prometheus/jmx_exporter#324]
I am using the exporter to export kafka metrics, but I noticed some CPU  consumption (generate alerts)

![github_cpu](https://user-images.githubusercontent.com/15848932/46339390-f4a63d80-c632-11e8-9b86-f1c5ec12c08e.PNG)

I spend a lot of time to debug the exporter,  my remark is, during the for loop that call RMI to get metrics values I got spikes.

My suggestion  is to not use  the external connection with Agent mode : 
use `ManagementFactory.getPlatformMBeanServer();`   to pull metrics 

![git_cpu_after](https://user-images.githubusercontent.com/15848932/46340084-b742af80-c634-11e8-9ccf-96f5bfd46622.PNG)

**Comment by brian-brazil** [comment]
Running as an agent is already the recommended way to do things.

**Comment by malud** [comment]
@garmes-gdev can you explain which sources you exactly mean or you have edited? `ManagementFactory.getPlatformMBeanServer()` gets automatically used of no jmx url is provided via config in `JmxScraper class`.

Since we have a high CPU Load with this agent enabled (~60%, without 5% avg) I thought it could help but we don't provide a jmxUrl config option.

**Comment by bshishir** [comment]
@garmes-gdev I am facing the same issue of high cpu consumption at regular intervals once a day. Any solutions?

**Comment by garmes-gdev** [comment]
Hello @brian-brazil , @bshishir, sorry for the issue.

@bshishir  if you run the exporter as an agent [ -javaagent:/path_to_jar/jmx_prometheus_javaagent.jar={{port}}:/path_to_conf_file/jmx_exporter_config.yaml

find below my conf file (don't use hostname option in the file )

---
startDelaySeconds: 0
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames: ["*:*"]

bests
