### ISSUE TITLE
Address already used if running Prometheus JMX exporter as an agent

### ISSUE THREAD

**Issue by DatPhanTien** [prometheus/jmx_exporter#325]
Dear

We are using JMX exporter 0.3.1 to export metrics of HBASE.
To do so, we add the following line into HBase hbase-env.sh conf

export HBASE_OPTS="$HBASE_OPTS -XX:+UseConcMarkSweepGC -javaagent:/app/otrace/bin/hbase/lib/jmx_prometheus_javaagent-0.3.1.jar=9094:/app/otrace/bin/hbase/conf/hbase_jmx_config.yaml"

We manage to start HBase with the exporter running as the agent.

However, we notice that for the second time calling the hbase bin command (such as ./bin/stop-hbase.sh, ...), it will try to start another time the JMX exporter agent, which is already running. The command will then exits as error.

As a result, we just wonder if there exists another way to config the JMX agent to be started only once.

Best 
Tien Dat

**Comment by brian-brazil** [comment]
With that setting you've presumably set things to be added to all JVMs related to HBASE. You should adjust the config so it only applies to the main server.

**Comment by DatPhanTien** [comment]
Thanks for you fast answer. I just don't know exactly how to make it applied only to the main server. All instruction of how to config JXM exporter, that I am aware of, lead me to the aforementioned config.

Could you please enlighten me with the right config, if you have?

Best

**Comment by polohb** [comment]
Maybe this is because you're in "pseudo-distributed" mode with many master on the same host.

Just follow this tutorial and I think it will be okay : https://blog.godatadriven.com/hbase-prometheus-monitoring.

All is explained with a script to manage many port for each Instance.

**Comment by DatPhanTien** [comment]
Perfect.
That is what I am looking for.
Thank you.
Shall I close the issue?
