### ISSUE TITLE
Configuring the JMX port on the fly

### ISSUE THREAD

**Issue by DatPhanTien** [prometheus/jmx_exporter#328]
Dear

We are using JMX_exporter to export metrics to Prometheus.
One of the applications that we use has multiple JAVA processes running, each process exports metrics to a different JMX port. During the run time, the number of JAVA processes can increase/decrease. 
These means there will be a dynamic number of processes to be monitored, which means the list of JMX ports is not constant.

Our question is: whether it is possible to dynamically:
1) Configure the JMX port on which the JMX_exporter is listening on the fly
2) Configure the port on which JMX_exporter is exposing metrics on the fly

Best regards
Tien Dat

**Comment by brian-brazil** [comment]
No this isn't possible, you must provide the port you want used when loading the agent.

**Comment by DatPhanTien** [comment]
I see.
A out of topic question, if you don't mind. 
How can we set the prefix, suffix or specific label for all metrics exported by one given JMX_Exporter agent. This would make the query much easier on Prometheus, since distinguishing between metrics of a different components would be hard using port numbers.
It is difficult to keep track of the components and port numbers mapping.

Best regards
Tien Dat

**Comment by brian-brazil** [comment]
Prometheus considers that to be a service discovery issue to be handled by target labels, not the responsibility of an exporter.
