### ISSUE TITLE
No Agent-class manifest attribute

### ISSUE THREAD

**Issue by DatPhanTien** [prometheus/jmx_exporter#329]
Dear

We are using JMX_exporter version 0.3.1.
We would like to load the JMX agent programmatically.

However, when we tried to do so, JAVA complains that the jar was built without Agent-Class manifest attribute.
We extract the jar and we found out that is was indeed missing:
`Manifest-Version: 1.0
Premain-Class: io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent
Archiver-Version: Plexus Archiver
Built-By: bbrazil
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_162`

Could it be possible to provide a jar with all: Premain-Class, Main-Class and Agent-Class attributes mentioned?

Thank you

**Comment by brian-brazil** [comment]
This was added in #280

**Comment by morganwalker** [comment]
@DatPhanTien were you able to find a jar that worked? I'm getting `no main manifest attribute` when attempting to use 0.3.1.

**Comment by mootezbessifi** [comment]
@morganwalker  i am getting the same issue from my side. any solution please ?
