### ISSUE TITLE
Some collection items are missing in windows server ?

### ISSUE THREAD

**Issue by dafanshu520** [prometheus/jmx_exporter#331]
I found that the collecting item of jmx_exporter like process_resident_memory_bytes, process_open_fds, process_max_fds, process_virtual_memory_bytes are missing in windows server, I use Apache Tomcat 8.5 in windows server 2012 for tesing, is there something wrong ?

**Comment by dafanshu520** [comment]
1

**Comment by brian-brazil** [comment]
Those only work on Linux. PRs welcome to extend that to Windows.

**Comment by brian-brazil** [comment]
And those would be for client_java.
