### ISSUE TITLE
wildfly 13.0.0.FINAL

### ISSUE THREAD

**Issue by kpaxindustries** [prometheus/jmx_exporter#344]
When trying to use the agent against wildfly 13.0.0 FINAL, I am getting the following error on startup.

The server is a simple standalone one

i have followed other posts on the issues board to try and get it working, but get a stacktrace on startup

My JAVA_OPTS in standalone.conf are as follows

```
JBOSS_MODULES_SYSTEM_PKGS="org.jboss.byteman,org.jboss.logmanager"

JAVA_OPTS="-Xms16g -Xmx16g -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true"
JAVA_OPTS="$JAVA_OPTS -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS -Djava.awt.headless=true"
JAVA_OPTS="$JAVA_OPTS -Xbootclasspath/p:/opt/wildfly/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-2.1.2.Final.jar"
JAVA_OPTS="$JAVA_OPTS -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
JAVA_OPTS="$JAVA_OPTS -javaagent:/opt/prometheus/jmx_exporter/jmx_prometheus_javaagent-0.3.1.jar=9102:/opt/prometheus/jmx_exporter/wildfly.yaml"
```

The stacktrace is as follows

```
=========================================================================

 

  JBoss Bootstrap Environment

 

  JBOSS_HOME: /opt/wildfly

 

  JAVA: java

 

  JAVA_OPTS:  -server -Xms16g -Xmx16g -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager -Djava.awt.headless=true -Xbootclasspath/p:/opt/wildfly/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-2.1.2.Final.jar -Djava.util.logging.manager=org.jboss.logmanager.LogManager -javaagent:/opt/prometheus/jmx_exporter/jmx_prometheus_javaagent-0.3.1.jar=9102:/opt/prometheus/jmx_exporter/wildfly.yaml -Xbootclasspath/a: -Djava.util.logging.manager=org.jboss.logmanager.LogManager

 

=========================================================================

 

java.lang.NoClassDefFoundError: org/wildfly/common/net/HostName

        at org.jboss.logmanager.ExtLogRecord.<init>(ExtLogRecord.java:87)

        at org.jboss.logmanager.Logger.log(Logger.java:796)

        at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:53)

        at org.jboss.logging.Logger.logf(Logger.java:2414)

        at org.jboss.as.server.logging.ServerLogger_$logger.serverHomeMismatch(ServerLogger_$logger.java:2362)

        at org.jboss.as.server.ServerEnvironment.<init>(ServerEnvironment.java:436)

        at org.jboss.as.server.Main.determineEnvironment(Main.java:339)

        at org.jboss.as.server.Main.main(Main.java:95)

        at org.jboss.modules.Module.run(Module.java:352)

        at org.jboss.modules.Module.run(Module.java:320)

        at org.jboss.modules.Main.main(Main.java:593)
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by gabrielbahniuk** [comment]
> No problem.

Did you solve the issue?

I am facing the same when upgrading from Wildfly 10 to Wildfly 13. Also saw a post in the mailing list but nobody answered it.

**Comment by dennisxnew** [comment]
> > No problem.
> 
> @kpaxindustries Did you solve the issue?
> 
> I am facing the same when upgrading from Wildfly 10 to Wildfly 13. Also saw a post in the mailing list but nobody answered it.
> 
> edit:
> 
> The solution for me was to add this line within standalone.conf:
> JAVA_OPTS="$JAVA_OPTS -Xbootclasspath/p:$JBOSS_HOME/modules/system/layers/base/org/wildfly/common/main/wildfly-common-1.4.0.Final.jar"
> 
> So the final standalone.conf should be like this (of course I hide my real config):
> 
> if [ "x$JAVA_OPTS" = "x" ]; then
> ...
> ...
> ...
> ...
> JAVA_OPTS="$JAVA_OPTS -Xbootclasspath/p:$JBOSS_HOME/modules/system/layers/base/org/wildfly/common/main/wildfly-common-1.4.0.Final.jar"
> ...
> ...
> ...
> ...
> else
> echo "JAVA_OPTS already set in environment; overriding default settings with values: $JAVA_OPTS"
> fi
> 
> I hope it works for you also.

It work for me, thanks~!
