### ISSUE TITLE
Switch config file to yaml

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/jmx_exporter#35]
Yaml is the standard config format for Prometheus, we should use that rather than json.

**Comment by inondle** [comment]
Hi Brian, 
I was looking at the prometheus Hactoberfest project list and was wondering if I could take on this project?

**Comment by brian-brazil** [comment]
Please do. The config format should the the same, just in yaml rather than json.

**Comment by inondle** [comment]
I looked over the project last night, would I need to add a yaml parser library and extend the JmxCollector class to handle Yaml files? Or is it just a matter of changing the existing config file to yaml? I don't see anything in jmx_exporter that can parse yaml files.

**Comment by brian-brazil** [comment]
It'd be adding a yaml parser library (preferably a light one) and replacing the existing json.
