### ISSUE TITLE
Missing Catalina:type=ThreadPool metrics

### ISSUE THREAD

**Issue by nickytd** [prometheus/jmx_exporter#353]
Hi 

using 
# TYPE jmx_exporter_build_info gauge
jmx_exporter_build_info{version="0.11.1-SNAPSHOT",name="jmx_prometheus_httpserver",} 1.0

with Tomcat 8.5.34

rules:
- pattern: 'Catalina<type=ThreadPool, name="(\w+-\w+)-(\d+)"><>(acceptCount):'
  name: tomcat_threadpool_$2
  labels:
    port: "$2"
    protocol: "$1"

produces following Exception and no metrics are returned to prometheus.

FINE: scrape: 'Catalina:type=ThreadPool,name="http-nio-8080"_[port, useSendfile, sniParseLimit, minSpareThreads, acceptorThreadPriority, deferAccept, acceptCount, maxThreads, pollerThreadPriority, modelerType, running, sslImplementation, defaultSSLHostConfigName, executorTerminationTimeoutMillis, sSLEnabled, name, domain, pollerThreadCount, localPort, connectionCount, maxHeaderCount, currentThreadCount, keepAliveTimeout, keepAliveCount, readBufSize, tcpNoDelay, threadPriority, maxConnections, maxKeepAliveRequests, soLinger, paused, selectorTimeout, socketProperties, writeBufSize, selectorPool, connectionLinger, useInheritedChannel, bindOnInit, connectionTimeout, backlog, acceptorThreadCount, soTimeout, currentThreadsBusy, alpnSupported, daemon, sslImplementationName]': Fail: java.rmi.UnmarshalException: error unmarshalling return; nested exception is:
	java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: org.apache.tomcat.util.net.SocketProperties

How we can get the Catalina ThreadPool metrics with the httpserver ?
Thanks

**Comment by brian-brazil** [comment]
This sounds like a Catalina issue.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by nickytd** [comment]
Thanks Brian
Here [is the link](https://groups.google.com/forum/#!topic/prometheus-users/3KQGLjJgwG8) if someone is facing the same issue
