### ISSUE TITLE
Port range for java agent

### ISSUE THREAD

**Issue by Bfoster-melrok** [prometheus/jmx_exporter#360]
Would it be possible to add a port range for the java agents instead of a single port? It could then bind to the first port in the range that it is able to.

My use case for this is I'd like to run a small spark cluster where the executors are running the java agent to expose their metrics, but if 2 executors land on the same worker node only one can bind to the port. To my knowledge, I cannot set different java options for each executor, so I am unable to set a different port for each one.

**Comment by brian-brazil** [comment]
This isn't something that an exporter should do, as that raises questions of things like service discovery. If you want to do something more complex with the port number I'd suggest a shell script to adjust things as needed.
