### ISSUE TITLE
JMX Exporter (probably) causing a Java exception into a tomcat application

### ISSUE THREAD

**Issue by jlvale** [prometheus/jmx_exporter#366]
So i'm running JMX Exporter inside a tomcat, and i'm calling the javaagent at setenv.sh: `CATALINA_OPTS="$CATALINA_OPTS -javaagent:$CATALINA_BASE/../jmx_prometheus`/jmx_prometheus_javaagent-0.3.1.jar=...". The tomcat is working properly, but some services are returning this Java exception: 
```
Erro na invocação do serviço findUserByUsername
Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
```

**Comment by brian-brazil** [comment]
This is likely a bug in your application. Do you have a full stack trace?
