### ISSUE TITLE
Unable to export MBean attribute of TabularData type

### ISSUE THREAD

**Issue by devsharma1979** [prometheus/jmx_exporter#372]
My application exposes custom MBean which has only one attribute of TabularData type (which contains  Objects CompositeDataSupport type)

only).  MBean data is visible using JConsole.  I am trying to use jmx_prometheus_javaagent to export metrics to prometheus. 

Issue I am facing is tabular data is not getting exported, During debug I noticed this could be related to following code (io.prometheus.jmx.JmxScrapper.java)-
`      
      logScrape(domain + beanProperties + attrName, "tabulardata");
            TabularData tds = (TabularData) value;
            TabularType tt = tds.getTabularType();

            List<String> rowKeys = tt.getIndexNames();

            CompositeType type = tt.getRowType();
            Set<String> valueKeys = new TreeSet<String>(type.keySet());
            valueKeys.removeAll(rowKeys);  /*This removes all the keys and prevent following to get executed, If I comment this line then metrics get exported*/
`

Reason for this is rowKeys are same as valueKeys,  this makes valueKeys empty and loop on valueKeys does not get executed.  I have attached structure of TabularData [AppInfoAdapter.zip](https://github.com/prometheus/jmx_exporter/files/3034323/AppInfoAdapter.zip. 

Let me know how this can be solved/any alternative? Is TabularData export supported by jmx_prometheus_javaagent.

**Comment by brian-brazil** [comment]
If you can implement an mBean then I'd suggest using client_java directly, rather than having to deal with JMX.

**Comment by devsharma1979** [comment]
Thanks Brian for response. App metrics are exposed over JMX so that other system can make use of  metrics+ other options.
 Using java_agent would keep app  independent of prometheus.

**Comment by brian-brazil** [comment]
client_java is independent of Prometheus. The Prometheus data format is a defacto standard supported by many competing monitoring solutions (most recently Zabbix). In addition client_java can't provide output only in Prometheus format, and will for example also support the OpenMetrics format and anything else you want.

In general, avoid JMX if you can. Among other things if the JMX exporter can't handle this, it's likely that other monitoring systems can't either.

**Comment by devsharma1979** [comment]
Thanks Brian,  I would explore suggested alternative.  
On side note, Jconsole is able to handle TabularData output in  this case.
