### ISSUE TITLE
Request to upgrade simpleclient to 0.6.0 for jmx_prometheus_javaagent

### ISSUE THREAD

**Issue by xSavian** [prometheus/jmx_exporter#379]
Hello, could you please upgrade dependency for jmx_prometheus_javaagent to 0.6.0 here:
https://github.com/prometheus/jmx_exporter/blob/9ffbfe2bb4d4154cc89c2d84ed704d7dab6641fd/jmx_prometheus_javaagent/pom.xml
I find out what simpleclient http_server v.0.3.0 has some problems with kubernetes Prometheus operator.

**Comment by brian-brazil** [comment]
Would you like to send a PR?

**Comment by xSavian** [comment]
Hello, @brian-brazil Can we close this issue? And can you tell when will be next release?

**Comment by brian-brazil** [comment]
I'll put a release on my todo list.
