### ISSUE TITLE
Failed to start latest zookeeper when using the exporter

### ISSUE THREAD

**Issue by skk2142** [prometheus/jmx_exporter#391]
I'm trying to use the exporter with the latest zookeeper release (3.5.5). I'm using the settings as suggested in https://alex.dzyoba.com/blog/jmx-exporter/. In particular, I set
```bash
# zookeeper-env.sh
SERVER_JVMFLAGS="-javaagent:/opt/jmx-exporter/jmx-exporter.jar=7070:/etc/jmx-exporter/zookeeper.yml"
```
and run zookeeper using the command:
```bash
/home/ubuntu/zookeeper/bin/zkServer.sh start /home/ubuntu/zookeeper/conf/zoo.cfg
```
I get this error:
```
ZooKeeper JMX enabled by default
Using config: /home/ubuntu/zookeeper/conf/zoo.cfg
Starting zookeeper ... /home/ubuntu/zookeeper/bin/zkServer.sh: line 149:  5534 Aborted                 (core dumped) nohup "$JAVA" $ZOO_DATADIR_AUTOCREATE "-Dzookeeper.log.dir=${ZOO_LOG_DIR}" "-Dzookeeper.log.file=${ZOO_LOG_FILE}" "-Dzookeeper.root.logger=${ZOO_LOG4J_PROP}" -XX:+HeapDumpOnOutOfMemoryError -XX:OnOutOfMemoryError='kill -9 %p' -cp "$CLASSPATH" $JVMFLAGS $ZOOMAIN "$ZOOCFG" > "$_ZOO_DAEMON_OUT" 2>&1 < /dev/null
FAILED TO START
```
Without using the exporter, zookeeper works fine. I'm using ubuntu18.04 and I set 
```
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
```
I don't have much experience with java. Could this a java version issue? Please suggest what I should do. Thanks.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
