### ISSUE TITLE
The release 0.12.1 is not available in Maven Central Repository

### ISSUE THREAD

**Issue by agaengel** [prometheus/jmx_exporter#397]
I just noticed that the release 0.12.1 is not available in Maven Central Repository

Regards
Alex

**Comment by brian-brazil** [comment]
There is no 0.12.1.

**Comment by agaengel** [comment]
but it is listed as latest release: https://github.com/prometheus/jmx_exporter/releases/tag/parent-0.12.0

**Comment by brian-brazil** [comment]
Ah, that's a typo. Fixed.
