### ISSUE TITLE
Agent Test has bad check for empty javaHome

### ISSUE THREAD

**Issue by swpalmer** [prometheus/jmx_exporter#405]
It looks like this line:
https://github.com/prometheus/jmx_exporter/blob/cae9f262557f4460a3de920fa9542f8ed75f5cbe/jmx_prometheus_javaagent/src/test/java/io/prometheus/jmx/JavaAgentIT.java#L62

Should be:

`if (javaHome != null && !javaHome.isEmpty()) {`

**Comment by brian-brazil** [comment]
Would you like to send a PR?

**Comment by bristy** [comment]
@brian-brazil  Do you want me to send PR for this?

**Comment by brian-brazil** [comment]
Please.
