### ISSUE TITLE
Not able to get custom metrics

### ISSUE THREAD

**Issue by Xat59** [prometheus/jmx_exporter#407]
Hello team,

using jmx_exporter , I'm not able to retrieve custom application metrics.

Here is the jmx exporter configuration :
```
hostPort: 127.0.0.1:38383
ssl: false
username:
password:
lowercaseOutputLabelNames: true
lowercaseOutputName: true
rules:
- pattern: 'java.lang:<type=OperatingSystem><>Arch:'
  name: test2
```

I also tried to set jmxUrl instead of hostPort : 
jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:38383/jmxrmi

And tried to remove 'username' / 'password' because I do not use them. But I get the same behavior.

Then I run the jvm exporter as javaagent of my application :
```
java -Xms1024M -Xmx1024M -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=38383 -Dcom.sun.management.jmxremote.rmi.port=38383 -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=true -javaagent:/opt/exporters/jmx/jmx_prometheus_javaagent-0.11.0.jar=8080:/opt/exporters/jmx/config.yml
```

Using command line directly, it works fine, meaning jmx is enabled :
```
$ java -jar cmdline-jmxclient-0.10.3.jar '-' localhost:38383 java.lang:type=OperatingSystem Arch
08/06/2019 14:29:04 +0200 org.archive.jmx.Client Arch: amd64
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
