### ISSUE TITLE
Still can't get it to work when Istio Sidecar enabled

### ISSUE THREAD

**Issue by lilvyao** [prometheus/jmx_exporter#421]
This is the first time I am opening an issue in Git. Please forgive me if I didn't quite follow the format or missed any info. 

I thought my problem is related to issue #304, but I tried upgrading the JMX Exporter version to 0.12, and still no luck. 

I am still having issues collecting metrics when Istio Sidecar enabled. The errors I am getting from the Prometheus UI are like: Get http://<POD_IP>:7000/metrics: EOF. 

Two things I noticed: 
1. It works perfectly fine when Istio Sidecar wasn't enabled;
2, I am able to get all of the metrics from those pods which have Istio sidecar enabled through "curl" from any pod within the same k8s cluster even inside Prometheus pod itself. It is just the Prometheus app itself is not getting them. 

_**JMX Exporter version:**_ jmx_exporter_build_info{version="0.12.0",name="jmx_prometheus_javaagent",} 1.0

My Prometheus was deployed through the last helm stable chart repo: https://github.com/helm/charts/tree/master/stable/prometheus-operator

**Comment by brian-brazil** [comment]
Does tcpdump indicate what's going on?
