### ISSUE TITLE
Tomcat application doesn't start, application endpoints throw 404

### ISSUE THREAD

**Issue by bc-mahesh** [prometheus/jmx_exporter#429]
Hello,

I am running the jmx exporter as a standalone server to read JMX metrics remotely. But there is an issue, when we start tomcat, our app endpoints throw 404, meaning the application never starts up. We think the jmx port somehow prevents a clean startup. Is there a known issue for this?

> No mapping found for HTTP request with URI [/service-0.1/ping] in DispatcherServlet with name 'main'

We have to to stop jmx exporter, start tomcat and then start jmx exporter again as a workaround now.

**Comment by hramadur** [comment]
Hi,  Could you let me know the steps / commands to start the jmx exporter stand alone please ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by bc-mahesh** [comment]
> Hi, Could you let me know the steps / commands to start the jmx exporter stand alone please ?

java -jar jmx_prometheus_httpserver-0.12.0-jar-with-dependencies.jar 9103 jmx_exporter.yml &

**Comment by hramadur** [comment]
Could you please provide the contents on jmx_exporter.yml  file ?
Also, from where did you fetch this jmx_prometheus_httpserver-0.12.0-jar-with-dependencies.jar file ?

**Comment by bc-mahesh** [comment]
Hi @hramadur,
Contents of the jmx_exporter.yml - 

> hostPort: svor-abb107:35135
> username:
> password:
> rules:
> - pattern: ".*"

I fetched this from - https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_httpserver/0.12.0/jmx_prometheus_httpserver-0.12.0-jar-with-dependencies.jar

I am still facing this issue.

**Comment by hyprsnpr** [comment]
I'm also having this issue, did you ever get an answer?

**Comment by wanghy8166** [comment]
+1

**Comment by bc-mahesh** [comment]
No answer yet!
