### ISSUE TITLE
JMX Exporter does not use local MBeanServer when running as an agent

### ISSUE THREAD

**Issue by Hangleton** [prometheus/jmx_exporter#456]
Hello,

I have been using the Prometheus JMX Exporter running as an agent in Apache Kafka broker JVMs in an attempt to avoid using the JMX-RMI protocol which is used when the exporter runs in a standalone JVM.

The problem is even when running as an agent, the exporter still uses the RMI-based protocol to communicate with the `MBeanServer` and fetch the attributes of MBeans. I tried replacing the implementation of `MBeanServer` the exporter relies on. This is defined in `io.prometheus.jmx.JmxScraper`. I noticed significant gains, as shown in 50th, 90th and 100th percentiles in the tables below (column "scrape time"):

![phoque1](https://user-images.githubusercontent.com/638312/71582258-3e652880-2b01-11ea-93d6-07ef18ee955f.png)

![phoque2](https://user-images.githubusercontent.com/638312/71582260-41601900-2b01-11ea-8511-9e440c6ac9e0.png)

Given excessive scrape time of JMX beans is a common problem with Apache Kafka, I was curious about the reasons the implementation does not allow to choose a local `MBeanServer` when running as a JVM agent?

**Comment by brian-brazil** [comment]
Did you tell it to use RMI by providing a jmxUrl?

**Comment by Hangleton** [comment]
There was a jmxUrl property, yes.
I just read the code and can see the platform MBeanServer is used if the property is empty.
So it just works already... Don't know why i did not see it.

**Comment by brian-brazil** [comment]
This is why using the agent is encouraged :)
