### ISSUE TITLE
How to export Spring Boot `http.server.requests` as Prometheus Histogram

### ISSUE THREAD

**Issue by rdohms** [prometheus/jmx_exporter#461]
This is a question, not an issue.

I have a Spring Boot setup, with micrometer and metrics turned on. I have successfully used `http.server.requests` to export a Counter of how many requests are happening.

However, I'm now stuck trying to create a Histogram of response times for these same requests.

What I have tried so far:
- Tried to find a way to extract the Attributes as a Prometheus Histogram, but found no way to do this
- Set `management.metrics.distribution.sla.http.server.requests: 1ms, 2ms, 5ms, 10ms, 20ms, 30ms` to get a set of gauges that represent the buckets

Has anyone achieved this before? I'm currently thinking along the lines of recreating the _sum, _count and _bucket parts separately from the gauge but I have not yet figured out how to do the sum and count parts. Any direction is much appreciated.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by rdohms** [comment]
ok thanks! 👍

**Comment by dominik-ba** [comment]
Anyhow since people stumble upon such questions thanks to google (like me), if there was an answer found in the mailing list, it might be helpful to give some hint here, too.

**Comment by rdohms** [comment]
No answer there so far @dominik-ba, here is the thread: https://groups.google.com/d/msgid/prometheus-users/855b6e7a-ce48-40b1-8db8-8ffc32df74fa%40googlegroups.com?utm_medium=email&utm_source=footer
