### ISSUE TITLE
Add a health check api in jmx exporter server.

### ISSUE THREAD

**Issue by bristy** [prometheus/jmx_exporter#465]
Add some sort of URL (www.https://[host]:[port]/health ) in JMX exporter to return 200 which indicate that server is working fine. We had a use case where we just wanted to check the health without scrapping the beans. Idea was to check if JMX exporter service is working fine and raise alarm if JMX exporter's health is bad.
Changes can be done here:
https://github.com/prometheus/jmx_exporter/blob/master/jmx_prometheus_httpserver/src/main/java/io/prometheus/jmx/WebServer.java

I am happy to take this up.

**Comment by brian-brazil** [comment]
This should follow how Prometheus itself does it.

**Comment by bristy** [comment]
Sure I can check how Prometheus report health check.

**Comment by bristy** [comment]
Prometheus has management api to report health.
https://prometheus.io/docs/prometheus/latest/management_api/

basis curl to the endpoint returns 
[host] curl localhost:9090/-/healthy
Prometheus is Healthy.

We can have similar management api for JMX exporter to return "jmx_exporter is Healthy."
eg. GET /-/healthy
curl jmxurl/-/healthy 
"jmx_exporter is Healthy."

@brian-brazil If you are agree with this, I can start working on implementation.

**Comment by brian-brazil** [comment]
Yes, that's what I meant.

**Comment by bristy** [comment]
@brian-brazil  Can I make this change to prometheus/client_java client? I am thinking of adding a new context("/-/healthy") with health handler?
This way it would be more generic.
https://github.com/prometheus/client_java

**Comment by brian-brazil** [comment]
If it doesn't break anything for users.

**Comment by bristy** [comment]
@brian-brazil  Hey I have made changes in java_client project. 
Can you please help me with consuming changes in jmx_exporter project? How do we upgrade the client version?

**Comment by brian-brazil** [comment]
There needs to be a release of the java client, then the dependency can be upgraded here, then there can be a release of the jmx exporter.

**Comment by brian-brazil** [comment]
This was picked up in 0.13.0.
