### ISSUE TITLE
Support custom JMX connector properties

### ISSUE THREAD

**Issue by bmesserer** [prometheus/jmx_exporter#469]
We're trying to connect to WebLogic via remote t3s protocol, but unfortunately, like quite a few other application servers, its remote "JMX over RMI" implementation uses a proprietary protocol called "t3" (or t3s over TLS) - see e.g. https://docs.oracle.com/cd/E13222_01/wls/docs90/jmx/accessWLS.html.
While it also supports IIOP, and newer versions have partially rectified this situation, many enterprises are still running lots of these app servers and enabling the possibility to scrape them is actually pretty simple - just allow to configure a few custom properties for the JMX environment.
These might also come in handy for more detailed customization as vendors (incl. Sun) use these for all configuration of the JMX connector.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by bmesserer** [comment]
> It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

This isn't a question. The JMX exporter currently does not support this because it doesn't support setting `jmx.remote.protocol.provider.pkgs` (and other necessary properties).
The prometheus-users mailing list [doesn't help](https://groups.google.com/forum/#!searchin/prometheus-users/jmx|sort:date/prometheus-users/nrEH0FLis3c/PL8TgA2nFwAJ) as it's not concerned with JMX/RMI protocol issues.

**Comment by sgoeschl** [comment]
@brian-brazil I actually asked on the user mailing list some time ago to no avail - please see

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/prometheus-users/nrEH0FLis3c
