### ISSUE TITLE
Some JMX GC metrics not exported after Java 11 upgrade

### ISSUE THREAD

**Issue by marko-asplund** [prometheus/jmx_exporter#475]
After upgrading from Java 8 to Java 11 some metrics fail to get exported
e.g. `java_lang_GarbageCollector_CollectionCount` and `java_lang_GarbageCollector_CollectionTime`.

I did manual scrapings for Java 8 and Java 11 based apps with the following results:
```
foo % grep CollectionCount jmx-metrics-java8.txt
java.lang{type=GarbageCollector, name=ParNew}[]CollectionCount: 10659
java.lang{type=GarbageCollector, name=ConcurrentMarkSweep}[]CollectionCount: 24
```
```
foo % grep CollectionCount jmx-metrics-java11.txt
java.lang{name=G1 Young Generation, type=GarbageCollector}[]CollectionCount: 811
java.lang{name=G1 Old Generation, type=GarbageCollector}[]CollectionCount: 0
```

When I do a query in Prometheus with the metric 'java_lang_GarbageCollector_CollectionCount' I get the ParNew and ConcurrentMarkSweep values, but not the G1 ones even though these look exactly the same (java.lang prefix, type=GarbageCollector).

The G1 ones are available however when querying with separate metrics `java_lang_G1_Young_Generation_CollectionCount` and `java_lang_G1_Old_Generation_CollectionCount`.

Looks like the first attribute is used as key in Prometheus, no matter what it is.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by marko-asplund** [comment]
@brian-brazil Thanks for the feedback.
I did reach out on prometheus-users.

Studying the code a bit, if I'm reading it right, the bean properties would appear to be processed in non-deterministic order here:
https://github.com/prometheus/jmx_exporter/blob/b28dd33dfb502315f558d882991ec634626912ff/collector/src/main/java/io/prometheus/jmx/JmxCollector.java#L310
What do you think?

**Comment by marko-asplund** [comment]
Issue discussed on prometheus-users and resolved:
https://groups.google.com/d/msg/prometheus-users/y1snSrJi4Xg/TNq5FHT6BgAJ
