### ISSUE TITLE
feature: Add correct handling of transformation for javaagent

### ISSUE THREAD

**Issue by vutkin** [prometheus/jmx_exporter#485]
Need to add correct handling of transformation for javaagent.

https://docs.oracle.com/javase/8/docs/api/java/lang/instrument/ClassFileTransformer.html
```
If the implementing method determines that no transformations are needed, it should return null. Otherwise, it should create a new byte[] array, copy the input classfileBuffer into it, along with all desired transformations, and return the new array. The input classfileBuffer must not be modified.
```
example: 
![image](https://user-images.githubusercontent.com/25753488/79222103-a268ee00-7e5f-11ea-815a-d4a99c4ddee2.png)

**Comment by brian-brazil** [comment]
Can you explain exactly what you're asking for? I'm lacking context here.

**Comment by vutkin** [comment]
You should not rely on default transformation developing java agent.

Regards, Viktor.

**Comment by brian-brazil** [comment]
I still don't understand what you're talking about.

**Comment by vutkin** [comment]
Ok, you may close the issue in this case.

Regards, Viktor.
