### ISSUE TITLE
Please upgrade snakeyaml to current version (1.26 as of this report)

### ISSUE THREAD

**Issue by matthiasmutam** [prometheus/jmx_exporter#488]
Currently, jmx_exporter uses snakeyaml 1.16 to parse YAML. This version has security issues that result in "high" findings in our whitesource reports. Not really an issue, I guess, but a nuisance always having to explain to our security guy why we ignore it.

**Comment by brian-brazil** [comment]
Yeah, as the yaml is user provided and they're able to load in a jmx agent there's no risk here. You can send a PR if you like.
