### ISSUE TITLE
no main manifest attribute, in jmx_prometheus_javaagent-0.12.0.jar

### ISSUE THREAD

**Issue by Jayesh-upvision** [prometheus/jmx_exporter#489]
Hello guys,

I have download the jmx_prometheus_javaagent-0.12.0.jar also version 0.11.0 and also created config.yml file in my linux system.
Java 1.8 is installed in my linux system.
I was trying to setup jmx_exporter as agent using below command.

`java -javaagent:./jmx_prometheus_javaagent-0.12.0.jar=8080:config.yml -jar jmx_prometheus_javaagent-0.12.0.jar`

But it gives the error.

no main manifest attribute, in jmx_prometheus_javaagent-0.12.0.jar

Brian please don't post same answer as you gave to all other people.
We are exacting a solution for that from you. 

As per your documentation it should work otherwise post the working things.

I request you to post the solution or edit the document and post working things.
Thanks

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Jayesh-upvision** [comment]
There is no solution, no any reference to this issue.
and you are closing everyone's new issue with this error.

**Comment by brian-brazil** [comment]
This is a general Java usage question, and I see no indication of a bug in this codebase or incorrect/misleading information in the docs. Accordingly the user list is a more appropriate place to ask about it.

**Comment by erickbreness** [comment]
I have the same issue, and checking the jar I'm trying to scrape I see this in the MANIFEST.MF file

Premain-Class: org.apache.cassandra.infrastructure.continuations.CAgent

The jar doesn't have a main class like

Main-Class: com.mypackage.MyClass

**Comment by vabinav** [comment]
```
abinavviswanathan@Abinavs-MacBook-Pro-2 META-INF % cat MANIFEST.MF 
Manifest-Version: 1.0
Implementation-Title: jmx_prometheus_javaagent
Premain-Class: io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent
Implementation-Version: 0.16.1
Archiver-Version: Plexus Archiver
Built-By: fabian
Agent-Class: io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent
Created-By: Apache Maven 3.8.1
Build-Jdk: 1.8.0_292
```

The MANIFEST.MF does not have Main-Class attribute specified.

 I believe this is a bug and thus I am getting the error above.
