### ISSUE TITLE
Process over other attributes when one of them is ignored

### ISSUE THREAD

**Issue by sooron** [prometheus/jmx_exporter#491]
Hi,

When using jmx-exporter as a http server, i tried to fetched some common metrics but encountered the following issue. As soon as an attribute is ignored, the processing of the MBean doesn't carry on to the other attributes and just stop.
This seems to be the case for String attributes for example.

Here are the logs you can get from a Spring Boot application exposing HikariCP metrics through JMX :

```
FINE: scrape: 'com.mydomain.test:pool=Hikari,type=hikaricp.connections'_'pool': process
May 05, 2020 3:28:29 PM io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'com.mydomain.test{pool=Hikari, type=hikaricp.connections}pool': Hikari
May 05, 2020 3:28:29 PM io.prometheus.jmx.JmxCollector$Receiver recordBean
FINE: Ignoring unsupported bean: com.mydomain.test<pool=Hikari, type=hikaricp.connections><>pool: Hikari
May 05, 2020 3:28:29 PM io.prometheus.jmx.JmxScraper doScrape
FINE: TIME: 189188736 ns for com.mydomain.test:pool=Hikari,type=hikaricp.connections
```

When looking in jconsole, the MBean has 2 attributes, pool and value, but the value attribute is never scraped.

I suppose I could add some filtering regexps to only fetch the value attribute, but why not processing valid attributes rather than stopping in such case ?

**Comment by brian-brazil** [comment]
That's not how the code works, if a bean doesn't have a value we can work with only that bean is ignored. Strings don't work unless you add additional config for them.

**Comment by sooron** [comment]
Yes, the whole bean is ignored, and not just the String attribute.
From the above example, the bean has a pool and value attribute, and gets ignored because of the pool attribute, even if the value attribute would be OK, since it's a number.

**Comment by brian-brazil** [comment]
Can you share what this looks like in jconsole? Those logs aren't showing a problem by themselves.

**Comment by sooron** [comment]
Here's the snapshot of the jconsole :

![thumbnail_image001](https://user-images.githubusercontent.com/11066709/81081253-f9f3fa00-8ef1-11ea-9f6c-8c0045556469.png)

**Comment by brian-brazil** [comment]
Are there logs from before that about the value?

**Comment by sooron** [comment]
After further investigation, it seemed that there was a problem with the jmx mbean.
With the same configuration, value is well fetched.
Sorry about this, closing this issue.
