### ISSUE TITLE
Multiple exporters on single JVM

### ISSUE THREAD

**Issue by jkimixl** [prometheus/jmx_exporter#498]
What would it take to allow for multiple javaagents to export the JMX info on different ports with different config files?  Use-case would be that you'd want to poll these ports at different intervals.

Current difficulty seems to come from #279 causing something like #290 .

If there's a workaround, then a pointer in that direction would be wonderful.  Thanks!

**Comment by brian-brazil** [comment]
That's not supported, but I guess you could do a custom build. Generally you should try to keep things to one interval per application.
