### ISSUE TITLE
javax.management.openmbean.TabularDataSupport cannot be cast to class javax.management.Attribute

### ISSUE THREAD

**Issue by joker234** [prometheus/jmx_exporter#501]
I run a plain [Apache Ignite](https://ignite.apache.org/download.cgi#binaries) installation, without anything configured or inside. Since the update to [Ignite 2.8.0](https://ignite.apache.org/releases/2.8.0/release_notes.html), I get this issue with the jmx exporter (latest release and built from current master):
```bash
% java -jar jmx_prometheus_httpserver/target/jmx_prometheus_httpserver-0.13.1-SNAPSHOT-jar-with-dependencies.jar 5556 example_configs/ignite.yml 
May 28, 2020 10:39:47 PM io.prometheus.jmx.JmxCollector collect
SEVERE: JMX scrape failed: java.lang.ClassCastException: class javax.management.openmbean.TabularDataSupport cannot be cast to class javax.management.Attribute (javax.management.openmbean.TabularDataSupport and javax.management.Attribute are in module java.management of loader 'bootstrap')
	at io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:160)
	at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:117)
	at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:473)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:190)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:223)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:144)
	at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
	at io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:68)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

example_configs/ignite.yml:
```yaml
---
hostPort: localhost:45013
```

I'm missing for example most of the `java.lang` output, that I still get via other tools like [jmxterm](https://github.com/jiaqi/jmxterm):
```bash
% jmxterm
Welcome to JMX terminal. Type "help" for available commands.
$>open localhost:45013
#Connection to localhost:45013 is opened
$>domain java.lang
#domain is set to java.lang
$>bean type=Memory
#bean is set to java.lang:type=Memory
$>get *
#mbean = java.lang:type=Memory:
Verbose = false;

ObjectPendingFinalizationCount = 0;

HeapMemoryUsage = { 
  committed = 262144000;
  init = 260046848;
  max = 4154458112;
  used = 40894464;
 };

NonHeapMemoryUsage = { 
  committed = 61423616;
  init = 7667712;
  max = -1;
  used = 57130496;
 };

ObjectName = java.lang:type=Memory;
```

This issue in the log sounds like something that is an error in the jmx exporters implementation of TabularData. Does this make sense to you? Since I'm still getting the values with several other tools, I think the issue is here somehow.
```
SEVERE: JMX scrape failed: java.lang.ClassCastException: class javax.management.openmbean.TabularDataSupport cannot be cast to class javax.management.Attribute (javax.management.openmbean.TabularDataSupport and javax.management.Attribute are in module java.management of loader 'bootstrap')
```

**Comment by brian-brazil** [comment]
See #483, it looks like that version of Ignite isn't implementing JMX correctly.

I notice that both you and the other issue are using the httpserver, have you tried the agent?

**Comment by tyrasd** [comment]
Isn't it the case that `AttributeList` explicitly (although discouragedly) allows non-`Attribute` values? From https://docs.oracle.com/javase/8/docs/api/javax/management/AttributeList.html#type-safe:

> For compatibility reasons, it is possible, though highly discouraged, to add objects to an AttributeList that are not instances of Attribute. However, an AttributeList can be made type-safe, which means that an attempt to add an object that is not an Attribute will produce an IllegalArgumentException. An AttributeList becomes type-safe when the method asList() is called on it.

**Comment by brian-brazil** [comment]
The exception is from where we're calling `asList` alright. We could be more resilient to this and not throw an exception, but we'd still not scrape anything. It still looks like Ignite is where this should be addressed.

**Comment by joker234** [comment]
> I notice that both you and the other issue are using the httpserver, have you tried the agent?
I tried that now, I get a little bit more metrics (especially `jvm_…`), but I still get the exception above and I'm still missing some e.g. `java_lang_Memory…`.

**Comment by brian-brazil** [comment]
The jvm_ and process_ metrics come from a different bit of code, so this isn't related to how you access JMX then.

**Comment by joker234** [comment]
I found a workaround, that works for me, for now: I used these whitelists:
```yaml
whitelistObjectNames:
  - "java.lang:type=OperatingSystem"
  - "java.lang:type=Threading"
  - "java.lang:type=Memory"
```
Is it possible for other cases, that the jmx exporter prints the error but *continues to scrape other* domains/beans that are actually working? Or print the current queried bean without using debugging logging.properties in case of an exception? That would have helped a lot to debug this :)

**Comment by brian-brazil** [comment]
> I found a workaround, that works for me, for now: I used these whitelists:

Those are covered by the jvm/process metrics that the agent produces itself and with better names/labels, so there's no need to configure them.

> that the jmx exporter prints the error but continues to scrape other domains/beans that are actually working

It generally tries to handle things gracefully, this is a deviation for JMX we've not come across before though.

> Or print the current queried bean without using debugging logging.properties in case of an exception? 

I'd rather not have two ways that logs are handled.

**Comment by nbonavia** [comment]
Added a pull request here. https://github.com/prometheus/jmx_exporter/pull/542
