### ISSUE TITLE
no main manifest attribute, in /opt/jmx_prometheus/jmx_prometheus_javaagent-0.13.0.jar

### ISSUE THREAD

**Issue by ask45** [prometheus/jmx_exporter#503]
java -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent-0.13.0.jar=7070:/opt/jmx_prometheus/6.yaml -jar **/opt/jmx_prometheus/jmx_prometheus_javaagent-0.13.0.jar

no main manifest attribute, in /opt/jmx_prometheus/jmx_prometheus_javaagent-0.13.0.jar

what should -jar be for monitoring cassandra with a separate agent demon for prometheus ?

java -javaagent:./jmx_prometheus_javaagent-0.13.0.jar=8080:config.yaml -jar yourJar.jar

what should yourJar.jar be for monitoring Cassandra  ?
i am trying to run jmx_eporter as a separate process instead of adding it to cassandra-env.sh

**Comment by mattrussi** [comment]
`-jar yourJar.jar` would be the JAR of the application that you want to monitor. In your case, it would be your Cassandra JAR. 

Typically for Cassandra, this is done by adding a variant of `java -javaagent:./jmx_prometheus_javaagent-0.13.0.jar=8080:config.yaml` to the environment variables in cassandra-env.sh.

> i am trying to run jmx_eporter as a separate process instead of adding it to cassandra-env.sh

I highly recommend running it as a javaagent as opposed to an external scraper. I've found it to be much easier to configure.

If you insist on running it separately, you can reference https://github.com/prometheus/jmx_exporter/blob/master/run_sample_httpserver.sh

**Comment by brian-brazil** [comment]
Thanks @mattrussi 

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
