### ISSUE TITLE
Zookeeper with zookeeper_id equal zero

### ISSUE THREAD

**Issue by p53** [prometheus/jmx_exporter#509]
I have zookeepers indexed from zero so also metrics are indexed with zero i get empty reply from server message

version 0.3.0 works
version 0.13.0 doesn't

**Comment by brian-brazil** [comment]
I'm not sure what you're talking about, this sounds like a support question. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by p53** [comment]
?? when i curl prometheus jmx exporter i get empty reply from server i suspect it has something to do with zero in zookeeper_id because nodes where zookeeper id is other than zero work

**Comment by scott-kirk** [comment]
I've been hitting this issue too after upgrading from 0.10.0 to 0.13.0. Our zookeeper clusters stopped reporting metrics from the zeroth zookeeper peer when rolling out the 0.13.0 upgrade. Rolling back the exporter version fixed the issue.
@p53 Did you figure out a workaround for this issue?

**Comment by nfillot** [comment]
Hello,

I also hit this issue with a zookeeper cluster and with zookeeper zero. I am getting an empty reply
Other nodes are working fine.

I pinpointed the issue with the 0.5.0 version of simpleclient_hotspot which added JVM metrics : https://github.com/prometheus/client_java/pull/391
0.4.0 version is working fine and is reporting metrics

Here is a sample of correctly exported metrics in 0.4.0 which might help pinpoint the issue

```# HELP org_apache_ZooKeeperService_ReplicatedServer_id0_JuteMaxBufferSize JuteMaxBufferSize (org.apache.ZooKeeperService<name0=ReplicatedServer_id0, name1=replica.0, name2=Follower><>JuteMaxBufferSize)
# TYPE org_apache_ZooKeeperService_ReplicatedServer_id0_JuteMaxBufferSize untyped
org_apache_ZooKeeperService_ReplicatedServer_id0_JuteMaxBufferSize{name1="replica.0",name2="Follower",} 1048575.0
# HELP org_apache_ZooKeeperService_ReplicatedServer_id0_OutstandingRequests OutstandingRequests (org.apache.ZooKeeperService<name0=ReplicatedServer_id0, name1=replica.0, name2=Follower><>OutstandingRequests)
# TYPE org_apache_ZooKeeperService_ReplicatedServer_id0_OutstandingRequests untyped
org_apache_ZooKeeperService_ReplicatedServer_id0_OutstandingRequests{name1="replica.0",name2="Follower",} 0.0
# HELP org_apache_ZooKeeperService_ReplicatedServer_id0_ElectionTimeTaken ElectionTimeTaken (org.apache.ZooKeeperService<name0=ReplicatedServer_id0, name1=replica.0, name2=Follower><>ElectionTimeTaken)
# TYPE org_apache_ZooKeeperService_ReplicatedServer_id0_ElectionTimeTaken untyped
org_apache_ZooKeeperService_ReplicatedServer_id0_ElectionTimeTaken{name1="replica.0",name2="Follower",} 23.0
# HELP org_apache_ZooKeeperService_ReplicatedServer_id0_ElectionType ElectionType (org.apache.ZooKeeperService<name0=ReplicatedServer_id0, name1=replica.0><>ElectionType)
# TYPE org_apache_ZooKeeperService_ReplicatedServer_id0_ElectionType untyped
org_apache_ZooKeeperService_ReplicatedServer_id0_ElectionType{name1="replica.0",} 3.0
# HELP org_apache_ZooKeeperService_ReplicatedServer_id0_MaxClientCnxnsPerHost MaxClientCnxnsPerHost (org.apache.ZooKeeperService<name0=ReplicatedServer_id0, name1=replica.0><>MaxClientCnxnsPerHost)
# TYPE org_apache_ZooKeeperService_ReplicatedServer_id0_MaxClientCnxnsPerHost untyped
org_apache_ZooKeeperService_ReplicatedServer_id0_MaxClientCnxnsPerHost{name1="replica.0",} 0.0
org_apache_ZooKeeperService_ReplicatedServer_id0_MaxClientCnxnsPerHost{name1="replica.0",name2="Follower",} 0.0

**Comment by nfillot** [comment]
Hello @brian-brazil 
Is it possible to re-open this issue ?
Thanks

**Comment by tobgu** [comment]
Seeing the exact same issue. Works fine with 0.12.
