### ISSUE TITLE
Problem, cant run jmx exporter

### ISSUE THREAD

**Issue by JeckiC** [prometheus/jmx_exporter#510]
pls help :) I hope this is good place to ask you.

Cant find similar problem. I have installed ActiveMQ in docker, something like: https://hub.docker.com/r/webcenter/activemq/, AMQ: -p 8161:8161 -p 61616:61616 -p 61613:61613 \
****
according to: https://github.com/prometheus/jmx_exporter I want to run jmx exporter on my AMQ server. I tried a lot of variants:

**1. I found activemq.jar (Docker)** /opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/bin/activemq.jar

**2. activemq.yml** = https://github.com/prometheus/jmx_exporter/blob/master/example_configs/activemq.yml

**3. cmd**: 
java -javaagent:/opt/scripts/jmx_prometheus_javaagent-0.13.0.jar=9110:/opt/scripts/activemq.yml -jar /opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/bin/activemq.jar

gets:

java -javaagent:/opt/scripts/jmx_prometheus_javaagent-0.13.0.jar=9110:/opt/scripts/activemq.yml -jar /opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/bin/activemq.jar Java Runtime: Oracle Corporation AAAAAAAAAA /usr/lib/jvm/java-AAAAAAAAAAAAA-openjdk-AAAAAAAAAAAAAA.el7_7.x86_64/jre Heap sizes: current=XXXXXXXX free=YYYYYYYYYYY max=ZZZZZZZZZZZZZ JVM args: -javaagent:/opt/scripts/jmx_prometheus_javaagent-0.13.0.jar=9110:/opt/scripts/activemq.yml Extensions classpath: [/opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/lib,/opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/lib/camel,/opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/lib/optional,/opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/lib/web,/opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/lib/extra] ACTIVEMQ_HOME: /opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq ACTIVEMQ_BASE: /opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq ACTIVEMQ_CONF: /opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/conf ACTIVEMQ_DATA: /opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/data Usage: Main [--extdir ] [task] [task-options] [task data]

Tasks: browse - Display selected messages in a specified destination. bstat - Performs a predefined query that displays useful statistics regarding the specified broker consumer - Receives messages from the broker create - Creates a runnable broker instance in the specified path. decrypt - Decrypts given text dstat - Performs a predefined query that displays useful tabular statistics regarding the specified destination type encrypt - Encrypts given text export - Exports a stopped brokers data files to an archive file list - Lists all available brokers in the specified JMX context producer - Sends messages to the broker purge - Delete selected destination's messages that matches the message selector query - Display selected broker component's attributes and statistics. start - Creates and starts a broker using a configuration file, or a broker URI. stop - Stops a running broker specified by the broker name.

Task Options (Options specific to each task): --extdir - Add the jar files in the directory to the classpath. --version - Display the version information. -h,-?,--help - Display this help information. To display task specific help, use Main [task] -h,-?,--help

Task Data: - Information needed by each specific task.

JMX system property options: -Dactivemq.jmx.url= (default is: 'service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi') -Dactivemq.jmx.user= -Dactivemq.jmx.password=

**4. the same but with** --version at the end gets: java -javaagent:/opt/scripts/jmx_prometheus_javaagent-0.13.0.jar=9110:/opt/scripts/activemq.yml -jar /opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/bin/activemq.jar --version Java Runtime: AAAAAAAAAAAAAA Heap sizes: current=XXXX free=YYYY max=ZZZZ JVM args: -javaagent:/opt/scripts/jmx_prometheus_javaagent-0.13.0.jar=9110:/opt/scripts/activemq.yml Extensions classpath: [/opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/lib,/opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/lib/camel,/opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/lib/optional,/opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/lib/web,/opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/lib/extra] ACTIVEMQ_HOME: /opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq ACTIVEMQ_BASE: /opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq ACTIVEMQ_CONF: /opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/conf ACTIVEMQ_DATA: /opt/docker/overlay2/a378910e4d6ca8e33b23502c106124644296b281e99343f14470dda79a326ff5/merged/opt/activemq/data

ActiveMQ 5.15.2 For help or more information please see: http://activemq.apache.org

**5.And finaly I cant't find any proces of exporter. Nothing on port 9110(defined by me in cmd) **

Any idea?

**Comment by brian-brazil** [comment]
This looks like an ActiveMQ usage question rather than a JMX exporter question, as the right command line arguments for the jmx exporter are in there and you're getting an ActiveMQ error. 
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
