### ISSUE TITLE
Blacklist individual MBean value

### ISSUE THREAD

**Issue by mmimica** [prometheus/jmx_exporter#512]
I need to blacklist `java.lang<type=OperatingSystem><name=CpuLoad>`. Currently, the scraper supports only blacklisting by MBean name. 
I need it blacklisted because it interacts with `SystemCpuLoad`. One of the two metrics always yields a invalid value, as explained on [this blog](https://medium.com/@milan.mimica/the-java-cpu-usage-observer-effect-18808b18323f). Presenting both metrics to end-users makes them choose which one to use and causes confusion.

**Comment by dhoard** [comment]
@mmimica I just create a PR (https://github.com/prometheus/jmx_exporter/pull/870) to allow MBean attribute exclusion filtering.

Can you review the enhancement to see if it satisfies your requirements?

**Comment by dhoard** [comment]
Adding code to allow attribute filtering by ObjectName and attribute name.
