### ISSUE TITLE
Add Metrics Filter to HTTP Server

### ISSUE THREAD

**Issue by alexgaganashvili** [prometheus/jmx_exporter#515]
Hi,

Could you add a capability to request specific metrics similar to this:
https://github.com/lightbend/kafka-lag-exporter#filtering-metrics-without-prometheus-server

Thanks,
Alex

**Comment by alexgaganashvili** [comment]
nm. This seems to be already supported. It's an "undocumented" feature:
https://prometheus.github.io/client_java/src-html/io/prometheus/client/exporter/HTTPServer.html#line.110

Thanks,
Alex

**Comment by alexgaganashvili** [comment]
It only supports default jvm metrics but not kafka ones.

**Comment by brian-brazil** [comment]
There's limitations in how this works, it's not going to usefully work with general JMX metrics.

**Comment by alexgaganashvili** [comment]
Can I make it work with Kafka metrics though? It would be useful not to have to discard over 300KB of returned data and keep only a small fraction of it.

**Comment by brian-brazil** [comment]
Kafka metrics are JMX metrics, so there's not much point. The expensive part of getting the data via JMX, not the Prometheus processing of them.

**Comment by alexgaganashvili** [comment]
Right, it was not quite clear what you meant by "general JMX metrics".
Should this ticket be closed at this point?

**Comment by brian-brazil** [comment]
Yes, this only works for direct instrumentation and certain custom collectors.
