### ISSUE TITLE
using blacklistObjectNames in config.yaml for ActiveMQ

### ISSUE THREAD

**Issue by GotGit20** [prometheus/jmx_exporter#516]
I have specified the below in the config.yaml. These metrics for these object names get really huge with time and is affecting the scrape time.

I was expecting these objects to not be queried, but I still find them on the scrape. Am I doing something wrong?

    blacklistObjectNames: [
    "org.apache.activemq.Broker.DestinationTopic:*",
    "org.apache.activemq.Broker.DestinationQueue:*",
    "org.apache.activemq.Broker.Active:*",
    "org.apache.activemq.Broker.SessionId:*",
    "org.apache.activemq.Broker.ActiveTransactionCount:*",
    "org.apache.activemq.Broker.DispatchQueueSize:*",
    "org.apache.activemq.Broker.Blocked:*",
    "org.apache.activemq.Broker.DispatchAsync:*",
    "org.apache.activemq.Broker.DestinationTemporary:*"
    ]

**Comment by brian-brazil** [comment]
Ca you share the relevant HELP from the scrape that indicates they're being scraped?

**Comment by GotGit20** [comment]
Below are a few of them


# HELP org_apache_activemq_Broker_DestinationTopic Subscription is on a Topic (org.apache.activemq<type=Broker, brokerName=Broker2, destinationType=Queue, destinationName=alipResponseQueue, endpoint=Consumer, clientId=ID_p01rap010.amerus.corp.tld-39584-1596851489611-0_1, consumerId=ID_p01rap010.amerus.corp.tld-39584-1596851489611-1_1_5_33><>DestinationTopic)
# HELP org_apache_activemq_Broker_DestinationQueue Subscription is on a Queue (org.apache.activemq<type=Broker, brokerName=Broker2, destinationType=Queue, destinationName=alipResponseQueue, endpoint=Consumer, clientId=ID_p01rap010.amerus.corp.tld-39584-1596851489611-0_1, consumerId=ID_p01rap010.amerus.corp.tld-39584-1596851489611-1_1_5_33><>DestinationQueue)
# HELP org_apache_activemq_Broker_ActiveTransactionCount The number of active transactions established on this Connection. (org.apache.activemq<type=Broker, brokerName=Broker2, connector=clientConnectors, connectorName=openwire, connectionViewType=remoteAddress

**Comment by GotGit20** [comment]
It worked on another JVM when I wanted to black list only one object type, when I specified the below.

blacklistObjectNames: ["com.accenture.alip.processserver:*"]


It looks like it has to do with specifying multiple objectnames to blacklist.

**Comment by brian-brazil** [comment]
You don't have the right object names, they must be exact matches. See the example config: https://github.com/prometheus/jmx_exporter/blob/master/example_configs/activemq.yml
