### ISSUE TITLE
Exports bad label names

### ISSUE THREAD

**Issue by bitplane** [prometheus/jmx_exporter#52]
Something in the MBean flattening code is causing the exporter to spit out invalid Prometheus label names. If I export everything from one of my nodes I get a row like this:
    org_apache_camel_camel_classname_Timeout{type="endpoints",name="\"some://endpoint",8_size="50000\"",} 30000.0

The "8_size" being an invalid label name in Prometheus as it starts with a number.

**Comment by brian-brazil** [comment]
Thanks for the report, can you share the mbean name per the HELP string?

**Comment by bitplane** [comment]
It looks like this in the output:

    # HELP org_apache_camel_camel_ourinternalname_Timeout Shutdown timeout (org.apache.camel<context=camel-ourinternalname, type=context, name="camel-ourinternalname"><>Timeout)
    # TYPE org_apache_camel_camel_ourinternalname_Timeout gauge

I couldn't find it in JConsole though

**Comment by brian-brazil** [comment]
If you can use a regex to get the jmx export just to export that metric and get the HELP string, that'd be useful. Then we can use it in a unittest.

**Comment by bitplane** [comment]
As per chat with Brian on IRC, it looks like it's due to the beanName containing delimiters:

    org.apache.camel:context=ourinternalname,type=endpoints,name="seda://endpointName\?concurrentConsumers=8&size=50000"

Which are parsed here:

https://github.com/prometheus/jmx_exporter/blob/master/collector/src/main/java/io/prometheus/jmx/JmxScraper.java#L150

    String[] tokens = beanName.substring(idx).split(",|=");

Need something like an ordered version of `getKeyPropertyList`
