### ISSUE TITLE
Secure Storing JMX Authentication Credentials 

### ISSUE THREAD

**Issue by ahmmub** [prometheus/jmx_exporter#536]
How can we secure the authentication credentials storing instead of having them in the config yaml file? 

(same for the ssl password keyStorePassword and trustStorePassword)

Suggestion: Support storing credentials in https://aws.amazon.com/secrets-manager/

**Comment by brian-brazil** [comment]
There's no plans to support any such things, ultimately we need access to the secret in plain text. How you choose to get that into the config file is up to you.

**Comment by ahmmub** [comment]
Any suggestions for a secret manager we can implement as **an option** to users who don't want their credentials to be in a plain text?

The point from proposing a cloud secret manager such as aws secret manager is to decouple the secret manager from the OS platform.

**Comment by brian-brazil** [comment]
As I've said, this is out of scope for this and other exporters. We don't want to be bound to the endless different approaches to this that are out there.

**Comment by ahmmub** [comment]
I'd expect that topic at least to be open for discussion and contribution by the opensource community.

Would you explain more why a legitimate security concern/requirement like that will be out scoped?
