### ISSUE TITLE
Http endpoint processes all requests regardless their path

### ISSUE THREAD

**Issue by qinghui-xu** [prometheus/jmx_exporter#539]
[Context]
We are trying to upgrade jmx exporter from 0.9.0 to 0.13.0, and we find that metrics endpoint of services with upgraded version are unresponsive from time to time.
[Analysis]
After digging more, we see that when there is some http scan with different urls (in our case it's just an internal security audit), 0.13.0 is processing all http requests regardless their path (such as `/admin`, `/login` or whatever). When we receive thousands of such requests at the same time, this becomes in fact a DOS attack by overloading the metrics endpoint for some amount of time (from minutes to hours), until jmx exporter finishes process all of them. Given that usually the jmx exporter needs seconds to scan all the mbeans when there are many, jmx exporter needs some significant time to process all those irrelevant http requests (they just need to be HTTP404).
[Root cause]
It seems this problem is due to the fact that now jmx exporter swtiches the http server implementation from jetty to the one provided by the jdk `com.sun.net.httpserver.HttpServer`. But this jdk implementation has some bug (or maybe it is a feature) to deal with the http requests with unknown paths, it just redirects all of them to the handler of the root path `/` instead of throwing a HTTP404 back to the client.
And as jmx exporter register the metric handler also to `/`, all irrelevant http requests are in fact processed by it.

**Comment by brian-brazil** [comment]
That's the way that particular endpoint works. I'd politely suggest not directing DOS attacks at production endpoints.

https://github.com/prometheus/client_java/issues/551 covers this.

**Comment by qinghui-xu** [comment]
I would like to agree with you on the DOS attacks, and it's important to protect the production environment.

But in this particular case, security audit is not carried out by myself, and it seems logical to audit the vulnerabilities of a prod env (well, I'm not expert on this subject but it makes sense to me)

From a user point of view, this is a regression comparing to 0.9 and may be considered as a vulnerability. IMHO, the fix should not cost too much for the community to maintain it. I could provide the PR if this will be accepted.

**Comment by ryan-lane** [comment]
@brian-brazil I think you're seeing this issue in reverse. The behavior in the code is a DoS vulnerability, that folks are pointing out. If a small scan from Nessus can overload services using this, than anything with access to the port will be able to easily overwhelm the service. I'd consider this CVE worthy.
