### ISSUE TITLE
Re: Secure Storing JMX Authentication Credentials

### ISSUE THREAD

**Issue by ahmmub** [prometheus/jmx_exporter#544]
For this issue: https://github.com/prometheus/jmx_exporter/issues/536

There is another proposal to allow securing the passwords (ssl and jmx) for the http-server based jmx exporter.

We can allow taking configurations overrides as java arguments: 

Example: 

```bash 
java -jar jmx_prometheus_httpserver-0.14.0-jar-with-dependencies.jar 5556 config.yml --configs-overrides '{"password"=<PASSWORD>, "ssl": "<SSL_PARAMETERS>"}'
```

That --configs-overrides is optional, and in this case we can allow retrieving secrets in the runtime from the bash script (however everyone wants) while starting the exporter.

**Comment by brian-brazil** [comment]
It is not safe to put passwords on the command line, they're far safer on a filesystem.

To be clear, the only interface that will be offered for secrets is to read them from the config file.

**Comment by ahmmub** [comment]
I'm not sure why you Brian consider it as "not safe", for example why the following is not secured: 

```bash
$PASSWORD = <GET_VALUE_FROM_A_SECRET_MANAGER>
$SSL_PARAMS = <GET_VALUE_FROM_A_SECRET_MANAGER>


java -jar jmx_prometheus_httpserver-0.14.0-jar-with-dependencies.jar 5556 config.yml --configs-overrides '{"password"=$PASSWORD, "ssl": "$SSL_PARAMS"}'
```

**Comment by brian-brazil** [comment]
This is not the place to discuss Unix security basics like not putting secrets on the command line. As I've already made clear, this feature will not be accepted on both security and configuration management grounds.
