### ISSUE TITLE
JmxScraper should not skip other type other than Number Boolean Date and String

### ISSUE THREAD

**Issue by qixiaobo** [prometheus/jmx_exporter#548]
As far I can see
https://github.com/prometheus/jmx_exporter/blob/master/collector/src/main/java/io/prometheus/jmx/JmxScraper.java#L196
I think we could use toString instead to just skip
![image](https://user-images.githubusercontent.com/2881751/96594720-8158ec80-131d-11eb-94b0-187d70c41db4.png)
![image](https://user-images.githubusercontent.com/2881751/96594755-8b7aeb00-131d-11eb-9c67-982f8df7b0a3.png)
If so I can just use some regex group to catch the value I need！

**Comment by brian-brazil** [comment]
What exact type is that that you are interested in? Hoping that arbitrary types contain a useful string representation where exactly one single value is of interest doesn't seem like a great strategy to me.

**Comment by qixiaobo** [comment]
> What exact type is that that you are interested in? Hoping that arbitrary types contain a useful string representation where exactly one single value is of interest doesn't seem like a great strategy to me.

A lot of jmx mbean may not return the type I say.
Just like LinkedHashMap because springboot may use DataEndpointMBean to return type like below
```java
public Object convert(Object data) {
		if (data == null) {
			return null;
		}
		if (data instanceof String) {
			return data;
		}
		if (data.getClass().isArray() || data instanceof List) {
			return this.objectMapper.convertValue(data, this.listObject);
		}
		return this.objectMapper.convertValue(data, this.mapStringObject);
	}
```
If toString is exectued ,I can use regex group to catch some value I need.
But this case I can only write another MBean to support jmx exporter

**Comment by qixiaobo** [comment]
That is to say  the collections should to be handled

**Comment by brian-brazil** [comment]
It's a big assumption that the string value of arbitrary types is going to be useful. If there's specific standard types that we're not currently handling let's talk about handling those, rather than throwing manipulation functions at the wall and hoping that something sticks.

**Comment by qixiaobo** [comment]
> It's a big assumption that the string value of arbitrary types is going to be useful. If there's specific standard types that we're not currently handling let's talk about handling those, rather than throwing manipulation functions at the wall and hoping that something sticks.

Agree with U. But in fact lots of mBean just return HashMap or List and so on. The complex object may also convert by ObjectMapper to a HashMap. So how to handle with this is a question. For me , an arbitrary string (may be json) is useful.
It's a  big assumption indeed.

**Comment by brian-brazil** [comment]
Thinking on it overnight, if you want to expose a Map the standard JMX way is to use TabularData. Accordingly I'd suggest changing whatever is currently exposing a Map to use TabularData instead so that it'll work with JMX tooling generally.

**Comment by qixiaobo** [comment]
> Thinking on it overnight, if you want to expose a Map the standard JMX way is to use TabularData. Accordingly I'd suggest changing whatever is currently exposing a Map to use TabularData instead so that it'll work with JMX tooling generally.

Cannot agree more! But in fact some project(like spring) , it exposes map indeed. I never doubt  about use TabularData is better.
How about considering such case?

**Comment by brian-brazil** [comment]
For anything non-standard like that we'd have to see how common it is, and if different systems do it differently. We'd also need to see how the attribute names would be handled, as a Map doesn't have one.

I don't think it's wise to add code to deal with one particular application that has chosen to go off the beaten path, rather it'd be better to fix that application.

**Comment by brian-brazil** [comment]
Also, the example you have posted contains nothing usable as a metric.

**Comment by qixiaobo** [comment]
> For anything non-standard like that we'd have to see how common it is, and if different systems do it differently. We'd also need to see how the attribute names would be handled, as a Map doesn't have one.
> 
> I don't think it's wise to add code to deal with one particular application that has chosen to go off the beaten path, rather it'd be better to fix that application.

Thanks for reply.
I would rather to add more code to adjust for jmx exporter.
But also I should say in java application, spring framework is the most common case~ 
https://github.com/spring-projects/spring-boot/blob/10a5cef4ef33e7c86d18e1f92793c2aaa57d5a82/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/jmx/DataConverter.java#L58

**Comment by brian-brazil** [comment]
Spring is still only one framework, it going off the beaten path does not define how JMX is intended to be used.

**Comment by qixiaobo** [comment]
> Spring is still only one framework, it going off the beaten path does not define how JMX is intended to be used.

Fine~ I will reconsider about this~
You're so nice to answer my question.
I may close this issue soon.
