### ISSUE TITLE
Mbean Collection fails if 1 bean is "unavailable"

### ISSUE THREAD

**Issue by reasland** [prometheus/jmx_exporter#550]
![image](https://user-images.githubusercontent.com/55564295/97244968-fa49bf80-17c7-11eb-8504-84c35d20dd13.png)

FINE: scrape: 'Catalina:type=ThreadPool,name="http-bio-9001"_[currentThreadsBusy, paused, truststoreType, keyAlias, socketProperties, useCometTimeout, currentThreadCount, trustManagerClassName, usePolling, keystorePass, maxThreads, trustMaxCertLength, truststoreAlgorithm, tcpNoDelay, algorithm, maxKeepAliveRequests, keepAliveTimeout, localPort, truststoreProvider, acceptorThreadCount, soTimeout, daemon, minSpareThreads, sessionCacheSize, acceptorThreadPriority, backlog, maxHeaderCount, port, keystoreType, name, soLinger, sslProtocol, sessionTimeout, useComet, clientAuth, modelerType, connectionCount, threadPriority, executorTerminationTimeoutMillis, running, allowUnsafeLegacyRenegotiation, sslEnabledProtocolsArray, ciphers, truststorePass, sSLEnabled, maxThreadsWithExecutor, crlFile, maxConnections, keystoreProvider, deferAccept, useSendfile, keyPass, bindOnInit, keystoreFile, truststoreFile, useServerCipherSuitesOrder]': Fail: java.rmi.UnmarshalException: error unmarshalling return; nested exception is: 
        java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: org.apache.tomcat.util.net.SocketProperties

There are multiple beans that can output a valid value, but since SockerProperties is invalid it will cause all beans to not write to log

**Comment by brian-brazil** [comment]
This is expected behaviour, as your application is throwing an exception when we ask it for JMX information. You'll need to fix this in your application.
