### ISSUE TITLE
Please add GPG public key info somewhere so artifact signature can be verified

### ISSUE THREAD

**Issue by rehevkor5** [prometheus/jmx_exporter#554]
See title.

It looks like the artifact is signed by E95EA6C2AD52A06CDE44C0F15007C2A4EA64F2BA which appears to be owned by https://keybase.io/bbrazil is that right? Can you add info to the README perhaps?

**Comment by brian-brazil** [comment]
There is a signature only because the central repository requires it in order to upload. If you're worried about the provinence of the binaries, I'd suggest building them yourself. See https://prometheus.io/docs/operating/security/#build-process
