### ISSUE TITLE
Add possibility to set path for logs

### ISSUE THREAD

**Issue by Kenzi007220** [prometheus/jmx_exporter#555]
Hi,
please add a feature to support path/name definition for start.log and start.error.log
Fe prometheus_jmx_exporter_log_file=/"some path"/prometheus_jmx_exporter_log_file.log

**Comment by brian-brazil** [comment]
This is coming from your application, and is nothing to do with the jmx exporter as it only uses the standard Java logging stuff. There's nothing we can do here, this is a usage question for your application.
