### ISSUE TITLE
Support aggregation of JMX metrics

### ISSUE THREAD

**Issue by weeco** [prometheus/jmx_exporter#561]
I often face the situation where the to be scraped JMX metrics are more granular than I need and therefore I'd like to aggregate. Example:

```yaml
  - pattern: kafka.network<type=RequestMetrics, name=ErrorsPerSec, request=(.+), error=(.+)><>Count
    name: "kafka_network_request_metrics_errors_per_sec"
    labels:
      request: $1
      error: $2
    type: COUNTER
```

Let's say I'm not interested in the specific error, but if I leave this label I don't think the JMX exporter will sum the occurances does it? I couldn't find a hint about this in the documentation.

**Comment by brian-brazil** [comment]
Aggregation is a matter to handle in Prometheus, each time series exposed by the jmx exporter should have a unique name and labels.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by weeco** [comment]
@brian-brazil I'm aware that Prometheus is capable of doing this, but if the Mbeans I export are thousands of metric serieses (for each pod) because of a label that I'm not interested in anyways I think it's a fair feature request that we aggregate on this before exposing this to Prometheus as handling millions of metric serieses is rather resource intensive in Prometheus.

So if I can get rid of these series right at exporting this would potentially save a lot of resources (not just for the ingestion but also when querying these data).

**Comment by brian-brazil** [comment]
This would require re-implementing a good chunk of Prometheus in the JMX exporter, I don't think it's wise for the JMX exporter to be anything beyond a simple proxy.

If you want less cardinality, I'd suggest changing your application to not expose things you don't need.

**Comment by weeco** [comment]
> This would require re-implementing a good chunk of Prometheus in the JMX exporter, I don't think it's wise for the JMX exporter to be anything beyond a simple proxy.

I understand that argument.

> If you want less cardinality, I'd suggest changing your application to not expose things you don't need.

If I were in control I wouldn't use JMX at all 🥇 . I can't change that and I highly doubt that this is going to happen in Kafka either as others might be interested in this detailed information.

**Comment by brian-brazil** [comment]
You can always request that they expose it both ways. If it really is thousands of series per target, that already is something that should probably be available in a coarser way - jmx isn't the most efficient after all.
