### ISSUE TITLE
How do I merge multiple labels into one metric

### ISSUE THREAD

**Issue by lifeiqiang** [prometheus/jmx_exporter#574]
config:
  - jobname: 
    startDelaySeconds: 0
    hostPort: 
    socket: 
    username:
    password:
    ssl: false
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    whitelistObjectNames:
      - "java.lang:type=Runtime"
    rules:
    - pattern: 'java.lang<type=Runtime><>BootClassPath: (\/\w+\/[a-zA-Z0-9._]+)|ClassPath: (\/\w+\/\w+\/[a-zA-Z0-9_]+)|VmName: (.*)'
      name: jvm_info
      value: "1.0"
      labels:
        jdkdir: $1
        tomdir: $2
        VmName: $3
      type: GAUGE

like this:
jvm_info{tomdir="/app/tomcat/tomcat8_test_9080",} 1.0
jvm_info{vmname="Java HotSpot(TM) 64-Bit Server VM",} 1.0
jvm_info{jdkdir="/opt/jdk1.8.0_181",} 1.0

merge to:

jvm_info{tomdir="/app/tomcat/tomcat8_test_9080",vmname="Java HotSpot(TM) 64-Bit Server VM",jdkdir="/opt/jdk1.8.0_181"} 1.0

**Comment by brian-brazil** [comment]
This is not possible, you always get one series per mBean. Also, jvm_info is already exposed out of the box.

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
