### ISSUE TITLE
JMX Prometheus Exporter not loading on HBSE Master node. Error: Could not find or load main class

### ISSUE THREAD

**Issue by SantoshT78** [prometheus/jmx_exporter#578]
I am setting up JMX Prometheus Exporter on HBase Master node. Referring to an article at < https://godatadriven.com/blog/monitoring-hbase-with-prometheus/> I have added following entry in hbase-env.sh file.

location: /opt/hbase/hbase/conf/hbase-env.sh

export HBASE_OPTS="$HBASE_OPTS javaagent:/opt/hbase/jmx-exporter/jmx_prometheus_javaagent-0.15.0.jar=8095:/opt/hbase/jmx-exporter/jmx-config.yaml"

Java home directory:

export JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-2.el7_8.ppc64le/"

JMX exporter and yaml file are in this folder - /opt/hbase/jmx-exporter

yaml file contain only a general rule:

rules:

pattern: ".*"
when I run start-hbase.sh, I am getting following error. What could be the problem?

Error: Could not find or load main class javaagent:.opt.hbase.jmx-exporter.jmx_prometheus_javaagent-0.15.0.jar=8095:.opt.hbase.jmx-exporter.jmx-config.yaml

Without jmx exporter entries in hbase-sh, hbase master node works fine and metrics dumps is also available on web url masterserver:port/jmx. Metrics about JRE,

{
    "name" : "java.lang:type=Runtime",
    "modelerType" : "sun.management.RuntimeImpl",
    "StartTime" : 1612180735317,
    "SpecName" : "Java Virtual Machine Specification",
    "SpecVendor" : "Oracle Corporation",
    "SpecVersion" : "1.8",
    "ManagementSpecVersion" : "1.2",
    "InputArguments" : [ "-Dproc_master", "-XX:OnOutOfMemoryError=kill -9 %p", "-Xmx8G", "-XX:MaxDirectMemorySize=8G", "-XX:+UseConcMarkSweepGC", "-XX:G1HeapRegionSize=32m", "-Dcom.sun.management.jmxremote", "-Dcom.sun.management.jmxremote.ssl=false", "-Dcom.sun.management.jmxremote.password.file=/opt/hbase/hbase/conf/jmxremote.passwd", "-Dcom.sun.management.jmxremote.access.file=/opt/hbase/hbase/conf/jmxremote.access", "-Dcom.sun.management.jmxremote.port=8093", "-Dhbase.log.dir=/opt/hbase/hbase/logs", "-Dhbase.log.file=hbase-hadoop-master-HBASEM1-DEV-S1.dev.com.log", "-Dhbase.home.dir=/opt/hbase/hbase", "-Dhbase.id.str=hadoop", "-Dhbase.root.logger=INFO,RFA", "-Djava.library.path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-2.el7_8.ppc64le//lib:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-2.el7_8.ppc64le//jre/lib:/opt/hadoop/hadoop/lib/native", "-Dhbase.security.logger=INFO,RFAS" ],

**Comment by tomwilkie** [comment]
Hi @SantoshT78!

This question is mostly beyond the scope of issues in this repo, and is best asked in the mailing list:  https://groups.google.com/g/prometheus-users

In this case, it looks like you missed a hyphen:
> `export HBASE_OPTS="$HBASE_OPTS javaagent:/opt/hbase/jmx-exporter/jmx_prometheus_javaagent-0.15.0.jar=8095:/opt/hbase/jmx-exporter/jmx-config.yaml"`

`export HBASE_OPTS="$HBASE_OPTS -javaagent:/opt/hbase/jmx-exporter/jmx_prometheus_javaagent-0.15.0.jar=8095:/opt/hbase/jmx-exporter/jmx-config.yaml"`
