### ISSUE TITLE
I am not a developer, how to use it?

### ISSUE THREAD

**Issue by Shark-SRookie** [prometheus/jmx_exporter#579]
- Use 'run_sample_httpserver.sh' can not start any process. 
- The current version is 0.15.0, why is 0.15.1 written in pom.xml?
- Where can I download jmx_prometheus_httpserver-0.15.1-SNAPSHOT-jar-with-dependencies.jar?
- I try 'java -jar jmx_prometheus_httpserver-0.15.0.jar' it show no main manifest attribute, in jmx_prometheus_httpserver-0.15.0.jar.

- Only be used in this way? 'java -javaagent:./jmx_prometheus_javaagent-0.15.0.jar=8080:config.yaml -jar yourJar.jar'

**Comment by tomwilkie** [comment]
Hi @Shark-SRookie! Questions like this are best asked on the mailing list I'm afraid: https://groups.google.com/g/prometheus-users.
