### ISSUE TITLE
Support multiple jvms

### ISSUE THREAD

**Issue by jackhopner** [prometheus/jmx_exporter#58]
To reduce the overhead of exporting JVM metrics it would be good to be able to run one jmx_prometheus_httpserver for multiple JVM's.

Requirements:

1. You can have one instance of the jmx_prometheus_httpserver which would collect and provide metrics for multiple JVM's
2. Either one config file per jvm or one file containing config for multiple jvms. The configuration would need to reload if it was changed, to support jvms being brought up and down.
3. The # HELP and # TYPE would need some sort of unique identifier per jvm appended to the metric name.
4. The jmx scrape duration and error metric would need an unique identifier appended to it.

**Comment by brian-brazil** [comment]
This is an explicit non-goal of this exporter, it is strongly recommended to run one agent per JVM.

> You can have one instance of the jmx_prometheus_httpserver which would collect and provide metrics for multiple JVM's

This is mixing your failure domains. It's easier to manage one per JVM.

> The configuration would need to reload if it was changed, to support jvms being brought up and down.

You should use service discovery at the Prometheus level to handle this.

> The # HELP and # TYPE would need some sort of unique identifier per jvm appended to the metric name.

They wouldn't, there should only be one of these per metric and having different values can cause problems.

**Comment by Bigsmooth68** [comment]
Hi @jackhopner 
Did you tested this successfuly?
BigSmooth
