### ISSUE TITLE
attrNameSnakeCase makes pattern matching unintuitive for attributes containing dots

### ISSUE THREAD

**Issue by Navgeet** [prometheus/jmx_exporter#582]
I've found this to be extremely unintuitive. For eg: attribute name `OutputDataSize.OneMinute.Rate` converts to `output_data_size._one_minute._rate` which doesn't make sense. It should convert to either `output_data_size.one_minute.rate` or `output_data_size_one_minute_rate`. Also when I capture the `._` and output it in metric name, it outputs to `_`, so to discover this anomaly I had to copy the `toSnakeAndLowerCase` method from code and run it in a sample java project.

It would be great if we can fix this, but it would be breaking change.

**Comment by dhoard** [comment]
Introducing just a breaking change would cause extreme technical friction for existing users.
