### ISSUE TITLE
jmx_exporter as an agent on Windows

### ISSUE THREAD

**Issue by kavyakul** [prometheus/jmx_exporter#59]
Hi,
I am running jmx_exporter on windows & it gives me following error:
Usage: -javaagent:/path/to/JavaAgent.jar=<port>:<yaml configuration file>

/path/to/JavaAgent.jar -> is an absolute path in my case, since its on windows, it has colons.
yaml configuration file -> again, its also an absolute path, hence has colons.

Probably, because the code is written in a way that is splits arguments based on ":", I am getting this fore said error.
Please let me know if there is a workaround for running JMX agent jar on windows.

**Comment by brian-brazil** [comment]
Can you use relative paths?

**Comment by kavyakul** [comment]
i have to run jar as a service(using nssm), so relative path would be last thing to try.

**Comment by jmlucjav** [comment]
I can use absolute paths in windows, watch out the slash/bakslashes...

`-javaagent:c:\prometheus\jmx_exporter-parent-0.6\jmx_prometheus_javaagent\target\jmx_prometheus_javaagent-0.6.jar=9011:src/main/resources/prometheus-jmx.yml -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1`

I am having other issues, but the paths do work.

**Comment by kavyakul** [comment]
Thanks, I will try out this now.

**Comment by kavyakul** [comment]
Can I get Jvm version (java.lang.Runtime) form JMX-exporter metrics. I have not set any pattern but still I am getting only java_lang_Runtime Start & Uptime.

# HELP java_lang_Runtime_StartTime StartTime (java.lang<type=Runtime><>StartTime)
# TYPE java_lang_Runtime_StartTime gauge
java_lang_Runtime_StartTime 1.455174377204E12

# HELP java_lang_Runtime_Uptime Uptime (java.lang<type=Runtime><>Uptime)
# TYPE java_lang_Runtime_Uptime gauge
java_lang_Runtime_Uptime 54458.0

**Comment by brian-brazil** [comment]
That's not exposed currently and the current jmx exporter doesn't do strings. This would be something to add to simpleclient_hotspot.

**Comment by kavyakul** [comment]
ok..thanks for the information!

**Comment by captaingoodguy** [comment]
@kavyakul can you show your prometheus-jmx.yml ? thank you very much!

**Comment by bc-dhandapani** [comment]
java -javaagent:../../common/rd/jmx_prometheus_javaagent-0.12.0.jar=localhost:8080:config.yaml
Usage: -javaagent:/path/to/JavaAgent.jar=[host:]<port>:<yaml configuration file>

I am getting usage error. How to resolve it

**Comment by safvankothawala** [comment]
java -javaagent:jmx_prometheus_javaagent-0.12.0.jar=8080:config.yaml -jar EmployeeService-0.0.1-SNAPSHOT.jar

Error:
Usage: -javaagent:/path/to/JavaAgent.jar=[host:]<port>:<yaml configuration file>

Kindly Help !!
