### ISSUE TITLE
Kafka HDFS connector problems

### ISSUE THREAD

**Issue by NoFWayMan** [prometheus/jmx_exporter#593]
Hi! I'm trying to use jmx_exporter to have some metrics about Kafka HDFS connector usage.
I have 3 hosts cluster with Kafka HDFS connector on them.
When i use _-javaagent:/usr/share/java/jmx_prometheus_javaagent-0.15.0.jar=9333:/usr/share/java/config.yml_ as JAVA_OPTS on node-01 — everythin is fine, Prometheus getting metrics, Grafana shows me a perfect picture.
But, when i ad same JAVA_OPTS parameter on another host (node-02) — HDFS connector is failing with error
Here is hdfs-connector.log output

`Mar 23 08:55:10 bdp-edge-3 hdfs-connector: Exception in thread "main" java.lang.reflect.InvocationTargetException
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: at java.lang.reflect.Method.invoke(Method.java:498)
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: Caused by: java.io.FileNotFoundException: /usr/share/java/config.yml (No such file or directory)
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: at java.io.FileInputStream.open0(Native Method)
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: at java.io.FileInputStream.open(FileInputStream.java:195)
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: at java.io.FileInputStream.<init>(FileInputStream.java:138)
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: at java.io.FileReader.<init>(FileReader.java:72)
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:78)
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:29)
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: ... 6 more
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: FATAL ERROR in native method: processing of -javaagent failed
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: Usage:
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: kill [options] <pid|name> [...]
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: Options:
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: -a, --all              do not restrict the name-to-pid conversion to processes
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: with the same uid as the present process
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: -s, --signal <sig>     send specified signal
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: -q, --queue <sig>      use sigqueue(2) rather than kill(2)
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: -p, --pid              print pids without signaling them
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: -l, --list [=<signal>] list signal names, or convert one to a name
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: -L, --table            list signal names and numbers
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: -h, --help     display this help and exit
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: -V, --version  output version information and exit
Mar 23 08:55:10 bdp-edge-3 hdfs-connector: For more details see kill(1).`

I tried to use another ports — did'nt helped. 
Maybe it's HDFS connector problems, i'm not sure.

**Comment by NoFWayMan** [comment]
No, i placed it at all 3 nodes, at the same path

**Comment by dhoard** [comment]
@NoFWayMan per @fstab comment, this appears to be a configuration issue.

Have you resolved this issue?

If there are no updates within 1 week, this will be closed as inactive.
