### ISSUE TITLE
JMX Exporter for cassandra reporting incorrect datacenter 

### ISSUE THREAD

**Issue by docast** [prometheus/jmx_exporter#596]
I am using cassandra 2.1.13 and monitoring cassandra using the latest jmx exporter (0.15.0) with the default JMX exporter yml config [no MBeans blacklisted, all MBeans are allowed]. 

The cassandra cluster name I have setup is "testcluster". However, the jmx exporter is always returning data_center label as "dc1". Also, cluster label is not getting outputted. 

Any thoughts on why the exporter is reporting "dc1" as data_center and why "cluster" label is not outputted.  I have tested with latest version of cassandra as well [3.11.10], however see the same issue. 

Openjdk version used is "1.8.0_275"

**Comment by fstab** [comment]
The first step to narrow this down is to figure out whether the value `dc1` comes from Cassandra itself, or if it is some configuration in `jmx_exporter`. One way to find this out is to connect `jconsole` to the Java process and check on the MBean tab what values the JMX bean actually contains.

**Comment by docast** [comment]
Thanks for the inputs. 

From jconsole, I am successfully able to retrieve the right datacenter" name and the cluster name.  When I use jmx_exporter (latest version) with Prometheus, I am seeing datacenter returned as "dc1" and clustername field is coming blank.

**Comment by docast** [comment]
Hi, wanted to check if you have any input on this. 

When we use jmx exporter for cassandra for prometheus: we dont see "data center" and "cluster" getting outputted as part of metric collection. I am able to successfully collect the metrics through JMX exporter, however, datacenter and cluster name is not getting outputed as part of metric collection. 
with Jconsole, I can query the cluster name and datacenter successfully. 

I have ensured that none of the Mbeans are blacklisted. 

lowercaseOutputLabelNames: true
lowercaseOutputName: true
# whitelistObjectNames: ["org.apache.cassandra.metrics:*"]
# ColumnFamily is an alias for Table metrics
# blacklistObjectNames: ["org.apache.cassandra.metrics:type=ColumnFamily,*"]

**Comment by docast** [comment]
closing this as the initial issue for which the thread was opened is addressed. 
Opened a new issue for the current issue encountering:https://github.com/prometheus/jmx_exporter/issues/600
