### ISSUE TITLE
JMX exporter for cassandra telemetry capture doesnt ouput datacenter and cluster details.

### ISSUE THREAD

**Issue by docast** [prometheus/jmx_exporter#600]
Hi Experts, 

I am using jmx exporter (14.0) for metric capture of cassandra into Prometheus: 

I am able to successfully collect the metrics through JMX exporter, however, datacenter and cluster name is not getting outputted as part of metric collection. 
with Jconsole, I can query the cluster name and datacenter successfully.

I have ensured that none of the Mbeans are blacklisted.

     lowercaseOutputLabelNames: true
     lowercaseOutputName: true
    # whitelistObjectNames: ["org.apache.cassandra.metrics:*"]
    # ColumnFamily is an alias for Table metrics
    # blacklistObjectNames: ["org.apache.cassandra.metrics:type=ColumnFamily,*"]

Can you please help me understand why datacenter and cluster name details are not outputted as labels in the metrics collected.  datacenter and cluster details as label is important to understand the right cluster name and datacenter as we are managing multiple cassandra clusters and building dashboards accordingly.

**Comment by fstab** [comment]
I didn't find the time to look into this yet. Is there any chance you can reproduce this by extending the `CassandraMetrics` in `JmxCollectorTest`?
