### ISSUE TITLE
How-to export JMX operation as a JMX attribute?

### ISSUE THREAD

**Issue by wsliwinski** [prometheus/jmx_exporter#614]
Hi,

We are using `jmx_exporter` to export ActiveMQ broker JMX metrics to Prometheus. However, we have experienced recently occasional JVM deadlocks in ActiveMQ, and therefore we would like to export the JMX operation `ThreadMXBean#findDeadlockedThreads()` as JMX attribute to be able to scrape it and put an alert.

Is it possible for `jmx_exporter` to call a JMX operation as expose the result as a JMX attribute?

Regards,
Wojtek

**Comment by LajosCseppento** [comment]
Maybe it could be part of `io.prometheus.jmx:collector` (our projects use directly that with Spring Boot)

**Comment by wsliwinski** [comment]
I've just discovered, that the `jmx_exporter` exoposes already:
```
# HELP jvm_threads_deadlocked Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers
# TYPE jvm_threads_deadlocked gauge
jvm_threads_deadlocked 0.0
# HELP jvm_threads_deadlocked_monitor Cycles of JVM-threads that are in deadlock waiting to acquire object monitors
# TYPE jvm_threads_deadlocked_monitor gauge
jvm_threads_deadlocked_monitor 0.0
```
So this probably solves my original problem, but the question is still valid.

**Comment by fstab** [comment]
To answer your general question: `jmx_exporter` only reads attributes, it does not call operations. The `jvm_threads_deadlocked` you see is coming from `client_java`'s `DefaultExports`, which is included in `jmx_exporter`. You find the implementation here https://github.com/prometheus/client_java/blob/b178c5e1879e8d3d3c6e50ede8968340ba9f2488/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/DefaultExports.java

**Comment by wsliwinski** [comment]
Thanks for the info.
