### ISSUE TITLE
Can I run jmx-exporter with  gradle.build ? 

### ISSUE THREAD

**Issue by shdvgj** [prometheus/jmx_exporter#624]
I add jmx-exporter in gradle.build , like this 
`applicationDefaultJvmArgs = ["-javaagent:\$APP_HOME/jmx_prometheus_javaagent-0.16.1.jar"]`

but it's not working , so is there any possible to run jmx-exporter with gradle.build ?

**Comment by ybbiubiubiu** [comment]
I hava same questions...

**Comment by dhoard** [comment]
The arguments look incorrect: Example of a complete argument value:

```
-javaagent:\$APP_HOME/jmx_prometheus_javaagent-0.18.0.jar=12345:\$APP_HOME/config.yaml
```

... where `jmx_prometheus_javaagent-0.18.0.jar` and `config.yaml` are located in `$APP_HOME`

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
