### ISSUE TITLE
Not currently exposed to Prometheus: org.apache.cassandra.net.FailureDetetector > DownEndpointCount

### ISSUE THREAD

**Issue by rachlenko** [prometheus/jmx_exporter#63]
Hi, 
I am trying to  track both the down count and which nodes are being marked as down.
Is it possible to expose it?

thanks.
Ev.

**Comment by brian-brazil** [comment]
You want the `up` metric, which will be 0 for any nodes that Prometheus can't scrape.

**Comment by rachlenko** [comment]
Thank you, Brian.
I got it. 
Could you tell me how Prometheus export the GC metrics?

**Comment by brian-brazil** [comment]
If you're using it as a agent you'll get the GC metrics automatically.

**Comment by rachlenko** [comment]
Unfortunately, I run it as separated process. 
Thank you, Brian.  It looks like a good answer to run exporter as an agent .

**Comment by brian-brazil** [comment]
It's generally recommended to run it as an agent. It's easy to manage, and gets you better stats.

**Comment by rachlenko** [comment]
thank you Brian.
