### ISSUE TITLE
Cassandra metric on https

### ISSUE THREAD

**Issue by MGulerce** [prometheus/jmx_exporter#630]
Hello,
I'm new to jmx-exporter.I setup the jar with standalone and agent .Works fine each way.But metric can read on http://IP:7070
But I cant add ssl encryption.I dont know if it's possible to do.
If it's possible how can ı do that?

Thanks for helping.

**Comment by tashian** [comment]
Sure, as far as I can tell this project doesn't support TLS. My suggestion would be to have the jmx exporter bind to localhost, and then run a reverse proxy in front of it (eg. Caddy or Traefik) that adds TLS server authentication. See https://caddyserver.com/docs/caddyfile/directives/reverse_proxy for more.

**Comment by fstab** [comment]
@dhoard started working on it https://github.com/prometheus/client_java/pull/686

**Comment by dhoard** [comment]
@MGulerce as @fstab has pointed out, I am in the process of adding cleaner SSL support into `client_java`

Issue -> https://github.com/prometheus/client_java/issues/693
PR -> https://github.com/prometheus/client_java/pull/695

If / when `client_java` is released with these changes, exporters can then be modified to support SSL and BASIC authentication.

In the short term, @tashian 's suggestion is the current approach.

**Comment by MGulerce** [comment]
Thank you,
We use our system as @tashian  said , But It would be great to add SSL support on client_java .
So I reaopened the ıssue

**Comment by dhoard** [comment]
As pointed out by @tashian this a dupe of https://github.com/prometheus/jmx_exporter/issues/442

I propose we close this issue and track SSL/TLS support in that issue.

**Comment by MGulerce** [comment]
Okey than
Thanks again
