### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by choudhary1996** [prometheus/jmx_exporter#632]
Hi,
I am using 
**Linux:** : Ubuntu 20.04.2 LTS
**Webserver** : Apache Tomcat 8.5.7 [ manual installation path: /opt/tomcat and port is default 8080]
**JAVA** : openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
All port allowed for now
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Can you suggest me how to configure this on server because i have ready checked all steps.
First i download this: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.16.1/jmx_prometheus_javaagent-0.16.1.jar
then execute: java -javaagent:./jmx_prometheus_javaagent-0.16.1.jar=8081:config.yaml -jar yourJar.jar
what is **yourJar.jar** 
if you  can suggest steps that will be great help

**Comment by dhoard** [comment]
`yourJar.jar` is the runnable jar containing your application.

Example:

I build and package Java HelloWorld application. The final jar name is `helloworld.jar` and runnable via `java -jar helloworld.jar`

To run the application with the `jmx_exporter`, I would run...

```
 java -javaagent:./jmx_prometheus_javaagent-0.16.1.jar=8081:config.yaml -jar helloworld.jar
```

... where `8081` is the `jmx_exporter` HTTP metrics endpoint and `config.yaml` is the `jmx_exporter` configuration file.

**Comment by choudhary1996** [comment]
Thanks for support
