### ISSUE TITLE
User and password as env variables

### ISSUE THREAD

**Issue by daviddetorres** [prometheus/jmx_exporter#636]
Would it be interesting to implement the configuration of user and password as environmental variables? 

This would help to secure the exporter in case of JMX under authentication.

**Comment by dhoard** [comment]
Can you elaborate on why you feel this would be more secure?

**Comment by daviddetorres** [comment]
In Kubernetes environments, it is a good practice to separate configuration in ConfigMap objects and authentication and credentials in Secrets. 

Being able to pass authentication through environmental variables to the JMX exporter can allow the creation of configurable generic ConfigMaps and custom authentication Secrets for different pods or workloads. 

If this is interesting, we can implement the feature.

**Comment by dhoard** [comment]
@daviddetorres I agree that storing authentication secrets in the `config.yaml` is not ideal for K8s.

For K8s, I feel a cleaner solution would be to use an init container and shared volume to inject configuration/secrets. (i.e. build the `config.yaml` in the init container.)

This would allow any value in the `config.yaml` to be externalized using environment variables. This would also support using a third-party secret provider/agent.

(I'm not a maintainer)

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
