### ISSUE TITLE
can JMX exporter provide http server request statistics?

### ISSUE THREAD

**Issue by ponson-thankavel** [prometheus/jmx_exporter#638]
Hello Experts,

We are using jmx exporter to export JVM stats for our java application. We recently had a requirement to collect http server request statistics and setup some alert on that. However, it seems like jmx exporter don't provide http server request statistics. We noticed that micrometer provides this out of the box. We want to ensure that this is not possible with jmx exporter before switching. Can anyone please help confirming this?

I posted this to prometheus users group in google groups but didn't get any response

https://groups.google.com/g/prometheus-users/c/xrP4ktdap9I

**Comment by dhoard** [comment]
@ponson-thankavel Please provide specifics. Is this a Java HTTP server? Are you using SpringBoot? Are you creating/registering custom MBeans? etc.

**Comment by qixiaobo** [comment]
I think we should register mbean to support this.
```xml
 <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-jmx</artifactId>
            <version>${micrometer.version}</version>
        </dependency>
```
This may help you

**Comment by fstab** [comment]
Micrometer can export metrics for Prometheus directly, using Micrometer's Prometheus registry.

There is no need to convert the metrics to JMX and use the `jmx_exporter`.

**Comment by qixiaobo** [comment]
> Micrometer can export metrics for Prometheus directly, using Micrometer's Prometheus registry.
> 
> There is no need to convert the metrics to JMX and use the `jmx_exporter`.

You're right. But some case like below:
We may already use jmx_exporter and do auto-discovery

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
