### ISSUE TITLE
Attaching prometheus to javaagent leads to Logger errors

### ISSUE THREAD

**Issue by Anshuamrita** [prometheus/jmx_exporter#641]
I attached prometheus javaagent to Jboss 
JAVA_OPTS="$JAVA_OPTS -javaagent:<full_path>/jmx_prometheus_javaagent.jar=8686<config yaml>/jmx_exporter.yaml"

This starts giving LogManager execption. Then I passed options to JVM to set and configure LogManager as below:
JAVA_OPTS="$JAVA_OPTS -Dlogging.configuration=file:<full_path>/logging.properties -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dorg.jboss.logging
 .Logger.pluginClass=org.jboss.logging.logmanager.LoggerPluginImpl -Dlog4j.defaultInitOverride=true 
 and post this I am attaching javaagent. Previous errors are gone but now new error is observed:
 
__ Unable to set property fileName on class org.jboss.logmanager.handlers.SizeRotatingFileHandler: java.lang.reflect.InvocationTargetException
13:01:04.114 nnm-core> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:01:04.114 nnm-core> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:01:04.114 nnm-core> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:01:04.114 nnm-core> at java.lang.reflect.Method.invoke(Method.java:498)
13:01:04.115 nnm-core> at org.jboss.logmanager.PropertyConfigurator.configureProperties(PropertyConfigurator.java:187)
13:01:04.115 nnm-core> at org.jboss.logmanager.PropertyConfigurator.configureHandler(PropertyConfigurator.java:312)
13:01:04.115 nnm-core> at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:128)
13:01:04.115 nnm-core> at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:86)
13:01:04.115 nnm-core> at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:246)
13:01:04.115 nnm-core> at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:231)
13:01:04.115 nnm-core> at java.util.logging.LogManager$3.run(LogManager.java:399)
13:01:04.115 nnm-core> at java.util.logging.LogManager$3.run(LogManager.java:396)
13:01:04.115 nnm-core> at java.security.AccessController.doPrivileged(Native Method)
13:01:04.115 nnm-core> at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
13:01:04.115 nnm-core> at java.util.logging.LogManager.access$800(LogManager.java:145)
13:01:04.116 nnm-core> at java.util.logging.LogManager$2.run(LogManager.java:345)
13:01:04.116 nnm-core> at java.security.AccessController.doPrivileged(Native Method)
13:01:04.116 nnm-core> at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
13:01:04.116 nnm-core> at java.util.logging.LogManager.getLogManager(LogManager.java:378)
13:01:04.116 nnm-core> at java.util.logging.Logger.demandLogger(Logger.java:448)
13:01:04.116 nnm-core> at java.util.logging.Logger.getLogger(Logger.java:502)
13:01:04.116 nnm-core> at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<clinit>(JmxCollector.java:39)
13:01:04.116 nnm-core> at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:29)
13:01:04.116 nnm-core> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:01:04.116 nnm-core> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:01:04.116 nnm-core> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:01:04.117 nnm-core> at java.lang.reflect.Method.invoke(Method.java:498)
13:01:04.117 nnm-core> at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
13:01:04.117 nnm-core> at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
13:01:04.117 nnm-core> Caused by: java.io.FileNotFoundException: ${jboss.boot.server.log.dir}/boot.log (No such file or directory)
_

Application logs are getting created but boot.log is not getting created.
Can anyone help here the right way to configure log and javaagent. So that it works properly. Probably here boot.log is looked upon by javaagent before logManager sets it up and initialization happens. We are using Java8 and prometheus javaagent version:  0.16.1

**Comment by fstab** [comment]
The configuration in Grafana says how often it pulls data from the Prometheus server, the configuration in Prometheus says how often it scrapes data from the exporter. A scrape interval of 5s seems a bit much, I would assume that a higher value like 60s is sufficient.

**Comment by fstab** [comment]
This means that another process is also trying to use port `8686` on the same host.

**Comment by ndimitry** [comment]
I would suggest a small enhancement [to the earlier answer](https://github.com/prometheus/jmx_exporter/issues/641#issuecomment-946065386) which might help to stop searching for a new logger lib after each update:
```
export JAVA_OPTS="${JAVA_OPTS} -Xbootclasspath/a:$(ls $WILDFLY_DIR/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-*.jar):$(ls $WILDFLY_DIR/modules/system/layers/base/org/wildfly/common/main/wildfly-common-*.jar)"
```

**Comment by dhoard** [comment]
@Anshuamrita

Have you resolved this issue?

If there are no updates within 1 week, this will be closed as inactive.

**Comment by ndimitry** [comment]
Just for information which may help a lot.

Now WildFly and JBoss implemented a special way to attach java agents. Use this way:

```sh
export MODULE_OPTS=-javaagent:/artifacts/jmx_prometheus_javaagent-0.XX.X.jar=<port>:/artifacts/config.yml
```
Or set the very same property (variable) in the end of the Wildfly/JBoss setup script (something like standalone.sh, etc.).

Starting from one of the Wilfdly/JBoss versions (I don't remember which, maybe even WF22 or 24) they fixed a related issue with logger.
Now if an agent is attached WF loads its main libraries also as agents. This leads to the logger being available on the start up and there is no need for these crazy solutions (i.e. manually attaching libraries).
