### ISSUE TITLE
Request for comment: In-process JMX -> Prometheus Bridge Mode.

### ISSUE THREAD

**Issue by kazuki-ma** [prometheus/jmx_exporter#644]
Background
====
Recently we deploy spring boot application by single jar fashion.
And we keep runtime environment simple or just a container runs single jar.

In such situation, we don't want start side car daemon.
It is also difficult to add a jar as a file and add complex settings to the JVM startup options.

Proposal
====

Create new deployment time like `spring-boot-starter-jmx-exporter`

User can expose jmx dependency by following way.

1. Adding this jar to their dependency. (Auto configuration started)
2. Add configuration to `application.yml`.

How do you think.
If it's looks good, I want to contribute it.

**Comment by dhoard** [comment]
`spring-boot-starter-jmx-exporter` sounds more suited as a Spring project.

How would this be implemented in the exporter without any dependencies on Spring?

**Comment by kazuki-ma** [comment]
@dhoard 

Thank you for your kind reply and sorry for my late response.

> spring-boot-starter-jmx-exporter sounds more suited as a Spring project.
>  How would this be implemented in the exporter without any dependencies on Spring?

Sounds nice, let me check it. Thank you for your answer.
