### ISSUE TITLE
How to get the real pod name on the k8s platform?

### ISSUE THREAD

**Issue by zhu733756** [prometheus/jmx_exporter#646]
Hey, friends! I have a question to ask you. Thanks in advance. 

As I query the metric like `JVM_INFO`,  the prometheus server returns as follows:

<img width="476" alt="17142dabb8e28c9a4ba6db07cf924ac" src="https://user-images.githubusercontent.com/38685176/139180894-c19bdaeb-eda9-4004-8ba2-0f0c571b2cfe.png">

Actually, the pod name here is the name of the exporter, how can get the real pod name?

**Comment by vabinav** [comment]
Is it possible to get the pod-ip as well?

**Comment by zhu733756** [comment]
> Is it possible to get the pod-ip as well?

Cannot. The picture has shown all the metrics that returns from the exporter. However, it seems to be useless. We need the actual pod name or pod IP, namespaces, etc. Not the exporters.

**Comment by fstab** [comment]
I think this is the wrong place for these questions. The `jmx_exporter` is a simple tool that reads numbers from JMX and exposes them to Prometheus. There is no code in `jmx_exporter` that does anything with Kubernetes Pods, IPs, or Namespaces.

If the info you are looking for is available in a JMX bean, `jmx_exporter` can be used to expose it to Prometheus. However, I understand that you are looking for information that's not provided by JMX, but for meta data that might be added by Promtheus' service discovery. You might get better answers by sending your question to the Prometheus Users Google group.

**Comment by zhu733756** [comment]
> I think this is the wrong place for these questions. The `jmx_exporter` is a simple tool that reads numbers from JMX and exposes them to Prometheus. There is no code in `jmx_exporter` that does anything with Kubernetes Pods, IPs, or Namespaces.
> 
> If the info you are looking for is available in a JMX bean, `jmx_exporter` can be used to expose it to Prometheus. However, I understand that you are looking for information that's not provided by JMX, but for meta data that might be added by Promtheus' service discovery. You might get better answers by sending your question to the Prometheus Users Google group.

Thank you for your reply and correcting the questions. I will try it your way. I see other exporters have these metrics by supporting `exposed_X = "<real data>" ` metrics like [dcgm-exporter](https://github.com/NVIDIA/dcgm-exporter). Will we integrate this solution in the future?

**Comment by fstab** [comment]
I don't know the `dcgm-exporter` and its `exposed_X` metrics, but if this is something that makes sense for Java applications running on Kubernetes I am happy to accept a PR. However, I myself have no plans to implement this. I will focus on the core functionality, which is exposing JMX metrics to Prometheus.

**Comment by zhu733756** [comment]
> I don't know the `dcgm-exporter` and its `exposed_X` metrics, but if this is something that makes sense for Java applications running on Kubernetes I am happy to accept a PR. However, I myself have no plans to implement this. I will focus on the core functionality, which is exposing JMX metrics to Prometheus.

OK. Thanks again.  Maybe I need to have a study for these good open-source projects.  :)
