### ISSUE TITLE
Is there any method to collect yarn Application task monitoring information

### ISSUE THREAD

**Issue by liangrui1988** [prometheus/jmx_exporter#649]
Is there any method to collect yarn Application task monitoring information
example：
get  all app information
http://host.domain.com:8088/cluster/app   

Application_id_xxx  :status  Timeout cpu  memory.......   Relevant indicators  to exporter  prometheus ？

thanks

**Comment by dhoard** [comment]
The exporter can capture JVM metrics but overall system-level metrics require system monitoring.
