### ISSUE TITLE
Capture metrics from multiple jmx ports as hostports

### ISSUE THREAD

**Issue by killua202** [prometheus/jmx_exporter#653]
In my VM I want to capture metrics from multiple jmx ports sometime range of jmx ports, I am using this run_sample_httpserver.sh and cofiguration YML file as 

hostPort: 127.0.0.1:1234
rules:
- pattern: ".*"

Here in host port i want to add multipe ports 1235, 1236 or range 1234-1250. Is it possible to add this ?

**Comment by dhoard** [comment]
@killua202 a JVM on listens to a single port JMX access.

Curious as to how this be useful? What problem are you trying to solve with a range?

**Comment by dhoard** [comment]
The jmx_prometheus_httpserver is designed to be used against a single server.
