### ISSUE TITLE
Bean is not found by the exporter

### ISSUE THREAD

**Issue by ozzyian** [prometheus/jmx_exporter#654]
I'm using the exporter to get custom MBeans from an application but some custom metrics are not recognized by the exporter.

The domain of the metric that I want is: "3DEXPERIENCE" and I can see that it is exported in Jconsole. Other custom metrics with domain "MCS" does work and are shown in /metrics by the exporter. I've tried using the minimal configuration "{}" but the mbean is still not exported by the agent. I've also tried using jolokia exporter and that one is able to capture the "3DEXPERIENCE" metrics.

**Comment by dhoard** [comment]
What is the MBean attribute Object type?

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
