### ISSUE TITLE
jmx_ prometheus_ Javaagent stopped running

### ISSUE THREAD

**Issue by ghost** [prometheus/jmx_exporter#669]
Hi, I use JMX_ prometheus_ Javaagent monitors Tomcat and encounters a problem, JMX stops running! In `http://prometheus_ip:9090/targets` Down is displayed, but Tomcat can still be accessed normally.

I guess JMX quit because of the high load? How can I solve this problem?

**Comment by saodis** [comment]
Use the ss command to view the port status, there are a lot of close-wait.
![image](https://user-images.githubusercontent.com/51149477/147382358-bbcd4058-c10d-4cec-8951-cd786bdd1b8b.png)

**Comment by fstab** [comment]
The first step would be to figure out why the `jmx_exporter` agent is unresponsive. Could you create a thread dump? This can be done by sending the -3 signal to the Tomcat process, like `kill -3 <pid>`.

**Comment by saodis** [comment]
@fstab Hi, It's `jmx_ exporter` dump thread? How do I create a thread dump?

**Comment by saodis** [comment]
Sorry, English is not my mother tongue. Can you understand what I mean？

**Comment by dhoard** [comment]
@saodis Have you resolved this issue?

**Comment by yuguangye** [comment]
yes ,i was resolved this issue,
Maybe we're not having the same problem
