### ISSUE TITLE
Limit number of metrics produced

### ISSUE THREAD

**Issue by nyarly** [prometheus/jmx_exporter#678]
A configuration error in our systems produced metrics of the form `"kafka_server_socket_server_metrics_connection_close_rate:_0_04179029629320072"` - the fix for this is obvious now, but in the meantime it's created real problems in our monitoring systems.

Would it be possible for jmx_exporter to track how many metrics it's produced, or how many metrics are different between /metrics requests and clamp those values?

**Comment by dhoard** [comment]
What value would there be to tracking metrics between scrape calls?
Can you elaborate on "clamping"?

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
