### ISSUE TITLE
Support for Histograms

### ISSUE THREAD

**Issue by NegatioN** [prometheus/jmx_exporter#68]
I'm no metric expert, but JMX can export histograms as far as I've seen? It's difficult to graph percentiles for Cassandra without support for histograms in the exporter. 

Are there any plans of adding this?

**Comment by brian-brazil** [comment]
The jmx exporter can export only what is available in JMX. Cassandra doesn't export histograms, so the jmx exporter can't export them.

If you want histograms in Cassandra, that'll require changes to Cassandra.

**Comment by NegatioN** [comment]
Maybe I'm misunderstanding, but I see quite a few mentions of histograms in the [Cassandra metric docs](https://wiki.apache.org/cassandra/Metrics)?

I realize that the exporter can only access what is already there, but am I correct in saying it currently does not support Histograms? The docs says: "type	The type of the metric, can be GAUGE or COUNTER. name must be set to use this. Defaults to GAUGE."

So assuming it is correct, I'm simply wondering if there are any plans for adding support for histograms in the near future? Or are there any obstacles to doing so? :)

**Comment by brian-brazil** [comment]
I don't think we'll support histograms in the jmx exporter for sanity's sake, however there's nothing preventing you from emulating it. A Prometheus histogram is just a set of counters.

**Comment by NegatioN** [comment]
Feels hacky to emulate it myself as well, so we'll see how essential it really is to have. :) Thanks for the help.

**Comment by brian-brazil** [comment]
It's not that hacky for an exporter. Exporters are all about tradeoffs.
