### ISSUE TITLE
Kafka's example config file shows misleading metrics

### ISSUE THREAD

**Issue by garyparrot** [prometheus/jmx_exporter#680]
Hello there,

I am facing an issue when running the JMX exporter with [Apache Kafka's example config file](https://github.com/prometheus/jmx_exporter/blob/d2d8a2214b9a869f40cc3cb145c37c7840ca75ba/example_configs/kafka-2_0_0.yml).

The metric `kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_count`(I believe it is exported by [this](https://github.com/prometheus/jmx_exporter/blob/d2d8a2214b9a869f40cc3cb145c37c7840ca75ba/example_configs/kafka-2_0_0.yml#L96-L98) rule), judging from the name it's supposed to show some percentage value. But if we draw this metric, we can see the value far exceeds the `[0, 1]` range a percentage value is supposed to be.

![](https://user-images.githubusercontent.com/39105714/151192078-cb052edc-e681-4f8d-a274-29a063362c89.png)

After further investigation, it seems that the target java bean has the following form.

```
[kafka.server:type=KafkaRequestHandlerPool,name=RequestHandlerAvgIdlePercent]
    "Count": 468668694921
    "EventType": percent
    "FifteenMinuteRate": 0.9786859257308558
    "FiveMinuteRate": 0.9921332610120102
    "MeanRate": 0.9995291889837272
    "OneMinuteRate": 0.9988134426109028
    "RateUnit": NANOSECONDS
```

I think that metric is exposing the `"Count": 468668694921` attribute. I have zero experience with the metric library Apache Kafka is using. But my guess is that this `Count` is increased every time this percentage value refreshes(Probably a few nanoseconds for one refresh to occurred).

It looks like [some other guy](https://stackoverflow.com/questions/63380178/kafka-metric-requesthandleravgidlepercent) is suffering from this issue too.

This exposed attribute has little relationship with the goal of this Java bean. Is it possible to get this fix?

Many thanks in advance. 👍

**Comment by dhoard** [comment]
This appears to be a bug in Kafka https://issues.apache.org/jira/browse/KAFKA-7295

The example configuration YAML file has the change mentioned on Stackoverflow

**Comment by dhoard** [comment]
Closed due to inactivity.
