### ISSUE TITLE
Memory will be raised 

### ISSUE THREAD

**Issue by yaofly2019** [prometheus/jmx_exporter#685]
The memory will be raised 20-30M every requests to jmx_exporter
![image](https://user-images.githubusercontent.com/58969363/154632997-b028217f-103b-4f2c-950c-0b4fa75049f6.png)

**Comment by ChampiYann** [comment]
We see something similar happening. It started seemingly out of nowhere.

**Comment by dhoard** [comment]
@yaofly2019 the core HTTPServer uses a `ThreadLocal` to allocate a byte array to store a response for efficiency.

(https://github.com/prometheus/client_java/blob/da243e272d80d58d4b8bbf5c63d4aec4feaed51a/simpleclient_httpserver/src/main/java/io/prometheus/client/exporter/HTTPServer.java#L73)

The `ThreadLocal` byte array size will grow to the largest metrics response that was served by the thread.

By default, the cached threads are keep-alive for 2 minutes

https://github.com/prometheus/client_java/blob/da243e272d80d58d4b8bbf5c63d4aec4feaed51a/simpleclient_httpserver/src/main/java/io/prometheus/client/exporter/HTTPServer.java#L457

Using an agressive scrape internal along with large metrics responses, this will result in threads being created to handle the load and `ThreadLocal` byte array object to be allocated.

As the threads are no longer required (not used in 2 minutes), they will age out and be removed, resulting in the `ThreadLocal` storage being freed.

What is your scrape interval?
What is your metrics response size?

**Comment by omersiar** [comment]
We see similar happening in our environment too.  We have an aggressive scrape interval of 2 seconds , memory usage is ~20GB.

**Comment by dhoard** [comment]
@yaofly2019 @ChampiYann @omersiar Please provide the exact jar version in which you reported the issue.

**Comment by dhoard** [comment]
Please review my comment https://github.com/prometheus/jmx_exporter/issues/685#issuecomment-1510659512 to understand the behavior.

I have added HTTPServer threads configuration for the next post `0.19.0` release to allow configuration of the minium, maximum, and thread keep-alive time.

https://github.com/prometheus/jmx_exporter#http-thread-pool-configuration-optional

**Comment by dhoard** [comment]
With the 0.20.0 release, the exporters default to a maximum of 10 threads but it is configurable.
