### ISSUE TITLE
Could jmx_exporter support running on AIX power linux

### ISSUE THREAD

**Issue by dungnt081191** [prometheus/jmx_exporter#701]
is jmx_exporter can running on AIX power linux or not.
when run jmx_exporter have lots of installtion isssue

**Comment by fstab** [comment]
I'm not aware of any issues. Please post some context, like how you install it and what errors you are seeing.

**Comment by cnskylee** [comment]
> is jmx_exporter can running on AIX power linux or not. when run jmx_exporter have lots of installtion isssue

In my opinion, jmx_exporter depend on Java Env., when you use java -jar xxx.jar to run a jar file ,or use tomcat moddileware etc. to run java web applications, you can use jmx_exporter, as you know that java can compiled once and run in any platform.

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
