### ISSUE TITLE
record-send-total and recod-consumd-total for not reported for all topics in cluster

### ISSUE THREAD

**Issue by amit-s-shah** [prometheus/jmx_exporter#705]
Below metrics report data for few topics from kafka cluster but not for all the topics. I am not able to understand the reason for it. Looking for some direction/ help here . 

- record-send-total metric under MBean: kafka.producer:type=producer-topic-metrics 
- records-consumed-total under MBean: kafka.consumer:type=consumer-fetch-manager-metrics,

using jmx_prometheus_javaagent-0.14.0.jar with below exporter configuration.

`lowercaseOutputLabelNames: false`
`lowercaseOutputName: true`
`ssl: false`

Thank you

**Comment by dhoard** [comment]
Some metrics are producer-only/consumer-only. If you are monitoring the broker, verify the metrics you are looking for are broker metrics.
