### ISSUE TITLE
unable to scrape activemq metrics from WIldfly17.0.1 domain.

### ISSUE THREAD

**Issue by obulirajm** [prometheus/jmx_exporter#707]
We have configured jmx_exporter on our wildfly domain using the default [wildfly-10.yaml] (https://github.com/prometheus/jmx_exporter/blob/master/example_configs/wildfly-10.yaml)

Though it seem to contain parameters to pull activeMQ metrics, we dont see any activeMQ data being scraped. Is there any change required to this config to support this.

**Comment by dhoard** [comment]
@obulirajm any updates?
