### ISSUE TITLE
是否可以实现监控哪些服务占用内存比较大呢

### ISSUE THREAD

**Issue by BQDMDMN** [prometheus/jmx_exporter#711]
在jvm运行时，能否实时监控对象的内存占用情况，或找出占用内存比较大的几个对象，就不需要dump文件来分析哪些对象导致的OOM,也可以提起避免出现OOM

**Comment by dhoard** [comment]
导出程序不提供堆转储来检测 OOM 异常。必须使用标准堆转储工具。

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
