### ISSUE TITLE
Unable to fetch kafka connector and task status metrics

### ISSUE THREAD

**Issue by khatribh** [prometheus/jmx_exporter#713]
Hi, 
I'm unable to fetch the kafka connector and task status metrics. I followed this issue, 
(https://github.com/prometheus/jmx_exporter/issues/633) and was still not able to get the connector status. I also followed the sample patterns to fetch the task status metrics but that didn't seem to work. Can anyone help me out?
https://github.com/prometheus/jmx_exporter/blob/master/example_configs/kafka-connect.yml

**Comment by khatribh** [comment]
Can anyone help me out? Still facing this issue.

**Comment by dhoard** [comment]
Take a look at

https://github.com/confluentinc/jmx-monitoring-stacks/blob/7.2-post/shared-assets/jmx-exporter/kafka_connect.yml

**Comment by timchenko-a** [comment]
Mentioned one isn't working, I suspect this is due to the fact status is reported as a string, so not exposed correctly. In my case as a workaround I was able to set task value as a label and expose with static value:
```
  - pattern : "kafka.connect<type=connector-task-metrics, connector=(.+), task=(.+)><>status: (.*)"
    name: kafka_connect_connector_task_status
    value: 1
    labels:
      connector: $1
      task: $2
      status: $3
```
