### ISSUE TITLE
rmi timeout

### ISSUE THREAD

**Issue by congyewudi** [prometheus/jmx_exporter#717]
How to configure the timeout of jmx_prometheus_httpserver rmi

**Comment by congyewudi** [comment]
connectTimeout and responseTimeout

**Comment by congyewudi** [comment]
I add parameters(-Dsun.rmi.transport.tcp.responseTimeout=10000) that have no effect on the command line

**Comment by fstab** [comment]
Hmm, I don't see why standard configuration wouldn't work. The `JmxScraper` creates a straightforward `MBeanServerConnection`:

https://github.com/prometheus/jmx_exporter/blob/master/collector/src/main/java/io/prometheus/jmx/JmxScraper.java#L95-L96

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
