### ISSUE TITLE
Add configuration for the minimum and maximum number of HTTP Server threads

### ISSUE THREAD

**Issue by atl-mk** [prometheus/jmx_exporter#720]
There's at least two problems this solves:

1. The output buffer of the HTTP threads is held by a strong reference so if there's a lot of metrics (on the order of 10,000s) the memory usage can be considerable (on the order of 100s MB which is much larger than the raw metric).
2. On smaller [hardware] machines if the exporter end point is being hammered, then the processor utilisation can also be significant (by default 5 up to hardware threads). Dropping metrics data in this case is favourable compared to the potentially instability of what's being monitored and it would help find the issue faster.

**Comment by dhoard** [comment]
@atl-mk 

Regarding 1.

`client_java` https://github.com/prometheus/client_java/issues/703

The thought process around keeping the buffer around https://github.com/prometheus/client_java/issues/703#issuecomment-930470387

Regarding 2.

If the agent's metrics endpoint is being called too aggressively, then the calling system should be using a longer scraping interval.

**Comment by atl-mk** [comment]
@dhoard absolutely, but that shouldn't bring down nor affect the performance of what is being monitored. Instead putting a hard and low limit allows finding that issue more quickly.

**Comment by dhoard** [comment]
@atl-mk

WRT 1 - I'm in agreement, min/max threads should be configurable. The core `HTTPServer` class allows for this configuration when built using the `HTTPServer.Builder`. The JMX exporter has yet to implement this feature.

WRT 2 - I'm in agreement that the exporter shouldn't adversely affect the performance of the application being monitored. This can be difficult because the exporter has no control of JMX MBeans/metrics that are registered or how long it takes to scrape them.

You mentioned "dropping metrics" ... can you clarify?

**Comment by atl-mk** [comment]
@dhoard Oh apologies, I was confused and misread that, I'm sorry.

Sorry, "dropping metrics" is not the really right, what I meant was; as the Prometheus server is polling there will be missing data points if the poll interval is shorter than the time it takes to get a response from the exporter. In my experience this has been pretty quickly identified by looking at Grafana dashboards.

**Comment by dhoard** [comment]
@atl-mk I have added thread min, max, and keep-alive configurations to the HTTP server. The code is pre-release but well-tested.

See https://github.com/prometheus/jmx_exporter/issues/688

**Comment by atl-mk** [comment]
Thanks @dhoard, looking forward to see this in main

**Comment by dhoard** [comment]
@atl-mk This is targeted for the 0.18.0 release

**Comment by dhoard** [comment]
@atl-mk with the recent changes made in the 0.19.0 release, code changes to implement HTTP server thread pool configuration should be straightforward.

Given a `ThreadPoolExecutor` ...

```
public ThreadPoolExecutor(
    int corePoolSize,
    int maxPoolSize,
    long keepAlive,
    TimeUnit unit,
    BlockingQueue<Runnable> workQueue,
    RejectedExecutionHandler handler
);
```

My current thought is ...

Expose `corePoolSize`, `maxPoolSize`, `keepAlive` (exposed as seconds), and queue size as configuration parameters.

If values aren't defined, the code would use defaults.

To prevent an unbounded queue scenario, the code would use a `BlockingArrayQueue`.

To handle a scenario where all threads are in use and the queue is full, the code would use a `RejectedExecutionHandler` that blocks.

Thoughts?

**Comment by atl-mk** [comment]
@dhoard sounds good
