### ISSUE TITLE
Could Jmx exporter support to connect multi java processes?

### ISSUE THREAD

**Issue by EvanLjp** [prometheus/jmx_exporter#723]
Currently, I found the jax_exporter only supports to connect one java process with remote JMX protocol? 
Could Jmx exporter could enhance server ability to support multi processes?

**Comment by EvanLjp** [comment]
for example. http server runs with daemonset

**Comment by dhoard** [comment]
Aggregation of metrics from the applications is a concern of the monitoring tool (Prometheus, etc.)

In general, if you are running a Java application, you should use `jmx_exporter` as an agent for each application within the application container image.

If you can't / don't want to change the application container image, but the image allows exposing JMX (i.e. allows configuring JVM arguments), then a sidecar could be created to monitor the application.

More details on your use case / constraints (documentation / deployment diagrams) would help with the conversation.
