### ISSUE TITLE
Version 0.17.0 is returning unknown version and name info

### ISSUE THREAD

**Issue by kaiquerass** [prometheus/jmx_exporter#728]
Docker image version 0.17.0 is returning `jmx_exporter_build_info{version="unknown",name="unknown",} 1.0`, which is breaking our scrape to this metrics.

Expected behavior: 
The same result of 0.16.1 version image `jmx_exporter_build_info{version="0.16.1",name="Prometheus JMX Exporter - Http Server",} 1.`

**Comment by dhoard** [comment]
@kaiquerass @LHozzan I created a PR to resolve the issue.

However, the name will represent the artifact name `jmx_prometheus_httpserver` and not the project name `Prometheus JMX Exporter - Http Server` (The name change was apparently made post `0.0.16`... not sure why)

**Comment by devopology** [comment]
@kaiquerass @LHozzan please verify against `0.18.0` and close if resolved.
