### ISSUE TITLE
-javaagent failed, processJavaStart failed

### ISSUE THREAD

**Issue by anshul81095** [prometheus/jmx_exporter#731]
Im trying to connect my kafka with jmx 

Using Java 11
Kafka 3.0.0
JMX 0.17
and using the 
KAFKA_OPTS in service file after entring and restarting the kafka fails to restart giving the following error

*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422

**Comment by bnjns** [comment]
@anshul81095 I'm getting the same error in Kafka Connect 7.x - did you manage to identify the issue?

**Comment by fstab** [comment]
Do you have any other agent attached in addition to `jmx_exporter`?

**Comment by bnjns** [comment]
Not as far as I'm aware; we just have `export KAFKA_OPTS="-javaagent:/opt/jmx_prometheus_javaagent.jar=9875:/opt/jmx_exporter_config.yml"`.

**Comment by dhoard** [comment]
@bnjns I just tested the scenario, and can't reproduce your issue.

Java version...
```
openjdk version "11.0.17" 2022-10-18 LTS
OpenJDK Runtime Environment Zulu11.60+19-CA (build 11.0.17+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.60+19-CA (build 11.0.17+8-LTS, mixed mode)
```

You mention "service file"... how are you starting Connect? systemd? Can you share the file?

**Comment by bnjns** [comment]
Oh interesting 🤔 We're using the Kafka Connect docker image (`confluentinc/cp-kafka-connect:7.3.0`), which is deployed to ECS as a single task. As part of the docker build, we download the exporter jar and copy over the config file, and then configure `KAFKA_OPTS` to the above value.
