### ISSUE TITLE
Is there a reference list of JVM-defined MBeans?

### ISSUE THREAD

**Issue by hjellinek** [prometheus/jmx_exporter#733]
I'm using the JMX Exporter without difficulty.  That is, all of the attributes show up in our monitoring systems as expected.  It's great!

The difficulty is in interpreting some of the data.  Is there a reference document that lists all of the MBeans the JVM (Java 11, in this case) instantiates and defines them?  I'm mainly talking about the keys that begin with `java_lang_`.

I've looked in various JSRs, on the Oracle Java site, an so on, but my search engine-fu has turned up nothing helpful.

Can you provide a pointer?  Thanks.

**Comment by fstab** [comment]
Not sure if there is a complete list somewhere, but in most cases you should find documentation in the corresponding javadoc.

Example: `java_lang_OperatingSystem_TotalSwapSpaceSize` corresponds to [OperatingSystemMXBean.getTotalSwapSpaceSize()](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.management/com/sun/management/OperatingSystemMXBean.html)

**Comment by hjellinek** [comment]
Thanks.  That may be the best I can hope for.  It would be so handy for my users, not all of whom are Java programmers, not to have to do this sort of multi-step lookup, but that's ~~Sun's~~ Oracle's responsibility, not Prometheus's.
