### ISSUE TITLE
why kafka JMX_EXPORTER haven't a helm installtion 

### ISSUE THREAD

**Issue by charithakaluhendiwala** [prometheus/jmx_exporter#738]
Where can I find a legitimate helm chart for kafka JMX_EXPORTER ?

**Comment by dhoard** [comment]
JMX Exporter in standalone HTTP server mode : 

I am not aware of a helm chart for running the JMX Exporter in standalone mode. Typically you would use a Docker image. (Various people have created images.)

JMX Exporter in Java agent mode :

You would integrate the JMX exporter Java agent into your existing application's Helm chart.

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
