### ISSUE TITLE
Native Memory Tracking

### ISSUE THREAD

**Issue by whiteskylife** [prometheus/jmx_exporter#739]
Is there a way to set up a pattern to capture information about Native memory?   such as Thread  stack ？

> jcmd <pid> VM.native_memory summary                                                                
Native Memory Tracking:
Total: reserved=6649506KB, committed=415302KB
               Java Heap (reserved=5064704KB, committed=317440KB)
                         (mmap: reserved=5064704KB, committed=317440KB) 
                   Class (reserved=1056927KB, committed=5919KB)
                         (classes #944)
                         (  instance classes #843, array classes #101)
                         (malloc=159KB #1291) 
                         (mmap: reserved=1056768KB, committed=5760KB) 
                         (  Metadata:   )
                         (    reserved=8192KB, committed=5120KB)
                         (    used=1311KB)
                         (    free=3809KB)
                         (    waste=0KB =0,00%)
                         (  Class space:)
                         (    reserved=1048576KB, committed=640KB)
                         (    used=161KB)
                         (    free=480KB)
                         (    waste=0KB =0,00%)
                  Thread (reserved=20601KB, committed=977KB)
                         (thread #17)
                         (stack: reserved=20520KB, committed=896KB)
                         (malloc=59KB #104) 
                         (arena=22KB #32)

-

**Comment by dhoard** [comment]
If the data isn't in one of standard metrics exports ( https://github.com/prometheus/client_java/tree/main/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot ) you could write and register your own MBean to capture and report the data.

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
