### ISSUE TITLE
At what rate are metrics exported from JMX? Is it configurable?

### ISSUE THREAD

**Issue by djkashtan** [prometheus/jmx_exporter#743]
This issue (https://github.com/prometheus/jmx_exporter/issues/498) mentions polling different java-agents at different rates. I am not even sure what the default rate is and I do not know how to change it.

**Comment by fstab** [comment]
Polling is not configured in `jmx_exporter`, it's a config option of the Prometheus server. Whenever the Prometheus server polls, `jmx_exporter` loads the current values from JMX beans. Typical poll intervalls of the Prometheus server are 30s or 60s.

**Comment by djkashtan** [comment]
Is there a way to tell how often the JMX beans are being updated?

**Comment by fstab** [comment]
I guess it depends on the JMX bean, but usually they are callbacks that are evaluated on the fly. For example, a JMX bean representing the size of a queue will calculate the queue size on the fly when it's polled. It will not be updated as the queue size changes.

**Comment by dhoard** [comment]
Closed as resolved.
