### ISSUE TITLE
why in this place use  System.exit(1)?

### ISSUE THREAD

**Issue by zhic0223** [prometheus/jmx_exporter#745]
![image](https://user-images.githubusercontent.com/102710484/199664559-55ee87f2-1f1d-41b2-9b5b-f69046301970.png)

why in this place use  System.exit(1)? Can I rm it?

**Comment by zhic0223** [comment]
@brian-brazil

**Comment by fstab** [comment]
What else would you expect to happen if you run it with illegal command line parameters?

**Comment by zhic0223** [comment]
> 

I mean if use System.exit(1),Will using this cause the process of the application that the user mounts the jmx-exporter agent to also exit?

**Comment by fstab** [comment]
Yes. If you start the application with an illegal command line, the application exits immediately.

**Comment by zhic0223** [comment]
> 
So I think this place is not very user friendly, is there any way to optimize it here

**Comment by dhoard** [comment]
@zhic0223 not sure what you're trying to accomplish. If you define your application to use the agent and the agent is misconfigured, allowing the application to run without the agent doesn't make sense to me.

**Comment by zhic0223** [comment]
> 

When the agent of jmx-exporter is mounted, if the client's application is forcibly exited simply because the parameters of vm options do not conform to the specifications of jmx, I think this is unreasonable. You can only exit the agent, not the Also opted out of the client's app.

**Comment by zhic0223** [comment]
I think this part can be optimized to remind the user that the vm options parameter configured when accessing the agent is incorrect, and tell him the correct configuration method, which is more secure. You can't cut off a person's head just because he has a cold.

**Comment by dhoard** [comment]
@zhic0223 I disagree. Allowing the application to run with a misconfigured agent will most likely result in more work on the end user to debug the issue and possibly more GitHub issues... "We installed and configured the agent and the application is running, but we can't access the JMX metrics"

**Comment by zhic0223** [comment]
> I disagree. Allowing the application to run with a misconfigured agent will most likely result in more work on the end user to debug the issue and possibly more GitHub issues... "We installed and configured the agent and the application is running, but we can't access the JMX metrics"

@dhoard There is a scenario that the customer's online application needs to monitor and observe the indicators of jvm for some reason, and then the customer mounts jmx, but his online application is not allowed to hang up for a long time. Then if the customer's vm options parameter is wrongly written, will the customer's online application always fail to start? What if that app has a lot of people online? If the customer's application is directly exited by jmx, the customer will never use jmx again?

**Comment by dhoard** [comment]
@zhic0223 Thanks for the use case clarification.

The agent is written assuming it will be defined as part of the JVM arguments and configured correctly. In my opinion/experience, this is the most common use-case scenario.

The code would need to be changed to support dynamic attachment correctly. (Failure of the agent doesn't cause the application to exit.) Keep in mind that attaching an agent dynamically to a running JVM requires the application to be coded to dynamically load the agent.

@fstab is dynamic loading a scenario the agent is expected to handle?

**Comment by dhoard** [comment]
To support correctly support dynamic agent loading (prevent misconfiguration from exiting the application when using the agent dynamically) the`JmxCollector` code would also need to be changed.

https://github.com/prometheus/jmx_exporter/blob/b6b811b4aae994e812e902b26dd41f29364c0e2b/collector/src/main/java/io/prometheus/jmx/JmxCollector.java#L147

https://github.com/prometheus/jmx_exporter/blob/b6b811b4aae994e812e902b26dd41f29364c0e2b/collector/src/main/java/io/prometheus/jmx/JmxCollector.java#L106

**Comment by fstab** [comment]
@dhoard thanks a lot for looking into this. I agree the agent is not written with dynamic attachment in mind. There are some other issues as well, like the agent does not detach cleanly as some classes will still be referenced after detaching the agent (see https://github.com/prometheus/client_java/issues/809). The recommended usage is either to attach the agent at startup and leave it attached, or to run `jmx_exporter_httpserver` in standalone mode and scrape JMX beans remotely via the network.

**Comment by zhic0223** [comment]
> @zhic0223 Thanks for the use case clarification.
> 
> The agent is written assuming it will be defined as part of the JVM arguments and configured correctly. In my opinion/experience, this is the most common use-case scenario.
> 
> The code would need to be changed to support dynamic attachment correctly. (Failure of the agent doesn't cause the application to exit.) Keep in mind that attaching an agent dynamically to a running JVM requires the application to be coded to dynamically load the agent.
> 
> @fstab is dynamic loading with bad configuration a scenario the agent is expected to correctly handle?
> 
> EDIT: updated question

You're welcome！I hope there are more scenarios to be tested and perfected here.

**Comment by dhoard** [comment]
Dynamic attachment is not supported/working as designed.

Closing as resolved.
