### ISSUE TITLE
Kafka Kraft JMX Metrics

### ISSUE THREAD

**Issue by bharathreddy901** [prometheus/jmx_exporter#753]
Hi Team - I have installed Kafka cluster in Kraft mode(with out zookeeper).I could not see the JMX Metrics.I have enabled with below file.

https://github.com/prometheus/jmx_exporter/blob/main/example_configs/kafka-2_0_0.yml

Is there any new configuration file for Kafka Kraft mode to expose the metrics.

Thanks.

**Comment by one-two-my-gad** [comment]
hello，请问现在有处理结果了么

**Comment by dhoard** [comment]
The file referenced is specific to ZooKeeper-based clusters.

You will need to consult https://cwiki.apache.org/confluence/display/KAFKA/KIP-835%3A+Monitor+KRaft+Controller+Quorum+Health to get a list of MBean for KRaft metrics

**Comment by dhoard** [comment]
@bharathreddy901 Have you consulted the documentation to determine the correct MBeans for KRaft metrics?

Have you resolved this issue?

If there are no updates within 1 week, this will be closed as inactive.
