### ISSUE TITLE
 Jmx metric name  Inconsistent with the official website of Apache

### ISSUE THREAD

**Issue by Mrchumo** [prometheus/jmx_exporter#754]
I downloaded jmx_ prometheus_ Javaagent-0.17.2. jar, and configure it to the hadoop.env.sh, but the metrics name is inconsistent with that described on the Apache website. For example, the port view indicator name is hadoop_ namenode_ Cachhit, but there is no relevant description on the Apache web page. Can you give a corresponding relationship and whether there is a dashboard to share

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
