### ISSUE TITLE
 untyped metrics 

### ISSUE THREAD

**Issue by ldpiuaeng** [prometheus/jmx_exporter#762]
there are many untyped metrics in the [jdk](https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.17.2/jmx_prometheus_javaagent-0.17.2.jar)
![image](https://user-images.githubusercontent.com/41384109/209626590-1ada5c80-4b6e-48bc-9036-e4cf3f2c05a0.png)

**Comment by fstab** [comment]
Untyped is the default if you don't specify a type in `config.yaml`.
