### ISSUE TITLE
no main manifest attribute

### ISSUE THREAD

**Issue by ppalza** [prometheus/jmx_exporter#763]
When I put myJar at the end of the command line:
`java -javaagent:./jmx_prometheus_javaagent-0.16.1.jar=8080:config.yaml -jar yourJar.jar`
I get an error message saying that there is no main manifest attribute:
`no main manifest attribute, in yourJar.jar`
This happens with all JAR Files from any application I'm trying it with.

Does anyone know what I might be missing? Thanks in advance.

**Comment by dhoard** [comment]
The `META-INF/Manifest` in your jar file needs to have a main class defined This is an application issue.

Test `java -jar yourJar.jar` ... it should work without the JMX Exporter Java agent jar configuration.

**Comment by dhoard** [comment]
@ppalza

Have you resolved this issue?

If there are no updates within 1 week, this will be closed as inactive.
