### ISSUE TITLE
Multiple JVMs via single endpoint

### ISSUE THREAD

**Issue by robertgates55** [prometheus/jmx_exporter#764]
At my company one of our components runs a 'parent' JVM that spawns 'child' JVMs to execute some of its jobs. This happens within a single kubernetes pod.

We've used the exporter to successfully export 'parent' stats (via the javaagent) but was looking for a reliable pattern for also exposing the stats from 'child' JVMs. We run a push gateway presently, where the child jvms export some stats - is there any option to have jmxexporter push to this? Or an alternative, better pattern?

**Comment by dhoard** [comment]
One option is to write a custom exporter they scrapes the application and all child applications, rewriting all metrics keys with machine specific tags allowing consolidation.

Dynamically launched applications are better suited to a metric push model/system.

**Comment by dhoard** [comment]
@robertgates55 The JMX Exporter is only designed to run against a single JVM. Have you determined a solution?
