### ISSUE TITLE
Anleitung - JMX Exporter

### ISSUE THREAD

**Issue by Sebahartfiel** [prometheus/jmx_exporter#765]
Hallo Zusammen, 
schnelle kurze Frage, ich habe auf einem Windows-Server eine Java Anwendung laufen und diese will ich dringend messen. Prometheus und Grafana laufen bereits, da ich mit dem Windows Exporter mir bereits einige Metriken auslese. Für Java wäre der JMX Exporter ideal.
Nur bin ich offensichtlich zu blöd zu verstehen, wie ich ihn zum laufen bekomme.

Kann mir, so doof es klingt, jemand erklären, wie ich den JMX Exporter mit der Java Anwendung verbinde, dies dann in Prometheus bekannt mache?

**Comment by dhoard** [comment]
Dies ist eher ein Support-Problem, das am besten in der Google-Gruppe beantwortet wird https://groups.google.com/g/prometheus-users
