### ISSUE TITLE
Exporter not exporting metrics depending on how the agent is started.

### ISSUE THREAD

**Issue by azer-smartrecruiters** [prometheus/jmx_exporter#769]
My java service is written with gradle. I could observe two different behaviours. One is where I start the agent in a separate gradle task. Like this:

```
tasks.withType(JavaExec) {
    jvmArgs "-javaagent:$projectDir/src/main/resources/jmx_prometheus_javaagent-0.17.2.jar=8075:$projectDir/src/main/resources/config.yaml"
}
```

In the other example I start the agent in `gradle.properties`, with the same command as above.

What I can observe is that in the first case I am seeing all my different metrics correctly exposed. In the second use case, that is not the case anymore. I just see standard jvm metrics exposed.

Am I missing something here?

**Comment by fstab** [comment]
I'm not a Gradle user. However, from the [docs](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties) it looks like you can only configure System properties and Gradle properties in the `gradle.properties` file. So maybe `gradle.properties` is the wrong place for JVM arguments?
