### ISSUE TITLE
Some MBeans not available 

### ISSUE THREAD

**Issue by clailoma** [prometheus/jmx_exporter#772]
Hello,
I have successfully installed jmx_exporter (agent) 0.17.2. After starting the agent I can find a lot of metrics. 
When I open a browser and open localhost:8049/metrics, I find all expected entries from MBean domain "3DEXPERIENCE".
In other used tools like "Jconsole" or "Java Mission Control" I find all mbeans from this domain
MBeans from other domains (mcs), which are also connected to the Java application, could be found. Could it be that the capital letters in the domain name are the problem?

Any ideas or solutinos?

**Comment by dhoard** [comment]
@clailoma for MBeans you are not getting exported, but are the value types?

**Comment by clailoma** [comment]
Sorry, but I do Not understand your answer.
Pleased can you  give me more information about your qestion.
Sorry

**Comment by dhoard** [comment]
The exporter only exports beans with values of type `java.lang.Number` and `java.lang.Boolean`. Other types are ignored.

https://github.com/prometheus/jmx_exporter/blob/154eb86255a59f021e7cca8ca304a36734c10b43/collector/src/main/java/io/prometheus/jmx/JmxCollector.java#L567-L574

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
