### ISSUE TITLE
Kafka connect metrics not supported?

### ISSUE THREAD

**Issue by mihkimjh** [prometheus/jmx_exporter#773]
https://kafka.apache.org/documentation/#connect_monitoring

It appears that the URL above no longer supports Kafka Connect metrics.
Is it true that we don't actually support Kafka connect metrics anymore?
I am currently in a state where I can view all Kafka related metrics by pulling the metrics information into *.
However, metrics related to Kafka Connect are not being collected.
Is it correct that this is no longer supported as per the official documentation?
If there is a version of jmx_exporter that supports Kafka Connect Matrix, please answer.
Below is my yml file.
<pre><code>rules:
- pattern: ".*"</code></pre>

**Comment by dhoard** [comment]
@mihkimjh There is no Kafka-specific code the in JMX exporter. The document shows the Connect MBeans.
