### ISSUE TITLE
IS the JMX exporter compatible with java azul  Zulu 8.64

### ISSUE THREAD

**Issue by skullking1612** [prometheus/jmx_exporter#778]
Hi All,
     facing an issue after upgrading to azul zulu 8.64, now jmx exporter is not scrapping the mbean metrices after the update, just stats the connection refused but havent made any changes for same, is this version supported to run jmx exporter? and we have upgraded from jmx-0.12.0 to 0.17.0 but as no changes were mentioned to be carried for config.yaml we have kept same config yaml of 0.12.0 for new version.

**Comment by fstab** [comment]
Hi, I just tried Zulu 8.68 and it worked without any issues. As you write "connection refused" I assume you are running jmx_exporter as a standalone HTTP server. Here's what I did:

Start an example application
```
~/Downloads/zulu8.68.0.21-ca-jdk8.0.362-linux_x64/bin/java -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -jar integration_tests/jmx_example_application/target/jmx_example_application.jar
```

Run jmx_exporter as a standalone HTTP server
```
 ~/Downloads/zulu8.68.0.21-ca-jdk8.0.362-linux_x64/bin/java -jar ./jmx_prometheus_httpserver/target/jmx_prometheus_httpserver-0.18.0.jar 9000 ./integration_tests/smoke_tests/src/test/resources/config-httpserver.yml
```

Metrics are successfully exposed on http://localhost:9000/.

**Comment by dhoard** [comment]
I ran the integration test suite I have been working on against this specific version without issues as well.

**Comment by skullking1612** [comment]
OK thanks, will Check configurations for any missing values

**Comment by dhoard** [comment]
Resolved as not reproducible.
