### ISSUE TITLE
Please publish .jar's and .deb with each Release

### ISSUE THREAD

**Issue by tamsky** [prometheus/jmx_exporter#78]
it would be helpful to be able to rely on a published set of binaries.

**Comment by brian-brazil** [comment]
Jars are published to maven.

**Comment by tamsky** [comment]
Awesome to know that, thanks!

**Comment by akamensky** [comment]
so for someone who just needs to install it you require to install and learn maven? Okay, then I'll advice all other developers in C/C++ removing binary releases and make everyone learn GNU Make, GCC etc to just install Apache server.
