### ISSUE TITLE
No main manifest attribute, in jmx_prometheus_javaagent-0.18.0.jar

### ISSUE THREAD

**Issue by NuwanSameera** [prometheus/jmx_exporter#788]
I am try to use jmx_prometheus_javaagent-0.18.0.jar to export metrics to Prometheus, because documentation says **As stated above, it is recommended to run JMX exporter as a Java agent and not as a standalone HTTP server.**

But javaagent doesn't have main class. I checked the source code as well.

Standalone HTTP server is working fine. But I need to use javaagent, because it is the best one as documentation

**Comment by NuwanSameera** [comment]
@dhoard Got it thanks. I am going to use this with HBase

Need to add following line to `hbase-env.sh`
`HBASE_OPTS="$HBASE_OPTS -javaagent:/path/jmx_prometheus_javaagent-0.7.jar=7000:/path/hbase_jmx_config.yaml"`

**Comment by dhoard** [comment]
> @dhoard Got it thanks. I am going to use this with HBase
> 
> Need to add following line to `hbase-env.sh` `HBASE_OPTS="$HBASE_OPTS -javaagent:/path/jmx_prometheus_javaagent-0.7.jar=7000:/path/hbase_jmx_config.yaml"`

@NuwanSameera I would use a newer version of the JMX Exporter - 0.7 is old.
