### ISSUE TITLE
How to monitor the jvm thread pool

### ISSUE THREAD

**Issue by jianghebo** [prometheus/jmx_exporter#792]
I am using version jmx_prometheus_javaagent_java-1.16.1；
How to use this to listen to the data of the thread pool and report

**Comment by dhoard** [comment]
@jianghebo can you provide more detail?

**Comment by jianghebo** [comment]
For example, I want to monitor the thread pool of 'java. util. concurrent. ThreadPoolExecutor' created manually in the java application, obtain the corePoolSize, largestPoolSize, maximumPoolSize of the thread pool, as well as the thread execution time, etc

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
