### ISSUE TITLE
jmx-exporter cant scrape some text metrics

### ISSUE THREAD

**Issue by MikeMX777** [prometheus/jmx_exporter#804]
Hi all! 
I have a problem in scrape some text metrics from apache artemis. I know that value of metric is only numeric, and for tests value set to 1. That is my pattern in rules:
```
  - pattern: "^org.apache.activemq.artemis<broker=\"([^\"]*)\",\\s*component=cluster-connections,\\s*name=\"([^\"]*)\"><>([^:]*):(.*)"
    attrNameSnakeCase: true
    name: artcluster_$3
    value: 1
    labels:
        a1: $1
        a2: $2
        a3: $3
        a4: $4
```
Attributes:
```
scrape            "Started": true,
scrape            "Address": "",
scrape            "MessagesAcknowledged": 1,
scrape            "MessageLoadBalancingType": "ON_DEMAND",
!DONT scrape      "Topology": "topology on Topology@47f077e3[owner=ClusterConnectionImpl@53887553[nodeUUID=e6b1d33c-a8af-11ed-837e-0242ac110002, connector=TransportConfiguration(name=netty-connector, factory=org-apache-activemq-artemis-core-remoting-impl-netty-NettyConnectorFactory) ?port=61616&host=art-smx03-t, address=, server=ActiveMQServerImpl::name=art-smx03-t]]:\n\te6c92b4c-a8af-11ed-baf9-0242ac110002 => TopologyMember[id=e6c92b4c-a8af-11ed-baf9-0242ac110002, connector=Pair[a=TransportConfiguration(name=netty-connector, factory=org-apache-activemq-artemis-core-remoting-impl-netty-NettyConnectorFactory) ?port=61616&host=app-smx01-t, b=TransportConfiguration(name=netty-connector, factory=org-apache-activemq-artemis-core-remoting-impl-netty-NettyConnectorFactory) ?port=62616&host=art-smx03-t], backupGroupName=art-smx03-t, scaleDownGroupName=null]\n\te5777e6d-a8af-11ed-887a-0242ac110002 => TopologyMember[id=e5777e6d-a8af-11ed-887a-0242ac110002, connector=Pair[a=TransportConfiguration(name=netty-connector, factory=org-apache-activemq-artemis-core-remoting-impl-netty-NettyConnectorFactory) ?port=61616&host=art-smx01-t, b=TransportConfiguration(name=netty-connector, factory=org-apache-activemq-artemis-core-remoting-impl-netty-NettyConnectorFactory) ?port=62616&host=app-smx01-t-], backupGroupName=app-smx01-t, scaleDownGroupName=null]\n\te6b1d33c-a8af-11ed-837e-0242ac110002 => TopologyMember[id=e6b1d33c-a8af-11ed-837e-0242ac110002, connector=Pair[a=TransportConfiguration(name=netty-connector, factory=org-apache-activemq-artemis-core-remoting-impl-netty-NettyConnectorFactory) ?port=61616&host=art-smx03-t, b=TransportConfiguration(name=netty-connector, factory=org-apache-activemq-artemis-core-remoting-impl-netty-NettyConnectorFactory) ?port=62616&host=art-smx01-t], backupGroupName=art-smx01-t, scaleDownGroupName=null]\n\tnodes=6\tmembers=3",
scrape            "MaxHops": 1,
!DONT scrape      "Nodes": {
                                  "e5777e6d-a8af-11ed-887a-0242ac110002": "art-smx01-t",
                                  "e6c92b4c-a8af-11ed-baf9-0242ac110002": "app-smx01-t"
                                         },
scrape            "Name": "smx-art-cluster",
scrape            "DuplicateDetection": true,
```

All atributes are in one level, numeric and small text values are working well, and BIG text values jmx-exporter dont scrape.
I need Topology atribute for parsing nodes and members from it, its type is java.lang.String, and its not working. But other attr - MessageLoadBalancingType has type java.lang.String, and its working!

**Comment by dhoard** [comment]
Text metrics are not supported.

**Comment by MikeMX777** [comment]
But how about other text metrics? when exporter can. For example:
`"MessageLoadBalancingType": "ON_DEMAND"`, - it can scrape. And I can to map it in labels:
`artcluster_message_load_balancing_type{a1="art-smx03-t",a2="smx-art-cluster",a3="message_load_balancing_type",a4=" ON_DEMAND",} 1.0`
And how about standart java metrics?:
```
# TYPE jvm_info gauge
jvm_info{runtime="OpenJDK Runtime Environment",vendor="Eclipse Adoptium",version="11.0.15+10",} 1.0
```

**Comment by dhoard** [comment]
I have tested 70 Java distributions/versions and I am not seeing an MBean named `jvm_info` whatsoever.

Can you provide your complete exporter.yaml?

**Comment by MikeMX777** [comment]
I'm using standart sample config, with small additions, like at top message.
JVM INFO is used by standart grafana dashboard for apache artemis - https://grafana.com/grafana/dashboards/9087-apache-artemis/
![image](https://github.com/prometheus/jmx_exporter/assets/22744709/978f6bc6-4466-4c0d-be34-053ff8e7a9ed)

**Comment by dhoard** [comment]
Looking through the code, an MBean text value will be added as a metric if the text can be converted to a `Double`.

https://github.com/prometheus/jmx_exporter/blob/c2a90ecc23d2ae0909cc197727cc56d00abc94e9/collector/src/main/java/io/prometheus/jmx/JmxCollector.java#L539 is were the MBean value is trying to be to a `Double` and be processed.

So I guess the correct statement would be "The JMX Prometheus Exporter will expose MBean text values if the value can be parsed as a `Double`".

You can use JConsole to view MBeans and their attributes/values and double check the metrics are are missing.
