### ISSUE TITLE
Memory consumption, resource occupation issues

### ISSUE THREAD

**Issue by runfali** [prometheus/jmx_exporter#808]
I am using jmx_prometheus_javaagent-0.17.2.jar here. After the project started, I found that the project occasionally restarted.
Will jmx_prometheus_javaagent-0.17.2 consume a lot of resources?

**Comment by dhoard** [comment]
"A lot of resources" is relative. The exporter will use resources, but the usage is dependent on how many metrics are exposed and the size of the metrics response.

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
