### ISSUE TITLE
How to monitor summary metrics using JMX exporter

### ISSUE THREAD

**Issue by anurag-appperfect** [prometheus/jmx_exporter#809]
For some metrics, it would be useful if we could see a few different percentiles (75, 95 and 99, for example) for metrics, which have constantly a lot of samples in short time periods. Can anybody help me to configure my java service to expose percentile metrics using jmx exporter ?

**Comment by dhoard** [comment]
The exporter only exposes metrics as exposed by JMX. If you want/need histograms, you would need to either create JMX MBeans that expose the percentiles or do it in in Prometheus (time series database.)

**Comment by anurag-appperfect** [comment]
Thank you for your answer, can you tell me a bit more about how we can achieve this in prometheus ?

**Comment by dhoard** [comment]
Typically you would use a [Histogram](https://github.com/prometheus/client_java/blob/main/simpleclient/src/main/java/io/prometheus/client/Histogram.java) to instrument your code.

[HistogramTest](https://github.com/prometheus/client_java/blob/main/simpleclient/src/test/java/io/prometheus/client/HistogramTest.java) is a good example of usage.
