### ISSUE TITLE
docker启动的java应用程序怎么用此插件进行监控呢？

### ISSUE THREAD

**Issue by moyouxuan000000** [prometheus/jmx_exporter#810]

**Comment by dhoard** [comment]
您应该将导出程序 jar 添加到 Docker 映像中。然后你可以 1.将配置 YAML 从 Docker 主机映射到容器，并将导出器端口外部映射到主机 2。将配置 YAML 添加到 Docker 映像，并将导出器端口外部映射到主机

Translated via Google Translate...

**Comment by moyouxuan000000** [comment]
> 

我也想过这样，但是因为有一系列的问题，pass了这个办法，请问除了这种打到镜像里的方法，还有其他办法吗？

**Comment by dhoard** [comment]
Closing as stale. Please reopen if you would like to continue the discussion.
