### ISSUE TITLE
prometheus configs for Kafka Rest Proxy

### ISSUE THREAD

**Issue by yarlagaddag** [prometheus/jmx_exporter#832]
Team, do you have any plans to provide a prometheus config file for Kafka Rest Proxy? I see currently there is one for Kafka and one for Kafka Connect.. but don't see anything for Rest Proxy..

**Comment by dhoard** [comment]
Are you referring to Confluent's Rest Proxy? If so take a look at ...

https://github.com/confluentinc/jmx-monitoring-stacks/blob/7.2-post/shared-assets/jmx-exporter/confluent_rest.yml

**Comment by yarlagaddag** [comment]
Yes,   that is correct @dhoard. Thanks for sharing  the link, I will take a look at it..

**Comment by dhoard** [comment]
Closing as resolved.
