### ISSUE TITLE
Did not find attribute configurationAsXmlString  in jboss6.4.9

### ISSUE THREAD

**Issue by raagulrakesh** [prometheus/jmx_exporter#848]
Hi,
 After enabling jmx_prometheus_javaagent-0.19.0.jar in jboss 6.4.9

My config.yaml
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    whitelistObjectNames: ["*:*"]

Waring message

13:09:38,394 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015961: Http management interface listening on http://0.0.0.0:9990/management
13:09:38,394 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015951: Admin console listening on http://0.0.0.0:9990
13:09:38,394 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015874: JBoss EAP 6.4.9.GA (AS 7.5.9.Final-redhat-2) started in 40346ms - Started 1269 of 1297 services (63 services are lazy, passive or on-demand)
13:09:58,051 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:09:58,336 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:10:56,669 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:10:56,946 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:11:56,591 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:11:56,857 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:12:56,574 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:12:56,839 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:13:56,570 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:13:56,841 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:14:56,489 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:14:56,753 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:15:56,609 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:15:56,881 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:16:56,642 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:16:56,909 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:17:56,551 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString
13:17:56,824 WARN  [org.infinispan.jmx.ResourceDMBean] (prometheus-http-1-1) ISPN000036: Did not find attribute configurationAsXmlString

How to avoid these warning

**Comment by raagulrakesh** [comment]
HI @dhoard 
Thanks for the reply

My JBoss server log file is full of this warning message. how can we remove this warning message in my log file

**Comment by dhoard** [comment]
Configuration of JBoss JMX configuration will need to be resolved via JBoss support/forums. This is out of scope from the exporter.
