### ISSUE TITLE
How much memory and how many threads does jmx_exporter itself take up?

### ISSUE THREAD

**Issue by KeeProMise** [prometheus/jmx_exporter#860]
I want to use jmx_exporter and would like to consult How much memory and how many threads does jmx_exporter itself take up?

**Comment by dhoard** [comment]
The _core_ memory usage is very small, but the depends on the number of simultaneous HTTP requests being served and the number of MBeans being monitored (HTTP response size.)

Technical Details
---

The exporter creates threads to process the inbound HTTP requests - the number of threads is proportional to the number of requests received. Threads age out (exit) after a time period if not used.

Each exporter thread allocates a local `ByteArrayOutputStream` to store the response before sending it to the client - the `ByteArrayOutputStream` memory is cached and reused for subsequent requests on the thread. While the thread is alive, the memory will expand to the largest response it has sent, but will not be garbage collected until the thread ages out (exits.)

**Comment by dhoard** [comment]
With the 0.20.0 release, the exporters default to a maximum of 10 threads but is configurable.
