### ISSUE TITLE
jmx exporter java process network metrics

### ISSUE THREAD

**Issue by real747-david** [prometheus/jmx_exporter#864]
Dear contributors, 

May I know if jmx exporter can provide java process network realted metrics, such as network usage in/out bytes per second, connection target server/client IP:Port, session duration etc. these metrics are very useful for conntion troubleshooting.

if yes, please show us how to do in config.yaml or somewhere, 
if no, do you have any plan to add this feature in future release. 

thanks.

**Comment by dhoard** [comment]
Your application would have to expose JMX MBeans, which the exporter could then export.

**Comment by real747-david** [comment]
could you provide more details about how the application expose JMX MBeans related to network metrics. applications just like, hdfs, hive, kafka etc. appreciate.

**Comment by real747-david** [comment]
could you provide more details about how the application expose JMX MBeans related to network metrics. applications just like, hdfs, hive, kafka etc. appreciate.
