### ISSUE TITLE
QA：Do jmx_prometheus_httpserver scrapy  data from jmx server  proactively when without prometheus？

### ISSUE THREAD

**Issue by hanson2021** [prometheus/jmx_exporter#876]
When i only start jmx_prometheus_httpserver  ,whether it will proactively  scrapy data  or not? If it will, is there any configure to control frequency？

**Comment by fstab** [comment]
No, it's just callbacks waiting for the Prometheus server to scrape. If the metrics endpoint is not called, nothing will happen.

**Comment by mustajibmk** [comment]
Can we have an option to enable active scraping at certain intervals? That way we can remove the dependency on the Prometheus server and jmx_exporter be used as a standalone tool.

**Comment by fstab** [comment]
I think I don't understand your question. What are you trying to achieve? You need a Prometheus server to do Prometheus monitoring, right?

**Comment by mustajibmk** [comment]
Most of the time, yes we would have a Prometheus server which would do it for us. I was referring to the case where jmx_exporter was not being called by the Prometheus server but rather by custom Java code/application.

**Comment by dhoard** [comment]
The JMX exporter exposes a REST API to collect metrics from JMX MBeans. Each REST API call collects metrics and returns a metrics response.

The application (Prometheus, custom application, etc.) calling the REST API doesn't matter.
