### ISSUE TITLE
Error opening zip file or JAR manifest missing jmx_prometheus_javaagent.jar:9200:/jmx-prometheus-kafka-metrics.yaml

### ISSUE THREAD

**Issue by nkol2307** [prometheus/jmx_exporter#878]
hi all we have an issue with .JAR file it is downloaded from this repo https://repo.maven.apache.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.20.0/jmx_prometheus_javaagent-0.20.0.jar

and indead .jar file doesn't have MAIN class definition 

![Screenshot 2023-10-03 at 13 38 44](https://github.com/prometheus/jmx_exporter/assets/56689311/ec0991a2-09e8-42ad-9c5f-7223dbe6e317)

we are starting it using 
KAFKA_OPTS="-javaagent:..../jmx_prometheus_javaagent.jar=9200:...jmx-prometheus-kafka-metrics.yaml"

how is then possible to start this jar file if it doesn't contain main class

**Comment by dhoard** [comment]
Java agents hook into the JVM via the `-javagent` flag and do not have a `Main-Class` manifest.

**Comment by nkol2307** [comment]
> Can you provide the full command line for the process? `ps -f <PID> > output.txt`

-javaagent:/usr/bin/jmx_prometheus_javaagent.jar=9200:/etc/kafka/jmx-prometheus-kafka-metrics.yaml kafka.Kafka /usr/hdp/5.0.11.8/kafka/config/server.properties this part is releveant for us  not whole java command

**Comment by dhoard** [comment]
The exporter jars are valid. Unzip correctly lists the contents and the MANIFEST.MF is correct. All integration tests pass.

This appears to be an application startup issue. Have you checked permissions on the jar and exporter YAML file related to the account running Kafka?
