### ISSUE TITLE
includeObjectNames option issue

### ISSUE THREAD

**Issue by baribalbear** [prometheus/jmx_exporter#879]
Hi All. 

We are running "JBoss EAP 7.4.6.GA (WildFly Core 15.0.15.Final-redhat-00001)"

We are having slow scraping performance (up2 15+sec). I found such issue:

https://github.com/prometheus/jmx_exporter/issues/246
https://github.com/prometheus/jmx_exporter/pull/284

We would like to get data from some specific MBeans only. Was testing with "java.lang:*".  While using below configuration it is working blazing fast (less than 1sec) and gets data from those MBeans only as  required:

whitelistObjectNames: ["java.lang:*"]

However I found such statement in the docs:

Both whitelistObjectNames and blacklistObjectNames are still supported for backward compatibility, but should be considered deprecated.

So I would assume includeObjectNames param should be used instead nowadays? 

But when I put:

includeObjectNames: ["java.lang:*"]

It does nothing - very long scraping time and gets all MBeans. 

Could you please tell what is recommended settings to get only specific MBeans and have the great scraping performance now? Is it still whitelistObjectNames?

Of course I also tried it with:

`rules:`
`  - pattern: "java.lang*"`
 
Yes, I get only specific MBeans data but the scraping speed is very slow comparing to using whitelistObjectNames. So it looks like it fetches all possible MBeans data and only after that does the filtering.

**Comment by dhoard** [comment]
Which version of the JMX Exporter are you using?
Can you share your exporter YAML?

`includeObjectNames` should work exactly like `whitelistObjectNames`
`excludeObjectNames` should work exactly like `blacklistObjectNames`

https://github.com/prometheus/jmx_exporter/blob/89275ac5fed732b943c248867db578b6f12bb756/collector/src/main/java/io/prometheus/jmx/JmxCollector.java#L229-L257

`whitelistObjectNames` and `blacklistObjectNames` are still supported functionality to prevent breaking prior installations that use them, but the long-term goal is to remove their use.

**Comment by baribalbear** [comment]
> Which version of the JMX Exporter are you using?
> Can you share your exporter YAML?

Hi there. I am using this version

#Generated by Maven
#Tue Mar 07 21:57:17 CET 2023
groupId=io.prometheus.jmx
artifactId=jmx_prometheus_javaagent
version=0.18.0

The config looks like:

`
---
includeObjectNames: ["java.lang:*"]
rules:
  - pattern: "java.lang*"
`

**Comment by dhoard** [comment]
This change was introduced into 0.20.0. I would suggest you upgrade due to other performance enhancements in 0.20.0.

**Comment by twoyang0917** [comment]
could you update README file of the repository to make it consistent.
currently it told me to download version 0.19.0 but the example of config file used `includeObjectNames` which it's fault.
I may have to spend more time to found this issue.

**Comment by dhoard** [comment]
> could you update README file of the repository to make it consistent. currently it told me to download version 0.19.0 but the example of config file used `includeObjectNames` which it's fault. I may have to spend more time to found this issue.

I have updated README.md.
