### ISSUE TITLE
Question: Authentication and SSL for jmx_prometheus_javaagent

### ISSUE THREAD

**Issue by GeluConstantin** [prometheus/jmx_exporter#880]
Hi,

Is authentication and SSL supported in jmx_prometheus_javaagent? If yes can you post/send me a link with the technical documentation? If there are special details for Windows let me know.

I want to use the agent for the Tomcat server.

Thank you

**Comment by dhoard** [comment]
HTTP Basic authentication and SSL are supported starting with the 0.20.0 version.

The [README.md](https://github.com/prometheus/jmx_exporter) has the information for configuration. There shouldn't be anything special for Windows.

The integration tests resources files provide various configuration examples:

https://github.com/prometheus/jmx_exporter/tree/main/integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/http/authentication

https://github.com/prometheus/jmx_exporter/tree/main/integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/http/ssl

Example with basic authentication and SSL:

https://github.com/prometheus/jmx_exporter/blob/main/integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/http/CompleteHttpServerConfigurationTest/JavaAgent/exporter.yaml

**Comment by GeluConstantin** [comment]
Hi,

I tried with the Version 20 and I can confirm that the basic authentication with SSL works.

Thank you again for the fast reply.

Constantin

**Comment by dhoard** [comment]
Resolved
