### ISSUE TITLE
Can't I use the jmx_exporter/example_configs/kafka-2_0_0.yml file in KRaft mode?

### ISSUE THREAD

**Issue by topyheun** [prometheus/jmx_exporter#881]
I saw the PR for the title and content. In response to this PR, there was a reply to refer to https://cwiki.apache.org/confluence/display/KAFKA/KIP-835%3A+Monitor+KRaft+Controller+Quorum+Health. I tried to access the site and refer to it, but I had difficulty. Are there any other materials?

**Comment by dhoard** [comment]
Currently, there is no Kafka KRaft example. Maintaining examples for every application is difficult and really should be provided by the community.

PRs are always welcome.
