### ISSUE TITLE
ObjectName not found using queryNames

### ISSUE THREAD

**Issue by cfrantsen** [prometheus/jmx_exporter#89]
I found something strange with the _jboss.as:management-root=server_ mBean, `beanConn.queryNames(null, null)` and `beanConn.getMBeanInfo(mbeanName)` finds it but not `beanConn.queryNames(name, null)`.

This behavior results in the jmx_exporter not finding the mBean if I add _jboss.as:management-root=server_ to the whitelist, the only configuration workaround I have found so far is not using a whitelist at all or to whitelist the whole _jboss.as_ domain but this adds a huge amount of mBeans to the scrape list resulting in 8-10x increased scrape durations (20+ seconds on a server with no deployments or application configuration).

The following change to the scraper code that generates the whitelist seems to solve the problem

```
            for (ObjectName name : whitelistObjectNames) {
                if (name == null || name.toString().contains("*")) {
                  mBeanNames.addAll(beanConn.queryNames(name, null));
                } else {
                  mBeanNames.add(name);
                }
            }
```

**Comment by brian-brazil** [comment]
Per the docs, `jboss.as:management-root=server` should work. Do you know why it isn't?

Your suggested fix is not correct, as it doesn't handle `?` and doesn't allow for the fact that these are patterns on names - not the names themselves.

**Comment by icetrain** [comment]
I'm at a loss as to why that mBean doesn't work with queryNames.

My intention with the above "fix" was to detect patterns and if a bare name was found then just add it to the scrape list and let `scrapeBean()` detect and handle invalid names etc.

**Comment by brian-brazil** [comment]
ObjectNames aren't bare names though, they're patterns, so we can't just use them as mBeanNames.

**Comment by icetrain** [comment]
From reading https://docs.oracle.com/javase/7/docs/api/javax/management/ObjectName.html i gathered that an ObjectName can represent either an object name or an object pattern.

In my case I'm adding an object name (no wildcard) to the whitelist and this is usable as is by `getMBeanInfo()`

**Comment by brian-brazil** [comment]
The problem is we can't distinguish between a pattern, and a mbean name.

**Comment by icetrain** [comment]
Why not? I don't quite follow :-) 

If an ObjectName name contains wildcards it's a pattern, if not ObjectName name == mbean name no?

**Comment by brian-brazil** [comment]
You're correct, I misread the docs.

This still leaves the question as to why the query isn't working.

**Comment by icetrain** [comment]
Asked for help on the [WildFly forums](https://developer.jboss.org/thread/272753) and the suggested code works but is very slow. queryMBeans() finds the beans though and is very similar to using queryNames(). I'l create a PR for this so you can have a look.
