### ISSUE TITLE
How to create hpa kubernetes based on heap consommation

### ISSUE THREAD

**Issue by calvinShan** [prometheus/jmx_exporter#895]
Creating a Horizontal Pod Autoscaler (HPA) in Kubernetes based on heap consumption?
In standard Kubernetes cluster

Because the cpu and memory cannot reflect the applicaiton situation

**Comment by dhoard** [comment]
@calvinShan An HPA based on CPU and memory can be done natively in k8s. I'm not sure how this applies to the JMX Exporter.
