### ISSUE TITLE
Does the expiry/renewal of certificates in jmx_exporter, require restart of service or is it automatically reloaded.

### ISSUE THREAD

**Issue by AVESH-RAI** [prometheus/jmx_exporter#899]
On certificate expiry, can the jmx_exporter automatically reload the new/modified certificates or it requires a restart of the application/container. 
https://github.com/prometheus/jmx_exporter

**Comment by dhoard** [comment]
The application will have to be restarted.

**Comment by AVESH-RAI** [comment]
Thanks @dhoard for your input.
