### ISSUE TITLE
High memory usage by jmx_exporter when connecting to Kafka

### ISSUE THREAD

**Issue by i4yyds** [prometheus/jmx_exporter#900]
Hi,
I'm using jmx_exporter to connect to Kafka, and I noticed that it is consuming a significant amount of memory, around 600MB. I'm wondering why it requires such a large amount of memory.
I have considered a few factors that could contribute to this high memory usage, such as the number of MBeans being monitored, the size of exported metric values, and the export frequency. However, I would appreciate some insights from the Prometheus team regarding any specific reasons or potential optimizations for reducing the memory footprint of jmx_exporter in this scenario.
Could you please shed some light on why jmx_exporter might be consuming this much memory and provide any suggestions or best practices for optimizing its memory usage?
Thank you for your assistance!
Best regards,

**Comment by dhoard** [comment]
See https://github.com/prometheus/jmx_exporter/issues/685#issuecomment-1510659512

Depending on your Kafka rules, this could be large.
