### ISSUE TITLE
Example config for Tomcat

### ISSUE THREAD

**Issue by danlz** [prometheus/jmx_exporter#902]
https://github.com/prometheus/jmx_exporter/blob/main/example_configs/tomcat.yml

You have to add a rule for exporting the `java_lang_operatingsystem_*` properties, ie:
 ```
  - pattern: 'java.lang<type=OperatingSystem><>(.*):'
    name: java_lang_operatingsystem_$1
    type: COUNTER
```

**Comment by dhoard** [comment]
@danlz Can you provide usage context? Are you using the exporter in agent mode or standalone mode?

**Comment by danlz** [comment]
I'm using it in agent mode.
You are including the java.lang:type=OperatingSystem MBean, but not exposing any of its attributes.

**Comment by dhoard** [comment]
@danlz the issue with adding an OperatingSystem MBean rule is that it's only valid in agent mode. In standalone mode, the OperatingSystem MBean would refer to the standalone exporter's JVM which would produce misleading.

I'm included to remove `"java.lang:type=OperatingSystem"` from the `whitelistObjectNames` configuration.

Thoughts?

**Comment by danlz** [comment]
ok, the config will be consistent.
