### ISSUE TITLE
How can I send metrics simultaneously for kafka metrics and for kafka connect

### ISSUE THREAD

**Issue by gemini2186** [prometheus/jmx_exporter#910]
Can you help me?
I have kafka cluster and i need to monitor Kafka brokers and Kafka Connect to Prometheus (and next in Grafana), what settings need to be made for the jmx_exporter?
thank you!

**Comment by dhoard** [comment]
@gemini2186 You have to add the JMX Exporter agent to your processes (broker and Connect) along with configuration.

I would start with https://github.com/confluentinc/jmx-monitoring-stacks as a good example.
