### ISSUE TITLE
Logging of jmx and alerts what all it can monitor

### ISSUE THREAD

**Issue by bhattanil** [prometheus/jmx_exporter#912]
How to log the log,
What all thing it can monitor
What will be configuration to monitoring every thing related to application.
How to monitor datasource checks 
What it is stuck and using high cpu and memory resources.
What is the reason it stuck and we need to restart exporter in 2 or 3 months.
Version I am using. Latest

**Comment by dhoard** [comment]
> How to log the log,
> What all thing it can monitor

The JMX exporter exposes a REST API endpoint to return MBean metrics in either Prometheus or OpenMetrics format.

> What will be configuration to monitoring every thing related to application.

The README.md and sample configuration files show how to configure the JMX Exporter to monitor a Java application

> How to monitor datasource checks

If a datasource exposed MBean, then the JMX Exporter can be configured to capture the datasource metrics

> What it is stuck and using high cpu and memory resources.

An application that is "stuck" or dead-locked is not addressed. CPU needs to be monitored via a standard OS process monitoring tool. The JMX Exporter can monitor the Java heap (JVM metrics), but you should also monitor it a OS process

> What is the reason it stuck and we need to restart exporter in 2 or 3 months.

The use of the word "Stuck" is not clear. Are metrics being exported? Is the JMX Exporter returning metrics? What error are you seeing? etc.
