### ISSUE TITLE
difference between metrics in jmx exporter

### ISSUE THREAD

**Issue by acharbha** [prometheus/jmx_exporter#915]
my `/opt/activemq/conf/jmxexporter.yml` is configured to enable all metrics -
echo 'rules:
- pattern: ".*"' > /opt/activemq/conf/jmxexporter.yml

I would like to understand the difference between these 2 metrics, are they same if so why there's a difference and if they are different why do we say same name java heap memory ?
Can someone please help me understand this ?

```bash
# HELP jvm_memory_bytes_used Used bytes of a given JVM memory area.
# TYPE jvm_memory_bytes_used gauge
jvm_memory_bytes_used{area="heap",} 5.694892E7

# HELP java_lang_Memory_HeapMemoryUsage_used java.lang.management.MemoryUsage java.lang:name=null,type=Memory,attribute=used
# TYPE java_lang_Memory_HeapMemoryUsage_used untyped
java_lang_Memory_HeapMemoryUsage_used 6.21918E7
```

**Comment by dhoard** [comment]
The metrics use the same Java MBean `java.lang:type=MemoryPool` but collect the value at different times. If the heap usage changes between calls to the MBean, you will have different values.
