### ISSUE TITLE
Metrics for a specific process

### ISSUE THREAD

**Issue by kenytux** [prometheus/jmx_exporter#925]
Hello,
I want to get metrics from a specific java application process (Like memory and cpu usage)
Does it possible?

**Comment by dhoard** [comment]
The exporter will provide access to JMX metrics exposed from the Java application process, but you still need/should do application monitoring at the OS level.

**Comment by kenytux** [comment]
For example, if I have an application  called myapp, can I have it's memory usage (Like 8gb for myapp)?

**Comment by dhoard** [comment]
Yes. Here is a list of built-in Java MBeans:

https://docs.oracle.com/javase/8/docs/api/java/lang/management/PlatformManagedObject.html

**Comment by kenytux** [comment]
Thank you
I will take a look

**Comment by kenytux** [comment]
Can you help me more?

**Comment by dhoard** [comment]
The documentation (`README.md`) describes the installation and configuration in general terms, but the nuances are related to your specific application, deployment environment, etc.

I would start with "Running the Agent" https://github.com/prometheus/jmx_exporter?tab=readme-ov-file#running-the-java-agent.
