### ISSUE TITLE
Plan for release with Prometheus Client 1.x?

### ISSUE THREAD

**Issue by aartigao** [prometheus/jmx_exporter#935]
Hi! I wonder, since #886 was merged 2 months ago, if you have plans to release it.

Maybe with a Release Candidate or a SNAPSHOT so we can test it in our envs. We've a project that embeds the JMX exporter JAR but this is the only one using Prometheus Client 0.x.

Thanks! 🙏🏽

**Comment by dhoard** [comment]
@aartigao version 1.0.1 has been released.
