### ISSUE TITLE
no main manifest attribute, in jmx_prometheus_javaagent-0.19.0.jar

### ISSUE THREAD

**Issue by BIPINAIREE** [prometheus/jmx_exporter#939]
while running the agent -
java -javaagent:./jmx_prometheus_javaagent-0.19.0.jar=12345:kafka-0-8-2.yml -jar jmx_prometheus_javaagent-0.19.0.jar

getting the message that -- no main manifest attribute, in jmx_prometheus_javaagent-0.19.0.jar

please help to fix that or share the new command

**Comment by dhoard** [comment]
You have to add the Java agent jar (`jmx_prometheus_javaagent-0.20-0.jar`) and configuration file (`config.yaml`) to your executable jar. The paths are either absolution or relative to your working directory.

```
java -javaagent:./jmx_prometheus_javaagent-0.20-0.jar=12345:config.yaml -jar yourJar.jar
```
