### ISSUE TITLE
 java agent jmx_exporter port will not be released immediately

### ISSUE THREAD

**Issue by eisig** [prometheus/jmx_exporter#94]
I use jmx exporter java agent to monitor tomcat. When I shut down tomcat, the jmx_exporter port will not be released immediately;(May be 30s or longer).
So when restarting  tomcat, it will fail.

**Comment by brian-brazil** [comment]
This is how TCP sockets work due to the TIME_WAIT state. It looks like we need to upgrade our jetty to include https://bugs.eclipse.org/bugs/show_bug.cgi?id=461133

**Comment by brian-brazil** [comment]
Unfortunately this upgrade would require dropping Java 6 support, so we're stuck with it this way.

**Comment by abuwahid007** [comment]
We have deployed jmx_prometheus_javaagent-0.3.1.jar and we are observing problem with Jboss 7 with jdk 1.7.  Kindly let me know the fix.
