### ISSUE TITLE
Hazelcast Metrics are not showing

### ISSUE THREAD

**Issue by Nirzak** [prometheus/jmx_exporter#941]
Hi, I am using the following rule to capture hazelcast metrics using JMX.

```
  - pattern: "^com.hazelcast<type=Metrics,instance=(.+),prefix=(.+),tag0=(.+)><>(.+):"
    name: hazelcast_$4
    attrNameSnakeCase: true
    labels:
      instance: $1
      prefix: $2
      tag0: $3
```

But the metrics are not showing on /metrics endpoint. but on the log it's showing that the metrics are scraping successfully from mbean. 

The log:
18-Apr-2024 04:50:14.448 FINE [prometheus-http-1-1] io.prometheus.jmx.logger.Logger.log com.hazelcast:type=Metrics,instance=hz-auth-inst
ance,prefix=executor.internal,tag0="name=hz:cluster:event"_completedTasks process
18-Apr-2024 04:50:14.448 FINE [prometheus-http-1-1] io.prometheus.jmx.logger.Logger.log com.hazelcast{type=Metrics, instance=hz-auth-ins
tance, prefix=executor.internal, tag0="name=hz:cluster:event"}completedTasks scrape: 12
18-Apr-2024 04:50:14.448 FINE [prometheus-http-1-1] io.prometheus.jmx.logger.Logger.log com.hazelcast:type=Metrics,instance=hz-auth-inst
ance,prefix=executor.internal,tag0="name=hz:cluster:event"_queueSize process
18-Apr-2024 04:50:14.448 FINE [prometheus-http-1-1] io.prometheus.jmx.logger.Logger.log com.hazelcast:type=Metrics,instance=hz-auth-inst
ance,prefix=executor.internal,tag0="name=hz:cluster:event"_maximumPoolSize process
18-Apr-2024 04:50:14.448 FINE [prometheus-http-1-1] io.prometheus.jmx.logger.Logger.log com.hazelcast{type=Metrics, instance=hz-auth-ins
tance, prefix=executor.internal, tag0="name=hz:cluster:event"}maximumPoolSize scrape: 1
18-Apr-2024 04:50:14.448 FINE [prometheus-http-1-1] io.prometheus.jmx.logger.Logger.log com.hazelcast:type=Metrics,instance=hz-auth-inst
ance,prefix=executor.internal,tag0="name=hz:cluster:event"_remainingQueueCapacity process
18-Apr-2024 04:50:14.448 FINE [prometheus-http-1-1] io.prometheus.jmx.logger.Logger.log com.hazelcast{type=Metrics, instance=hz-auth-ins
tance, prefix=executor.internal, tag0="name=hz:cluster:event"}remainingQueueCapacity scrape: 2147483647

**Comment by Nirzak** [comment]
HI I was able to fix the problem. So I am going to create a PR to add an example config for hazelcast in prometheus JMX exporter. Thanks

**Comment by dhoard** [comment]
Issue resolved
