### ISSUE TITLE
Failed to find Premain-Class manifest attribute in jmx_exporter.jar

### ISSUE THREAD

**Issue by shpsec-dennis** [prometheus/jmx_exporter#96]
Hi,

With the following args to the JVM:

`-javaagent:jmx_exporter.jar=9400:jmx_exporter.yml
`
Where jmx_exporter.yaml is just:

`{}`

I see the following error when trying to start the JVM:

```
Failed to find Premain-Class manifest attribute in jmx_exporter.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```

I am using a jar with the file size 19896 kb collector-0.8-SNAPSHOT.jar which I just checked out a couple of days ago.

**Comment by brian-brazil** [comment]
You need jmx_prometheus_javaagent, the collector is just a library.

**Comment by shpsec-dennis** [comment]
Thanks for the quick response! That was it.
