### ISSUE TITLE
[Feature Request] Add optional parameter to delay the agent startup

### ISSUE THREAD

**Issue by sdurrheimer** [prometheus/jmx_exporter#97]
This would help with applications having trouble being queried by Prometheus during their startup process.

**Comment by brian-brazil** [comment]
Is there an exception we're not catching?

**Comment by sdurrheimer** [comment]
No issues or exception with the jmx_exporter directly. In my case, I have a full-featured application that takes about 2min to startup. During the starting process, if my Prometheus instance try to scrape the jmx_exporter, some component of the application fail to initialize (I don't really know why, but maybe due to the fact that the jmx_exporter is querying the JVM for metrics at the same time).

The real solution would be to try to fix this bug in this (proprietary) application, or even use direct instrumentation with the java_client, but for now we don't have the time/budget for it.

We talked briefly of this on IRC, and you suggest to add a timeout on start as a "quick solution" to avoid the problem.

**Comment by sdurrheimer** [comment]
@brian-brazil do you think this is something we can do ?

**Comment by brian-brazil** [comment]
Feel free to send a PR

**Comment by cfrantsen** [comment]
This would be useful for me to as we are seeing alot of error log when starting WildFly if prometheus happens to scrape the java agent during startup.

Until I get around to looking at this, here is an example of how to implement this if someone else feels like taking a look at it :)

https://github.com/jmxtrans/jmxtrans-agent/blob/master/src/main/java/org/jmxtrans/agent/JmxTransAgent.java#L68

**Comment by samueletonon** [comment]
+1 on this feature as we are facing the same problem

**Comment by qixiaobo** [comment]
Any progress?

**Comment by qixiaobo** [comment]
> Any progress?
Sorry for not see this pr! It's a great work to handle with my init error!
