### ISSUE TITLE
Extracting PM metrics on Kafka Cluster results in duplicate files due to different cases in the same metric names.

### ISSUE THREAD

**Issue by secureaniruddha** [prometheus/jmx_exporter#980]
One of our customers is trying to extract PM metrics logs and has encountered duplicate files due to different cases with the same metrics names. This means one file contains metrics entries in uppercase and another in lowercase. They want to know if all `java_lang` related PM metrics entries can be configured in lowercase to avoid file duplication. 

Is it possible to configure all `java_lang` related metrics entries in lowercase, and is it recommended?

[metrics. zip](https://github.com/user-attachments/files/15926874/metrics.zip)

**Comment by secureaniruddha** [comment]
Hi @dhoard  Thanks for the swift reply. If there is no option for per metric configuration, can we ensure there should be a single file in any case to avoid duplication?

**Comment by dhoard** [comment]
@secureaniruddha there is no per-metric configuration to convert the metric name to lowercase. Typically `lowercaseOutputName: true` is used for metric name consistency.

Can you elaborate on what you mean by "file duplication"?

**Comment by secureaniruddha** [comment]
@dhoard  After CCRC upgraded to 1.16 D102, DDC files can be generated ok, but extracting pm metrics files has duplicated files in windows. The duplicated files' content are different, and file names differences are: capital letters and lowercase. Example printout:
![image](https://github.com/prometheus/jmx_exporter/assets/107193436/06ae1580-9127-42b0-bc9b-8b0108b18f4f)

On linux this leads to an inconsistency because different case filenames are treated as different files (it still is an issue of different contents and writing to different places). On Windows it's more pressing issue, since same name different case files overwrite one another, and the metrics data is essentially lost.

**See attached files as example:**
PMjava_lang_**CodeHeap_non_profiled_nmethods_Valid**-20240510T083355+0200-20240510T090355+0200.json
PMjava_lang_**codeheap_non_profiled_nmethods_valid**-20240510T083355+0200-20240510T090355+0200_1.json
 
**Checking the metrics from CLI directly:**
ccrc-admin@ccrc41#metrics-query java_lang_CodeHeap_non_nmethods_Valid
{
    "data": {
        "result": [
            {
                "metric": {
                    "__name__": "java_lang_CodeHeap_non_nmethods_Valid",
                    "instance": "192.168.197.5:9072",
                    "job": "k8s-endpoints-15s-http-2",
                    "kubernetes_name": "eric-data-message-bus-kf",
                    "kubernetes_namespace": "eric-ccrc",
                    "namespace": "eric-ccrc",
                    "pod_name": "eric-data-message-bus-kf-2",
                    "service_name": "eric-data-message-bus-kf",
                    "type": "MemoryPool"
                },
                "value": [
                    "2024-05-12T16:03:53Z",
                    "1"
                ]
            },
            {
                "metric": {
                    "__name__": "java_lang_CodeHeap_non_nmethods_Valid",
                    "instance": "192.168.99.136:9072",
                    "job": "k8s-endpoints-15s-http-2",
                    "kubernetes_name": "eric-data-message-bus-kf",
                    "kubernetes_namespace": "eric-ccrc",
                    "namespace": "eric-ccrc",
                    "pod_name": "eric-data-message-bus-kf-1",
                    "service_name": "eric-data-message-bus-kf",
                    "type": "MemoryPool"
                },
                "value": [
                    "2024-05-12T16:03:53Z",
                    "1"
                ]
            }
        ],
        "resultType": "vector"
    },
    "status": "success"
}
ccrc-admin@ccrc41#
ccrc-admin@ccrc41#
ccrc-admin@ccrc41#metrics-query java_lang_codeheap_non_nmethods_valid
{
    "data": {
        "result": [
            {
                "metric": {
                    "__name__": "java_lang_codeheap_non_nmethods_valid",
                    "app_kubernetes_io_instance": "pi-ccrc-vnf41-4",
                    "app_kubernetes_io_name": "eric-nrf-kvdb-ag",
                    "app_kubernetes_io_version": "9.2.0_67",
                    "dr_egress_kvdb": "true",
                    "geode_cluster": "eric-nrf-kvdb-ag",
                    "instance": "eric-nrf-kvdb-ag-locator.eric-ccrc.svc:8081",
                    "job": "oldScrape-service",
                    "namespace": "eric-ccrc",
                    "sidecar_istio_io_inject": "true",
                    "type": "MemoryPool"
                },
                "value": [
                    "2024-05-12T16:04:01Z",
                    "1"
                ]
            },
            {
                "metric": {
                    "__name__": "java_lang_codeheap_non_nmethods_valid",
                    "app_kubernetes_io_instance": "pi-ccrc-vnf41-4",
                    "app_kubernetes_io_name": "eric-nssf-kvdb-ag",
                    "app_kubernetes_io_version": "9.2.0_67",
                    "dr_egress_nssf_kvdb": "true",
                    "geode_cluster": "eric-nssf-kvdb-ag",
                    "instance": "eric-nssf-kvdb-ag-locator.eric-ccrc.svc:8081",
                    "job": "oldScrape-service",
                    "namespace": "eric-ccrc",
                    "sidecar_istio_io_inject": "true",
                    "type": "MemoryPool"
                },
                "value": [
                    "2024-05-12T16:04:01Z",
                    "1"
                ]
            }
        ],
        "resultType": "vector"
    },
    "status": "success"
}
ccrc-admin@ccrc41#

**Comment by dhoard** [comment]
@secureaniruddha This sounds like an issue with the CCRC tool, since the exporter only exposed metrics via HTTP(S).
