### ISSUE TITLE
Inconsistency in WebLogic MBean Retrieval Between JMX Exporter Versions 0.17.2 and 1.0.1

### ISSUE THREAD

**Issue by Sophisycho** [prometheus/jmx_exporter#998]
Hi JMX Exporter team,

I've been using your project for WebLogic monitoring and noticed something strange between versions 0.17.2 and 1.0.1. In 0.17.2, I can retrieve WebLogic MBeans without needing to add the following JVM argument:

```
-Djavax.management.builder.initial=weblogic.management.jmx.mbeanserver.WLSMBeanServerBuilder
```

But when I switched to version 1.0.1, I had to add this option for the MBeans to show up. It seems odd since I thought this option was supposed to be mandatory across all versions.

Could you shed some light on why this is happening? Is this an intentional change in newer versions, or is there something else going on? 

Thanks in advance for any clarification!

Best regards

**Comment by dhoard** [comment]
@Sophisycho I'm unaware of any changes in the exporter code that would change the behavior.

Looking at the relevant code in `0.17.2` and `1.0.1` the only change was to allow RMI to the registry without SSL...

`0.17.2`

https://github.com/prometheus/jmx_exporter/blob/4bbb8ed6a25b5ce1e05ba9e0d10c884d0ca3f25a/collector/src/main/java/io/prometheus/jmx/JmxScraper.java#L80-L96

`1.0.1`

https://github.com/prometheus/jmx_exporter/blob/a4f4c5ffb0d15ef26eb6a1b45ec2fd48fca837a3/collector/src/main/java/io/prometheus/jmx/JmxScraper.java#L106-L130

**Comment by dhoard** [comment]
@Sophisycho I suspect it's related to https://github.com/prometheus/jmx_exporter/issues/128

I would try using `startDelaySeconds`.

This will delay initial metrics collection/prevent calls to `ManagementFactory.getPlatformMBeanServer()` in scenarios where a custom `MBeanServer` implementation is being used.
